### ISSUE TITLE
Building x64 version with MinGW-w64

### ISSUE THREAD

**Issue by teepean** [dhewm/dhewm3#1]
I am trying to build x64 version of Doom 3 on Windows but cmake seems to insist on building the x86 version. Are there any command line options I can use to force the x86_64 build?

**Comment by Sophist-UK** [comment]
I know this issue is closed, but is there a pre-built 64-bit version for Windows? The releases page only has a 32-bit version (which works fine).

**Comment by DanielGibson** [comment]
No there isn't, because the 32bit version works fine ;)
