### ISSUE TITLE
SDL2 build ignores keyboard input (with mingw)

### ISSUE THREAD

**Issue by kortemik** [dhewm/dhewm3#100]
Using SDL2 with mingw triggers SDL_TEXTEDITING event which is not handled and therefore keyboard input is ignored.

**Comment by Eleuin** [comment]
there is definitely still an issue with SDL2 mingw builds ignoring keyboard input on startup, however, it is regained by alt-tabbing out of the game and alt-tabbing back in

**Comment by Eleuin** [comment]
this still needs to be addressed. this should really be bumped

**Comment by DanielGibson** [comment]
can you try if just using the latest SDL2.dll from http://libsdl.org/download-2.0.php changes anything?

**Comment by DanielGibson** [comment]
I get this in a build with MSVC2010 in a winxp VM as well, using SDL 2.0.4RC2

I can walk around, but windows does its error-dong-sound whenever I hit a key. I can not type in the console. alt-tabbing out and in again fixes it.
