### ISSUE TITLE
demo support

### ISSUE THREAD

**Issue by a-detiste** [dhewm/dhewm3#105]
Is there any support for the demo version of this game ?

I found this demo version, but I can't get it to work with dhewm3;
it allways complains about `Couldn't load default.cfg`

Can you document this on the FAQ ?

http://www.fileplanet.com/145822/download/DOOM-3-Demo (461Mb)
`.wine/drive_c/Program Files/Doom 3 Demo/demo/demo00.pk4`

```shell
unzip -l  /usr/local/share/dhewm3/base/demo00.pk4 | grep cfg
     1774  2004-08-04 11:12   default.cfg
```

@smcv @coldtobi

**Comment by DanielGibson** [comment]
No, there isn't.

The demo data is of an older version of doom3, while the GPL version of doom3 and thus also dhewm3 only support doom3 1.3.1.

I added this to https://github.com/dhewm/dhewm3/wiki/FAQ

**Comment by a-detiste** [comment]
Thanks for fast answer :+1:

**Comment by DanielGibson** [comment]
oh by the way, the Doom3 demo is now supported (in 1.5.1)
