### ISSUE TITLE
Fixing some spelling errors: s/unkown/unknown, s/seperate/separate.

### ISSUE THREAD

**Issue by coldtobi** [dhewm/dhewm3#107]
Description: Fixing some spelling errors
Those words are fixed: s/unkown/unknown, s/seperate/separate.
Fixes are only done in code, comments are only touch when the there was also
a code location to fix in the same file.

Patch https://gist.github.com/coldtobi/ee31ed1a3e83f71afb26

Will make a merge request with this.

**Comment by DanielGibson** [comment]
merged it, thanks.
just the merge request would have been enough ;-)
