### ISSUE TITLE
Win32 icon

### ISSUE THREAD

**Issue by svdijk** [dhewm/dhewm3#115]
For the release discussed in #106, it would probably be good to add an icon to the windows .exe. For an MSVS build, including a simple .rc file in the src_sys_core list in CMakeLists.txt should be enough I believe, but for a MinGW (cross-)build some more magic may be needed...

**Comment by DanielGibson** [comment]
merge requests are welcome ;-)

At least when using SDL2 we have a window icon now without using .rc, but the exe itself has no icon. Would be great if you could make it work with mingw too, I think it's supported.

**Comment by DanielGibson** [comment]
Smallish update: In fact it should work with both mingw and MSVC - I guess I'll build the official  release binaries in MSVC so I don't have to bundle mingw dlls.

**Comment by svdijk** [comment]
I just created pull-request for this, #121.

**Comment by DanielGibson** [comment]
Merged.

Thanks a lot!
