### ISSUE TITLE
net_clientMaxRate does nothing

### ISSUE THREAD

**Issue by Wintch** [dhewm/dhewm3#117]
This is not really dhewm's problem as in legacy Doom3 code it is not working also.
But as cvar "net_clientMaxRate" does nothing, maybe we could change it's description in order to avoid trying to use it

**Comment by DanielGibson** [comment]
nope, it *is* used, it ends up in `serverClient_t::clientRate` and `serverClient_t.channel.maxRate`, via `idAsyncClient::SetupConnection()` (`msg.WriteInt( cvarSystem->GetCVarInteger( "net_clientMaxRate" ) );`) => network message => `idAsyncServer::ConnectionlessMessage()` ("connect" case) =>  `idAsyncServer::ProcessConnectMessage()` => `idAsyncServer::InitClient()`
