### ISSUE TITLE
new game console 

### ISSUE THREAD

**Issue by lvilches21** [dhewm/dhewm3#119]
good,
my name is Luis Vilches, I am from Chile.

I am in the process of forming a team to develop a new video game based on the Linux operating system and I wonder if they will launch a version of the game, if so I hope to give support to the console that is developed or perhaps work together on this project, if you're interested of course.
Thank you

lvilches21@gmail.com

**Comment by DanielGibson** [comment]
feel free to port dhewm3 to your console, if your do and do any changes/improvements to dhewm3 on the way, pull requests are welcome :)

I'm afraid I don't have time to do the porting myself, though.
