### ISSUE TITLE
Assertion during fight with Cyberdemon

### ISSUE THREAD

**Issue by DanielGibson** [dhewm/dhewm3#122]
From http://idtechforums.fuzzylogicinc.com/index.php?topic=314.0
On "Windows 7 64-bit Ultimate SP 1" when fighting the Cyberdemon, Phrozo got the following error:

![d3_cyberdemon_assertion](https://cloud.githubusercontent.com/assets/1216493/10268327/5752a2c0-6ab5-11e5-8394-c71dfbadc254.png)

The Cyberdemon occurs in the "Primary Excavation Site" level (`map game/hellhole.map`)

**Comment by andre-d** [comment]
Debug builds have more asset exceptions enabled than release and some
assets shipped broken.

**Comment by DanielGibson** [comment]
So far I couldn't even reproduce it with a win32 debug build (on winxp in a VM though, I'll try on win7 64bit later)

**Comment by DanielGibson** [comment]
Couldn't reproduce on Win7 either. Strange. I killed the Cyberdemon >10 times today on different hardware and operating systems, but never triggered that assertion.

I hope Phrozo will give me some more information on how to reproduce.

**Comment by svdijk** [comment]
Is this assert needed to prevent worse things from happening, or is it "just" a sanity check intended to be useful during development? If the latter, releases could be build with -DNDEBUG to disable assertions...

**Comment by DanielGibson** [comment]
I think it tries to make sure that bounding boxes don't become negative when being subtracted from.. I think they really shouldn't be negative, but I have no idea what kind of bad things happen if they are.

Phrozo wasn't able to reproduce the problem either, so I guess it won't be fixed for release :-/
Fortunately, it seems to occur very rarely.

**Comment by DanielGibson** [comment]
I think I "accidentally" reproduced this while playing d3xp's last level (game/hell). it  seems to happen occasionally when using the BFG, the whole backtrace looks like

```
#0  AssertFailed (file=0xffff <error: Cannot access memory at address 0xffff>, line=108, 
    expression=0x5d325b5d305b622e <error: Cannot access memory at address 0x5d325b5d305b622e>)
    at dhewm3/neo/idlib/Lib.cpp:518
#1  0x00007fffde61703e in idBounds::operator- (this=0x7fffffffc9a8, a=...)
    at dhewm3/neo/idlib/bv/Bounds.h:173
#2  0x00007fffde60f3b0 in idWeapon::Event_LaunchProjectiles (this=<optimized out>, num_projectiles=<optimized out>, 
    spread=<optimized out>, fuseOffset=<optimized out>, launchPower=<optimized out>, dmgPower=<optimized out>)
    at dhewm3/neo/d3xp/Weapon.cpp:3449
#3  0x00007fffde642e44 in idClass::ProcessEventArgPtr (this=<optimized out>, ev=<optimized out>, 
    data=0x7fffffffcb20) at dhewm3/neo/d3xp/gamesys/Callbacks.cpp:362
#4  0x00007fffde67137c in idInterpreter::CallEvent (this=0x102f2f3c, func=<optimized out>, argsize=48)
    at dhewm3/neo/d3xp/script/Script_Interpreter.cpp:796
#5  0x00007fffde6722e1 in idInterpreter::Execute (this=0x102f2f3c)
    at dhewm3/neo/d3xp/script/Script_Interpreter.cpp:1009
#6  0x00007fffde67b105 in idThread::Execute (this=0x102f2f24)
    at dhewm3/neo/d3xp/script/Script_Thread.cpp:684
#7  0x00007fffde615226 in idWeapon::UpdateScript (this=0x11c87004)
    at dhewm3/neo/d3xp/Weapon.cpp:2098
#8  0x00007fffde615818 in idWeapon::PresentWeapon (this=0x11c87004, showViewModel=true)
    at dhewm3/neo/d3xp/Weapon.cpp:2194
#9  0x00007fffde5e9849 in idPlayer::Think (this=0xf5436b4)
    at dhewm3/neo/d3xp/Player.cpp:7447
#10 0x00007fffde59bc57 in idGameLocal::RunTimeGroup2 (this=0x7fffde9e5040 <gameLocal>)
    at dhewm3/neo/d3xp/Game_local.cpp:2383
#11 0x00007fffde59c188 in idGameLocal::RunFrame (this=0x7fffde9e5040 <gameLocal>, clientCmds=0x7fffffffde10)
    at dhewm3/neo/d3xp/Game_local.cpp:2531
#12 0x00000000004c8208 in idSessionLocal::RunGameTic (this=0xc82800 <sessLocal>)
    at dhewm3/neo/framework/Session.cpp:2762
#13 0x00000000004ca158 in idSessionLocal::Frame (this=0xc82800 <sessLocal>)
    at dhewm3/neo/framework/Session.cpp:2708
#14 0x0000000000495a18 in idCommonLocal::Frame (this=0xbf2000 <commonLocal>)
    at dhewm3/neo/framework/Common.cpp:2396
#15 0x0000000000570add in main (argc=<optimized out>, argv=<optimized out>)
    at dhewm3/neo/sys/linux/main.cpp:300
```

As a workaround I added a check in idWeapon::Event_LaunchProjectiles() to see if subtracting the `projBounds` from `ownerBounds` is legal.
