### ISSUE TITLE
dhewm3 doesn't work with latest files from steam

### ISSUE THREAD

**Issue by anarsoul** [dhewm/dhewm3#123]
I've got doom3 files from steam on Linux, but dhewm3 doesn't work with them. I believe they're supposed to be zip-archives, but unzip fails to unpack them. md5sum doesn't patch either. Guess they're encrypted?

**Comment by DanielGibson** [comment]
Damn. You're right, I should have actually tested the files I downloaded with download_depot :-/

That's bad news.. unless someone finds a better workaround, you'll have to use windows Steam (on windows or via wine) to install doom3 and get the data files from there.  
I checked on my Windows PC and the pk4 files there can be opened and have the correct md5sum.

**Comment by anarsoul** [comment]
Damn. I have no Windows :(

**Comment by DanielGibson** [comment]
Ok, it seems like each .pk4 file is missing some bytes at the end.

Good data:
```
$ ls -l pak*.pk4
-r-xr-xr-x 1 caedes caedes 353159257 Sep 28 18:12 pak000.pk4
-r-xr-xr-x 1 caedes caedes 229649726 Sep 28 18:12 pak001.pk4
-r-xr-xr-x 1 caedes caedes 416937674 Sep 28 18:12 pak002.pk4
-r-xr-xr-x 1 caedes caedes 317590154 Sep 28 18:12 pak003.pk4
-r-xr-xr-x 1 caedes caedes 237752384 Sep 28 18:12 pak004.pk4
-rw-r--r-- 1 caedes caedes    552334 Sep 28 18:12 pak005.pk4
-rw-r--r-- 1 caedes caedes    218751 Sep 28 18:12 pak006.pk4
-rw-r--r-- 1 caedes caedes    192031 Sep 28 18:12 pak007.pk4
-rw-r--r-- 1 caedes caedes     12243 Sep 28 18:12 pak008.pk4
```

Bad data:
```
$ ls -l pak00*
-rwxr-xr-x 1 caedes caedes 353012464 Oct  3 17:31 pak000.pk4
-rwxr-xr-x 1 caedes caedes 229641552 Oct  3 17:31 pak001.pk4
-rwxr-xr-x 1 caedes caedes 416500720 Oct  3 17:32 pak002.pk4
-rwxr-xr-x 1 caedes caedes 317295072 Oct  3 17:32 pak003.pk4
-rwxr-xr-x 1 caedes caedes 237434288 Oct  3 17:33 pak004.pk4
-rwxr-xr-x 1 caedes caedes    547840 Oct  3 17:33 pak005.pk4
-rwxr-xr-x 1 caedes caedes    213776 Oct  3 17:33 pak006.pk4
-rwxr-xr-x 1 caedes caedes    187904 Oct  3 17:33 pak007.pk4
-rwxr-xr-x 1 caedes caedes     12224 Oct  3 17:33 pak008.pk4

$ md5sum pak00*
58fab6fd7fe4eff7f66df62dffb5aff5  pak000.pk4
40386b8d6910c2dad4bf504c9e5ba236  pak001.pk4
8f1c37d34bb2987cad206583136777df  pak002.pk4
66e4d51ce94b0b709d5cf63189493962  pak003.pk4
351b23fc51676ae9c54ece90c688e908  pak004.pk4
ba47a8aa79d96d1d80e1ec0138f913ec  pak005.pk4
37e15aed33170957d4929fc79fd43835  pak006.pk4
87179b75f4fdc28ebd0c9e15add1f7b8  pak007.pk4
472dd2311aa381dc7c533b60b39b5ce6  pak008.pk4
```

As you can see, the files are a bit smaller. To verify my assumption, I dd'ed this amount of bytes of some "good" pk4 files into a new file and took its md5sum - it matches with the broken data!
```
 $ dd if=pak008.pk4 of=pak008.test bs=1 count=12224
12224+0 records in
12224+0 records out
12224 bytes (12 kB) copied, 0,0174037 s, 702 kB/s
$ md5sum pak008.test 
472dd2311aa381dc7c533b60b39b5ce6  pak008.test

$ dd if=pak005.pk4 of=pak005.test bs=1 count=547840
547840+0 records in
547840+0 records out
547840 bytes (548 kB) copied, 0,520728 s, 1,1 MB/s
$ md5sum pak005.test 
ba47a8aa79d96d1d80e1ec0138f913ec  pak005.test
```

Not sure what to do with this information.. I don't know yet where the missing data is coming from.

**Comment by DanielGibson** [comment]
(BTW, can you check if your broken data has the same md5sums?)

**Comment by anarsoul** [comment]
b8b60bab3f9dfc97fe73a1f0856be5fb  pak000.pk4
c8315d2e6ed521f334446ecda5b20a56  pak001.pk4
de9579bafa662d82b6e1b6db92bcc4c6  pak002.pk4
3528150e921c23f9d59506fc84f280b5  pak003.pk4
c0c27d507304a83f6c46bd24ef7b6f09  pak004.pk4
ba47a8aa79d96d1d80e1ec0138f913ec  pak005.pk4
37e15aed33170957d4929fc79fd43835  pak006.pk4
87179b75f4fdc28ebd0c9e15add1f7b8  pak007.pk4
472dd2311aa381dc7c533b60b39b5ce6  pak008.pk4

**Comment by anarsoul** [comment]
-rwxr-xr-x 1 vasilykh vasilykh 353012464 Oct  9 17:07 pak000.pk4
-rwxr-xr-x 1 vasilykh vasilykh 229641552 Oct  9 17:12 pak001.pk4
-rwxr-xr-x 1 vasilykh vasilykh 416500720 Oct  9 17:18 pak002.pk4
-rwxr-xr-x 1 vasilykh vasilykh 317295072 Oct  9 17:22 pak003.pk4
-rwxr-xr-x 1 vasilykh vasilykh 237434288 Oct  9 17:25 pak004.pk4
-rwxr-xr-x 1 vasilykh vasilykh    547840 Oct  9 17:25 pak005.pk4
-rwxr-xr-x 1 vasilykh vasilykh    213776 Oct  9 17:25 pak006.pk4
-rwxr-xr-x 1 vasilykh vasilykh    187904 Oct  9 17:25 pak007.pk4
-rwxr-xr-x 1 vasilykh vasilykh     12224 Oct  9 17:25 pak008.pk4

**Comment by DanielGibson** [comment]
oh great, so we don't even have the same broken files.
I just ran download_depot again, and some md5sums changed again:
```
4939f9aca8829e147e81cb3ebc0e4f90  pak000.pk4
3ee50158d6f707261d3b71d9f7a1a99f  pak001.pk4
fe82e6aca5b78b23ff61d7a412098c29  pak002.pk4
ada7015dc701b33a9f4c03324c13c0b8  pak003.pk4
9a89cfaf116fa1449e7da944f0a62e70  pak004.pk4
ba47a8aa79d96d1d80e1ec0138f913ec  pak005.pk4
37e15aed33170957d4929fc79fd43835  pak006.pk4
87179b75f4fdc28ebd0c9e15add1f7b8  pak007.pk4
472dd2311aa381dc7c533b60b39b5ce6  pak008.pk4
```

I guess it's a steam bug :-/

If you don't have windows, you could try running Steam in wine? winetricks makes that pretty easy (at least it used to when I last tried >1year ago)

**Comment by anarsoul** [comment]
OK. Thanks a lot for your help!

**Comment by DanielGibson** [comment]
You're welcome, thanks for trying out dhewm3!  
I'm sorry I couldn't be of any more help.

If I find out anything I'll post it here.

**Comment by anarsoul** [comment]
Just FYI: steam is able to download games with vanilla wine without winetricks. dhewm3 works just fine with files from there.

**Comment by NoXPhasma** [comment]
I don't own Doom 3 on Steam so I can't test this, but you could try to download the game with [SteamCMD](https://developer.valvesoftware.com/wiki/SteamCMD).

There is a command line option to choose Windows as Plattorm: https://www.reddit.com/r/linux_gaming/comments/2uvj4p/linuxgamingprotip_use_steamcmd_download_steam/

**Comment by KuriKai** [comment]
I was able to download with galliumnine wine standard doom3

**Comment by DanielGibson** [comment]
I guess you don't *need* winetricks, but as far as I remember it had a gui where you just had to click "Install Steam" and it did.

@NoXPhasma steamcmd sounds interesting - no idea if it maybe has the same bugs as Steam though - should be tested.

**Comment by DanielGibson** [comment]
steamcmd seems to work!

Install it like described at https://developer.valvesoftware.com/wiki/SteamCMD#Linux (you can skip creating a new user, your normal user will do just fine)  
then run `./steamcmd.sh` once so it downloads itself or whatever it does there, enter `quit` to quit it.  

then you can download doom3 with  
`./steamcmd.sh +@sSteamCmdForcePlatformType windows +login <YOUR_STEAM_LOGIN_NAME> +force_install_dir ./doom3/ +app_update 9050 validate +quit`

when it's done you should have the normal windows installation of doom3 in ./doom3/ with the correct checksums.  
if this works for you as well, I'll add it to the FAQ

**Comment by DanielGibson** [comment]
Ok, I documented how to install with steamcmd in the FAQ.

Thanks for reporting! :-)

**Comment by a-detiste** [comment]
> then run ./steamcmd.sh once so it downloads itself or whatever it does there, enter quit to quit it.

:cry: that's a bit of a pain, I hoped this tool would had been something lightweight like `lgogdownloader` that could be readily used by the meta-installer `game-data-packager` I'm working on.

This tool should automate these 3 items from your FAQ, Doom3 support will be available in the Ubuntu release of this month.
```
- Which game data files are required?
- How do I get the files using Steam?
- Where do I need to put the game data files?
```

**Comment by DanielGibson** [comment]
lgogdownloader obviously won't work because it's steam.  
afaik, steamcmd is the most lightweight way to get gamedata from steam.

anyway, if you had looked at the FAQ you would have noticed that the `then run ./steamcmd.sh once so it downloads itself or whatever it does there, enter quit to quit it.` step is left out there, it also works do directly execute the other command that downloads the game as well.

note that one still needs a steam account and *maybe*, if you don't have steam linux installed and logged in on your computer, you may have to enter your password there as well, don't know, didn't try.
