### ISSUE TITLE
idlib fails to build with Visual Studio 14

### ISSUE THREAD

**Issue by leffmann** [dhewm/dhewm3#124]
Have specified DHEWM3LIBS, and CMake configuration and generation of files for Visual Studio 14 (Community 2015) passes without errors, but running `msbuild idlib.vcxproj` or building from inside Visual Studio fails with loads of these:

dhewm3-master\neo\idlib/math/Matrix.h(2387): error C3861: `_alloca`: identifier not found
dhewm3-master\neo\idlib\math\Matrix.cpp(6582): error C2660: `idVecX::SetData`: function does not take 1 arguments
dhewm3-master\neo\idlib\math\Matrix.cpp(7150): error C2660: `idMatX::SetData`: function does not take 2 arguments
dhewm3-master\neo\idlib\math\Simd.cpp(1399): error C3688: invalid literal suffix `S_COLOR_RED`; literal operator or literal operator template `operator ""S_COLOR_RED` not found

**Comment by DanielGibson** [comment]
https://msdn.microsoft.com/en-us/library/wb1s57t5.aspx# says that it's deprecated, but not that it's not available anymore.  
can you try adding `#include <malloc.h>` at the beginning of Matrix.h?  
that should also fix the errors in Matrix.cpp

about the ine in Simd.cpp I have no idea, I think that code should work?  
does it get better if you replace the line with
`idLib::common->Printf( "   simd->Memcpy() " S_COLOR_RED "X\n" );`
i.e. adding spaces araound S_COLOR_RED?

**Comment by leffmann** [comment]
It worked fine. I've sent a pull request.
