### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [dhewm/dhewm3#125]
I would like to point out that identifiers like "[`__DOOM3_CONFIG_H__`](https://github.com/dhewm/dhewm3/blob/657ad99bf185feb71199c6af097577d037e59d59/neo/config.h.in#L1)" and "[`__MD5_H__`](https://github.com/dhewm/dhewm3/blob/657ad99bf185feb71199c6af097577d037e59d59/neo/idlib/hashing/MD5.h#L1)" [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by DanielGibson** [comment]
changing this would make merging code from other doom3 ports harder.

while I could imagine __MD5_H__ and similar colliding with system headers, __DOOM3_CONFIG_H__ most certainly won't.

so unless this causes real trouble somewhere I'd like to keep it like it is.

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoid undefined behaviour?")?

**Comment by andre-d** [comment]
Is it undefined or implementation defined?

**Comment by elfring** [comment]
Would you like to take [special care for undefined behaviour](https://en.wikipedia.org/wiki/Undefined_behavior "Description for undefined behaviour")?
