### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [dhewm/dhewm3#127]
[Extra null pointer checks are not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for NULL before delete p?") like the following.
* [CPropTree::FreeGlobalResources](https://github.com/dhewm/dhewm3/blob/657ad99bf185feb71199c6af097577d037e59d59/neo/tools/common/PropTree/PropTree.cpp#L256 "CPropTree::FreeGlobalResources function")
* [idAASBuild::Shutdown](https://github.com/dhewm/dhewm3/blob/657ad99bf185feb71199c6af097577d037e59d59/neo/tools/compilers/aas/AASBuild.cpp#L73 "idAASBuild::Shutdown function")
* [idBrushSide](https://github.com/dhewm/dhewm3/blob/657ad99bf185feb71199c6af097577d037e59d59/neo/tools/compilers/aas/Brush.cpp#L100 "Destructor for idBrushSide")
* [idSurface_SweptSpline::SetSpline](https://github.com/dhewm/dhewm3/blob/657ad99bf185feb71199c6af097577d037e59d59/neo/idlib/geometry/Surface_SweptSpline.cpp#L38 "idSurface_SweptSpline::SetSpline function")

**Comment by andre-d** [comment]
The counter argument: http://yosefk.com/c++fqa/heap.html#fqa-16.8

**Comment by andre-d** [comment]
(Just a rant about the FAQ in this case) Regardless its possible ID calls
those methods often and wanted to avoid the extra call when not needed.

**Comment by DanielGibson** [comment]
it doesn't hurt either and changing this makes merging code from other doom3 ports harder.. so I guess we'll keep it like this
