### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [dhewm/dhewm3#128]
Would you like to wrap any pointer data members with the template class "[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "a smart pointer")"?

Update candidates:
* [idODE_Midpoint](https://github.com/dhewm/dhewm3/blob/657ad99bf185feb71199c6af097577d037e59d59/neo/idlib/math/Ode.cpp#L89 "idODE_Midpoint class")
* [idRoutingCache](https://github.com/dhewm/dhewm3/blob/657ad99bf185feb71199c6af097577d037e59d59/neo/game/ai/AAS_routing.cpp#L46 "idRoutingCache class")

**Comment by DanielGibson** [comment]
nope
