### ISSUE TITLE
Fix signal handler

### ISSUE THREAD

**Issue by elfring** [dhewm/dhewm3#129]
[The function "Printf"](https://github.com/dhewm/dhewm3/blob/master/neo/framework/Common.cpp#L413 "Formatted output") does not belong to the list of [async-signal-safe functions](https://www.securecoding.cert.org/confluence/display/c/SIG30-C.+Call+only+asynchronous-safe+functions+within+signal+handlers "Call only asynchronous-safe functions within signal handlers.").
How do you think about to delete its call from your function "[got_SIGPIPE](https://github.com/dhewm/dhewm3/blob/657ad99bf185feb71199c6af097577d037e59d59/neo/sys/posix/posix_net.cpp#L678 "Check signal handling implementation.")"?

**Comment by DanielGibson** [comment]
> For strictly conforming programs, only the C standard library functions abort(), _Exit(), quick_exit(), and signal() can be safely called from within a signal handler.

I don't think this aims for strict conformance, it's just a game ;-)

**Comment by elfring** [comment]
Would you like to consider other software design options?
* [sigwaitinfo()](http://pubs.opengroup.org/onlinepubs/9699919799/functions/sigwaitinfo.html "wait for queued signals")
* [Self-pipe trick](http://cr.yp.to/docs/selfpipe.html "Use case description by Daniel J. Bernstein")
* [Signal-safe locks](http://locklessinc.com/articles/signalsafe_locks/ "lock-free algorithms")

**Comment by DanielGibson** [comment]
LOOK AT Self-pipe trick

**Comment by DanielGibson** [comment]
bad bot, doesn't even understand zork commands.
