### ISSUE TITLE
Still refuses to build correctly with Visual Studio Community 2015

### ISSUE THREAD

**Issue by leffmann** [dhewm/dhewm3#132]
Line 3371 of dhewm3/neo/framework/FileSystem.cpp;
`return _write( static_cast<idFile_Permanent*>(bgl->f)->GetFilePtr()->_file, ptr, size * nmemb );`
gives error C2039: `_file`: is not a member of `_iobuf`.

GetFilePtr() returns the internal FILE, and looking at MSVCs definition of FILE, it only contains a place-holder. No good idea how to go about fixing it, just putting it up here.

**Comment by DanielGibson** [comment]
can you try replacing `static_cast<idFile_Permanent*>(bgl->f)->GetFilePtr()->_file` with `_fileno(static_cast<idFile_Permanent*>(bgl->f)->GetFilePtr())`?

same in line 3421, btw (where _read() is used)

**Comment by leffmann** [comment]
It builds! I gave it a 10-minute play, and everything ran fine. I put some guards around your fix, as the previous code evidently built fine with *some* version of MSVC.

**Comment by DanielGibson** [comment]
doesn't need guards, according to https://msdn.microsoft.com/en-us/library/zs6wbdhx%28v=vs.71%29.aspx it has been around at least since MSVC2003 and it's cleaner than accessing internal fields of FILE anyway
