### ISSUE TITLE
ERROR: Missing 'WEAPON_NETFIRING' field in script object 'weapon_fists'

### ISSUE THREAD

**Issue by LTGZZ** [dhewm/dhewm3#133]
Hi !
Slackware64 14.1 multilib, latest dhewm3 from git.
I copied all .pk4, I can run the program and launch the timedemo, but I can't start a game.

**Comment by DanielGibson** [comment]
Are you sure you have pak005.pk4 to pak008.pk4 from the patch?
See https://github.com/dhewm/dhewm3/wiki/FAQ#which-game-data-files-are-required (if you think you've got them, please check md5sums)

**Comment by LTGZZ** [comment]
You're right, they are missing.

**Comment by DanielGibson** [comment]
you can easily extract them from the patch, see the end of the section I linked above.

**Comment by LTGZZ** [comment]
Ok.
I'm downloading the Linux patch. Here's the ftp :
ftp://ftp.idsoftware.com/idstuff/doom3/linux/

**Comment by DanielGibson** [comment]
yep, that should be the right one.

Alternatively http://files.holarse-linuxgaming.de/native/Spiele/Doom%203/doom3-linux-1.3.1.1304.x86.run might be faster.

**Comment by LTGZZ** [comment]
It's working now.
Thanks for your help.

**Comment by DanielGibson** [comment]
Great!

**Comment by y2keeth** [comment]
had the same issue when i had a extract script folder in the bade directory, deleting that fixed mine

**Comment by dumbass842** [comment]
guys it happened with mine but im on windows

**Comment by TheMidnightHammer** [comment]
Did you apply the 1.3.1 patch? You need pak005.pk4 to pak008.pk4 which can be found in the patch.
