### ISSUE TITLE
Voice playback stops when quicksave is initiated

### ISSUE THREAD

**Issue by AMDmi3** [dhewm/dhewm3#137]
When I quicksave, currently played voice fragment (such as NPC speaking, or radio transmission) is silent until it ends. E.g. npc lips are still moving/transmission UI indication is still active, but no sound is heard.

**Comment by AMDmi3** [comment]
Update: this actually affects all sounds, not just voice

**Comment by svdijk** [comment]
I've checked this againt the original Doom3 1.3.1 binary, and this doesn't occur there, sounds keep playing there when I quicksave.

Note that the issue in dhewm3 is a bit peculiar: a sound stops playing when quicksaving _only_ when the sound is being played for the first time while quicksaving. E.g. when I start a specific PDA recording, then quicksave, then recording stops playing. However if I then start the same recording again, I can quicksave all I want, the recording keeps playing correctly. The same goes for other recordings and NPCs.

Maybe some caching issue?
