### ISSUE TITLE
General audio issues.

### ISSUE THREAD

**Issue by orbea** [dhewm/dhewm3#139]
On Slackware-current using the OpenAL-1.17.1 release I have tried both the dhewm3 1.4.1-RC1 and 1.4,0 releases, the 1.4.1-RC1 is certainly an improvement, but still far from perfect.

The issues are various and inconsistent, seemingly dependent on location of the game map and other sounds going on on.  These include voices with a noticeable echo effect, reverb or recordings that will sound different (Better or worse) if your character moves around the map which ends up leading to trying to find just the right corner to listen to recordings properly...  Other problems would be excessive white noise associated with some background noises such as something hammering away.

Overall I would not consider these game breaking, just distracting.  Otherwise the engine runs great on my system using the nouveau drivers.

**Comment by DanielGibson** [comment]
This sounds very weird.
I'm surprised 1.41RC1 is an improvement as there have been no changes 
that should affect sound.

Do you use pulseaudio or alsa directly?
What kind of speaker setup do you use (headphones, stereo speakers, 5.1 
speakers, ...)? If headphones, with HRTF?

Anything you configured in openal's config?

Cheers,
Daniel

**Comment by orbea** [comment]
This is with alsa directly and stereo speakers, I tested the 1.4.0 release far less than 1.4.1RC1, but it was clear as day the reduction in the echo effect in the voices during the first cut-scene after docking at Mars City and leaving the ship.

The OpenAL configuration should be default except I changed the sample rate in alsoft-config to 48000 to quiet an error message in another program.

**Comment by DanielGibson** [comment]
I think this is mostly a feature.

The echo/reverb effects are from the EFX (formerly EAX) effect support that was added to doom3 with some patch and was Windows-only until dhewg ported it to other platforms as well.
The game has reverb settings (for echo etc) defined per room (in `efxs/<levelname>.efx`) and when you're in a room those settings are applied to all sounds that are played - even though it might make sense not to do that for audio logs, radio chatter and other things that the player is supposed to hear "locally" through the headphones in his helmet or something. I don't see an easy option to identify those sounds (other "local" sounds like your own gunshots should have those effects, after all) when they're being mixed, though, so I guess there's not much I can do :-/

However, you could just deactivate EAX/EFX effects completely in the `Settings` menu in `System -> Audio Settings -> EAX 4.0 HD On` (click to set to `Off`).
