### ISSUE TITLE
Game does not start: couldn't load game dynamic library

### ISSUE THREAD

**Issue by mickeylyle** [dhewm/dhewm3#140]
When I try to launch the game: http://paste.ubuntu.com/15279246/

**Comment by mickeylyle** [comment]
Tried again using 1.4.1rc1 from twolife's ppa: http://paste.ubuntu.com/15279266/

**Comment by mickeylyle** [comment]
Might be useful for reference, a startup/shutdown of the proprietary engine on my machine: http://paste.ubuntu.com/15279287/

Note these lines:

found DLL in pak file: /usr/local/games/doom3/base/game01.pk4/gamex86.so
copy gamex86.so to /home/raevol/.doom3/base/gamex86.so

**Comment by DanielGibson** [comment]
make sure to install both the `dhewm3` and the `dhewm3-doom3` package - the latter contains the base.so

**Comment by mickeylyle** [comment]
Thanks, that did it. Sorry for the noise!
