### ISSUE TITLE
Map BSP problems

### ISSUE THREAD

**Issue by RalfVB** [dhewm/dhewm3#147]
I've started making maps for Doom 3, using DarkRadiant. I compile them using the 'dmap' command from Doom 3.

The problem is some geometry is rendered wrongly in-game. Here's a [thread](http://idtechforums.fuzzylogicinc.com/index.php?topic=444.0) I created on the idTech4 forum, that demonstrates the problem.

The interesting thing is that these glitches aren't there when the map is compiled in stock Doom 3.

Please take a look at  this [testmap](https://github.com/dhewm/dhewm3/files/305366/building.zip).

**Comment by DanielGibson** [comment]
yeah, dmap hasn't been tested much yet, as far as I remember..
I wonder if this also happens in 32bit builds of dhewm3 (might be a 64bit issue)?

**Comment by RalfVB** [comment]
I can compile a 32-bit build later today and try with that.

**Comment by DanielGibson** [comment]
so have you tried 32bit builds yet?

**Comment by RalfVB** [comment]
Hello,

Sorry about the lateness! Been busy with things.
Unfortunately no, I haven't had the chance to try yet. I've got a laptop running 32-bit Linux which I meant to test it with, but it's at my parent's place which I haven't managed to visit yet in the meantime.

**Comment by DanielGibson** [comment]
any update on this?

**Comment by DanielGibson** [comment]
I can't reproduce the problem with latest dhewm3 (from git) on XUbuntu 18.04 x86_64 (GCC 7.5 and clang 6.0).

**Comment by DanielGibson** [comment]
Also works with XUbuntu 20.04 (GCC 9.3 and 10.2) so I guess this issue has been fixed accidentally.

**Comment by DanielGibson** [comment]
Turns out I can reproduce it after all, but only if `ONATIVE` is enabled in CMake - this would've been relevant information.

https://github.com/RobertBeckebans/RBDOOM-3-BFG/issues/436 discusses the issue, which is caused by a GCC compiler bug (at least I think it's a bug).

**Comment by DanielGibson** [comment]
GCC bugreport for this: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=100839

**Comment by BielBdeLuna** [comment]
is `-ffp-contract=off` the solution?

**Comment by DanielGibson** [comment]
I don't know, maybe.
TBH all this doesn't make sense to me and I hope that the guy who answered there was mistaken and GCC doesn't *really* believe that breaking the language standard in normal optimization modes is acceptable.

I'll wait a bit, hoping that someone else chimes in in the GCC bugreport to clear this up. For now my workaround should work for all GCC versions including their current development version.
