### ISSUE TITLE
Fedora 24 wayland dhewm3: No mouse?

### ISSUE THREAD

**Issue by rolfdeenen** [dhewm/dhewm3#152]
Hi. Recently discovered dhewm3 after the original(?) doom3 client wouldn't run on my Fedora 24 (64 bit) installation. I run Gnome under Wayland as X gives me tearing when playing videos. Most seems to work fine except I have no mouse in dhewm3. The game starts and video and audio seem fine, but in the main menu I have no mouse. When I start the console (CTRL + `) the pointer appears but I am unable to click something (because of the console?). Closing the console also removes the pointer. Any ideas or workarounds? Googeling has given me no solution. Thanks in advance.

**Comment by DanielGibson** [comment]
This is most likely an SDL bug.
What SDL version are you using? Try 2.0.4 (latest release), if that 
doesn't improve things try the latest code from hg (check out from 
https://hg.libsdl.org/SDL or just download 
https://hg.libsdl.org/SDL/archive/tip.tar.bz2
If you wanna google the bug, it /might/ have something to do with 
absolute vs relative mouse mode: 
https://wiki.libsdl.org/SDL_SetRelativeMouseMode

**Comment by DanielGibson** [comment]
So according to http://phoronix.com/scan.php?page=news_item&px=SDL2-Wayland-Relative-Mouse SDL2 now supports relative mouse mode - so it might be worth trying latest hg code now.
It seems like it also needs a recent version of Wayland ("There has been the relative pointer protocol for Wayland/Weston around for a few months now."), no idea if the one in Fedora 24 already supports relative mouse mode.

**Comment by rolfdeenen** [comment]
Hi, me again. Just wanted to let you know that I upgraded to Fedora 25 and the mouse now works (albeit very slow) in the menu. In the game itself it seems to work fine...

**Comment by shoober420** [comment]
Use SDL dev builds. You have to use mercurial which pulls the latest commits. There's a package in Arch Linux for it "sdl2-hg", but I don't know how fedora works. I would also use git version of Wayland and Weston.
