### ISSUE TITLE
Can't Disable Mouse Smoothing (m_smooth) (m_strafeSmooth)

### ISSUE THREAD

**Issue by shoober420** [dhewm/dhewm3#154]
I can't disable mouse smoothing in dhewm3. I have "m_smooth 0" in my autoexec and also tried manually setting it to 0 in console, but it still remains at 1. The same applies to "m_strafeSmooth". I'm on Arch Linux, and my full system specs are in my Steam profile, which is linked in my GitHub page.

**Comment by DanielGibson** [comment]
setting both to 1 disables smoothing.
