### ISSUE TITLE
App crashes on OSX El Capitan

### ISSUE THREAD

**Issue by emorej31** [dhewm/dhewm3#156]
During summer 2016, I was able to successfully compile dhewm3 1.4.1 on OSX El Capitan, using MacPorts to install required dependencies. I was able to play the game until Dec 26, the last time I did so.
I tried to play it again 2 days ago and the app crashed at startup. I tried to compile it again, hoping this could solve the problem, and I got this error message:

_[ 55%] Building CXX object CMakeFiles/dhewm3.dir/renderer/Image_files.cpp.o
/Users/jerome/Downloads/dhewm3-1.4.1/neo/renderer/Image_files.cpp:833:10: error: no matching function for call to 'jpeg_read_header'
  (void) jpeg_read_header(&cinfo, true );
         ^~~~~~~~~~~~~~~~
/opt/local/include/jpeglib.h:1039:13: note: candidate function not viable: no known conversion from 'bool' to 'boolean' for 2nd argument
EXTERN(int) jpeg_read_header JPP((j_decompress_ptr cinfo,
            ^
1 error generated.
make[2]: *** [CMakeFiles/dhewm3.dir/renderer/Image_files.cpp.o] Error 1_

Two remarks:

1. I periodically update MacPorts software, but I can't remember when libjpeg was last updated;

1. I installed OSX Security update 2016-003 on Jan 18.

Do you have any information on that issue?

**Comment by emorej31** [comment]
It seems that the issue comes from a libjpeg update in MacPorts (it now uses v9b).
In _neo/renderer/Image_files.cpp_, I have replaced line 833:

_(void) jpeg_read_header(&cinfo, true );_

by:

_boolean toto;
(void) jpeg_read_header(&cinfo, toto );_

It fixes the issue. Successfully compile. App launches again.

**Comment by DanielGibson** [comment]
interesting..
you probably want to use `boolean toto = true;` - passing an uninitialized variable calls for trouble ;)

**Comment by DanielGibson** [comment]
maybe I should kick out libjpeg and use stb_image.h instead..

oh and btw, thanks for reporting the issue and the fix! :)

**Comment by emorej31** [comment]
`boolean toto = true;` does not compile on OSX. 
Types are different: `toto` is `boolean` and `true` is `bool`...

**Comment by DanielGibson** [comment]
and `= 1;`?
if that doesn't help use `boolean toto = (boolean)1;`

you should really set it to true or 1, otherwise the value of toto is random and can cause random bugs or even crashes in jpeg_read_header()

**Comment by DanielGibson** [comment]
I just pushed a fix, can you test it?
(I'm using `(void) jpeg_read_header(&cinfo, (boolean)true);` now)

**Comment by emorej31** [comment]
Your fix works perfectly well on my system.
Many thanks, Daniel.

Jérôme

**Comment by DanielGibson** [comment]
cool, thanks for testing!
