### ISSUE TITLE
Flashlight Bug In Engineering and Coolant

### ISSUE THREAD

**Issue by shoober420** [dhewm/dhewm3#159]
The flashlight will not work when in "Engineering and Coolant", and "Coolant Control Junction" when J. Edwards is helping you through there with his lamp light.

https://www.youtube.com/watch?v=eRCAXqAPLhg

My system specs are in my Steam profile, which is linked in my Github page. I'm on Arch Linux 64bit.

**Comment by DanielGibson** [comment]
are you sure this isn't a feature?

**Comment by shoober420** [comment]
It does mention that the power is out in that area and that its effecting the electricity, but i doubt the flashlight is powered by electricity, and if you notice, the flashlight will blink on sometimes at random.

**Comment by shoober420** [comment]
I just watched a playthrough, and the light does indeed work in those areas. Strange thing is if you noticed, the flashlight starts working half way through. In the playthrough, the light worked in the way beginning at "Engineering and Coolant", so there must be an issue somewhere.

**Comment by DanielGibson** [comment]
I just played that scene and the flashlight worked through the whole scene.
However, sometimes there were new electromagnetic pulses that kill the flashlight - but switching it off and on again worked.

**Comment by DanielGibson** [comment]
https://youtu.be/eRCAXqAPLhg?t=43 this really looks buggy though, when I tested the flashlight went off completely (which is intended, I think), while in your video it's not really off but just doesn't light stuff anymore.
Might be a but in your video driver? I'm still on nvidia 367.57 (On Xubuntu 16.04 amd64)

**Comment by Yamagi** [comment]
I just gave it a try and was unable to reproduce it. Neither FreeBSD with nvidia-driver 375.26 nor Archlinux with mesa 17.0.1 running on a Radeon R7 370 show any rendering problems. Can you tell us the exact version of your video driver and make sure that no exotic cvar are set?

**Comment by DanielGibson** [comment]
shoober420's steam profile says he uses "NVIDIA GeForce GTX 760 2GB (378.13)" - 378.13 is a beta driver.
If the problem happens with a fresh config (i.e. without any unusual CVars set), maybe report the bug to nvidia.

**Comment by shoober420** [comment]
His occurs with a default config as well. I moved my "base directory" into my "home" directory so it would generate a brand new config. I also went ahead and changed my Nvidia driver settings to see if that was involved, and that had no effect. It still didn't render the flashlight. NVIDIA's website says that the "378.09" drivers are beta, and the "378.13" are official.

**Comment by shoober420** [comment]
I just made a thread on NVIDIA's Linux forum about this bug.

**Comment by shoober420** [comment]
Here's a link to the thread on NVIDIA's website.

https://devtalk.nvidia.com/default/topic/1000533/linux/video-of-flashlight-bug-in-doom-3-dhewm3-/

One reply says to compile with the "-DZFAIL" option. I'll have to try that out.

**Comment by DanielGibson** [comment]
no idea what that's supposed to achieve, dhewm3 has no -DZFAIL option.
If it's from a patch re-adding the patent "Carmacks Reverse": not gonna happen.

Regarding "If you suspect that this is a NVIDIA driver bug, you'll have to explain why, and provide more information.", the obvious answer is: Because the code works with all older versions of the nvidia driver, including 375.39 (but maybe you should make sure that on your machine an older driver actually works to rule out a defective GPU or whatever else could cause this).

**Comment by shoober420** [comment]
I do remember when unused the beta 378.09, that the fireball the imps would throw would render a strange blue color. Also, when I would get damaged, my screen would be blueish I stead of red. This later got fixed in 378.13.

**Comment by DanielGibson** [comment]
Could you maybe try 375.xx (ideally .26 or .39), as those versions are known to work for yamagi/me?

**Comment by shoober420** [comment]
Great news, out of desperation of having to installing older drivers, I tried one more thing. Instead of loading my save, I completely reloaded the area using "map game/alphalabs2". Upon doing this, my flashlight worked perfectly fine. I'm going to blame my changing of shadow cvars on this and say it corrupted my save file.

**Comment by DanielGibson** [comment]
hmm good to know that savegames one took while using weird cvars can have that effect

**Comment by DanielGibson** [comment]
also, you should probably tell nvidia it's not a driver bug after all

**Comment by shoober420** [comment]
I will for sure, thank you.
