### ISSUE TITLE
Audio Cracking

### ISSUE THREAD

**Issue by shoober420** [dhewm/dhewm3#164]
I'm playing through "Resurrection of Evil" right now, and thought I would mention I experienced alot of audio cracking when playing through vanilla Doom 3. I assume it's because of all the EAX emulation and reverb effects. Do you guys hear them as well? It's the only game I hear audio cracking, like it's clipping. I have version 1.17.2 of OpenAL installed.

**Comment by DanielGibson** [comment]
Do the issues go away if you disable EFX (EAX in the menu)?

**Comment by DanielGibson** [comment]
Also, where/when/with what software does it happen?
You say "RoE" and also "vanilla Doom3" - do you mean the main game and *not* RoE with "vanilla", or do you man playing RoE with the original executables from id (and not dhewm3) or what?

**Comment by shoober420** [comment]
Oops, sorry for the confusion. By vanilla, I meant no mods and just plain Doom 3 with dhewm3. I'll try disabling EAX and let you know how it sounds.

**Comment by shoober420** [comment]
Well, I've recently played Serious Sam Fusion, and my audio does crack there as well. It might have something to do with my volume settings in alsamixer. I'll post back and let you know. For the record, I don't use Pulseaudio. My volume settings are at 100 because when I listen to music with Deadbeef, it's nice and loud. But for games, just turning the knob on my speakers a little will make a pretty loud. Im almost certain that's the issue, no Pulseaudio+100 volume.

**Comment by DanielGibson** [comment]
It's usually a good idea to not go much higher than 80

**Comment by shoober420** [comment]
I'm sure this is an issue on my end, I'm closing this, sorry about that.
