### ISSUE TITLE
Add soft shadows (smoothing shadows)

### ISSUE THREAD

**Issue by 18woldemar** [dhewm/dhewm3#173]
Please, add soft shadows (smoothing shadows) support!
Also, please add the _**compiled**_ _**win64**_ _**build.**_ I think many people need it))

**Comment by DanielGibson** [comment]
> Please, add soft shadows (smoothing shadows) support!

That would be a lot of work, seems unlikely

> Also, please add the compiled win64 build. I think many people need it))

Why would they need it?

**Comment by 18woldemar** [comment]
Not everyone wants to download the compiler to do them. And not everyone can.

**Comment by DanielGibson** [comment]
Why would anyone need a Win64 build? The provided Win32 build works perfectly on 64bit Windows

**Comment by 18woldemar** [comment]
Of course)) But I think for many you need a native win64 build. Why not?

**Comment by DanielGibson** [comment]
I still don't get who would need a native win64 build and why/what for.

**Comment by 18woldemar** [comment]
Probably to support more than 4 GB of RAM.

**Comment by DanielGibson** [comment]
And when does Doom3 need that? I haven't heard any complaints about out of memory errors yet

**Comment by 18woldemar** [comment]
Okay, a lot of projects also provided 64-bit binaries, for example iortcw or ioquake3, darkplaces, etc.
