### ISSUE TITLE
can not compile on Linux Ubuntu when path has spaces

### ISSUE THREAD

**Issue by legluondunet** [dhewm/dhewm3#174]
Hello,

I can not compile dhewm3 if the path where I stored his sources contains spaces.

compilation terminal log:
https://pastebin.com/Z2is94WS

I tested to move dhewm3 sources in a path does not contain spaces, it compiled OK.

Thank you for your help.

Config:
Ubuntu 17.04 Zesty Zapus 64 bits - NVIDIA GeForce GTX 770 - official Ubuntu Nvidia drivers 375.66 - 1920x1080 - Processor Intel i5-3570 3,4 Ghz - 8 Go RAM

**Comment by RalfVB** [comment]
You never, ever have spaces in paths.

**Comment by DanielGibson** [comment]
fixed, thanks for reporting!
