### ISSUE TITLE
Mouse lag from when i last used it.

### ISSUE THREAD

**Issue by LethalManBoob** [dhewm/dhewm3#176]
This has been fixed? I recall much worse mouse input lag and yes i made sure vsync was forced off and used r_finish on both. Id say it felt like 50ms more lag

**Comment by DanielGibson** [comment]
no idea what version you last tested and when, but I don't recall any change in dhewm3 that could affect this.
could be caused by a change on your system or maybe from an updated version of libSDL2

**Comment by LethalManBoob** [comment]
Latest "releases" version.

**Comment by DanielGibson** [comment]
and what version had input lag and what operating system did you test on etc?

**Comment by LethalManBoob** [comment]
Latest version on the "releases page" and windows 10

**Comment by DanielGibson** [comment]
And what version did lag? 1.4.0 (released October 2015)? Or even before that?

But in the end I'm glad it works better for you now, whatever the reason is :-)

**Comment by LethalManBoob** [comment]
1.4.1 had the issue and ill get to retesting this sometime this week. Im
due a format.
