### ISSUE TITLE
FAQ is wrong about buying RoE in humble store for germans

### ISSUE THREAD

**Issue by mdosch** [dhewm/dhewm3#177]
> (Note that Germans still can't buy the RoE Addon there):

This is wrong, as I just purchased it there and am now downloading the files via steamcmd.
My browser is using Tor (if the IP makes any difference) as I use different browsers or browsers with different setups for different purposes and only use browsers without Tor for streams that are only available in my country.

But at checkout I used my german credit card and even my german address and I could successfully purchase it without hiding I am a german. 

Maybe you check whether this has changed and you can purchase this from Germany or add a note about using Tor.

**Comment by DanielGibson** [comment]
I guess they just check the IP, so using Tor makes a difference (if the exit-node happens to be outside Germany), as does using VPN.
I don't think they intend to sell this to Germans, they're just sloppy about the check, so Tor/VPN can be used as workaround (even with German address apparently).

However, it seems like Doom3 itself is now available for Germans via Steam (while RoE still isn't).

I wish Steam (or Humble Store) just added a proper age verification so they could sell "indizierte" games to German adults.

**Comment by DanielGibson** [comment]
Also, I'm not sure about the legality of using Tor or VPN to get around this restriction (haven't read the Steam and Humble EULAs), so it may not be a good idea to put this in the README?

**Comment by mdosch** [comment]
I didn't use it as a workaround to get this game. I just use it almost everywhere so i didn't take any actions to circumvent any lockout I didn't even know about. I just stumbled at your FAQ after downloading as I was looking for which files to copy and was irritated about the statement it doesn't work for germans.
If it might be a legal action to not sell to german IPs (not a problem as I have business trips all over the world) better leave the README as it is.

>I wish Steam (or Humble Store) just added a proper age verification so they could sell "indizierte" games to German adults.

Why should they care about the BPjM? If you make it to complicate to sell in your country we don't. 

> Also, I'm not sure about the legality of using Tor or VPN to get around this restriction (haven't read the Steam and Humble EULAs), so it may not be a good idea to put this in the README?

To be honest: Neither do I. I never use steam over Tor but I bought this game in my browser. Maybe for future use I should consider using humble store in a browser not using Tor as this might be against their terms of use. I just was sloppy and didn't even think about it as using Tor is normal for me in our times of nosy providers and three-letter-agencies.

**Comment by DanielGibson** [comment]
> Why should they care about the BPjM? If you make it to complicate to sell in your country we don't.

**They** are the ones who want to *my* money. They should care.
This actually costs Valve *and* developers distributing their games on Steam a lot of money. Lost sales is one factor, Developers crippling their games and maintaining different versions for Germany vs Rest Of The World is another.

But whatever, it's not like Valve seems very eager to fix any problems with their platform (and there are a lot worse problems) and I can't do anything about it anyway.

I adjusted the Readme to state that doom3 is also available on steam in Germany (it wasn't years ago), and added a vague mention of "German IPs" - I guess that should be safe from my side (as you said, at least when you're actually abroad it should be totally legal to buy things there that aren't available in Germany).
