### ISSUE TITLE
Error: unloading data from OpenAL hardware buffer

### ISSUE THREAD

**Issue by meetajhu** [dhewm/dhewm3#178]
TL:DR- When i click on exit level from Mars City i get this error in console. Have OpenAL installed, EAX 4.0 HD set to ON. 

Long Story: Using Windows 10. Tried on ZXR nothing worked. Swapped X-fi titanium fatality champion installed latest drivers and set to 'game mode' in console launcher and launched Doom3 was able to activate EAX 4.0. Starting Mars City level works but when i exit level in elevator it quits to menu with the said error in console. 

"Error: unloading data from OpenAL hardware buffer"

Do i need to install OpenAL soft? or am i missing anything?

**Comment by DanielGibson** [comment]
Can you test the latest release candidate and see if the issue persists?
https://github.com/dhewm/dhewm3/releases/tag/1.5.0_RC1

OpenAL soft is bundled with the official Windows binaries and should be used by default, unless you remove/rename the contained OpenAL32.dll.
After starting the game, open the console (`Shift`+`Esc`) and scroll up (mousewheel or `Page Up`) until you reach "OpenAL renderer: ..." and "OpenAL version: ..." - renderer should be "OpenAL Soft", version should be sth like "1.1 ALSOFT 1.19.1"

**Comment by meetajhu** [comment]
ok

**Comment by coreyoconnor** [comment]
I can repro this with:

*  dhewm3 at HEAD 
* OpenAL soft 1.19.1
* NixOS

I went the nuclear route and decided it should care to the level of error:

**Comment by coreyoconnor** [comment]
~~~
diff --git a/neo/sound/snd_cache.cpp b/neo/sound/snd_cache.cpp
index 647930f..4a5aac2 100644
--- a/neo/sound/snd_cache.cpp
+++ b/neo/sound/snd_cache.cpp
@@ -576,12 +576,12 @@ void idSoundSample::PurgeSoundSample() {
        alGetError();
        alDeleteBuffers( 1, &openalBuffer );
        if ( alGetError() != AL_NO_ERROR ) {
-               common->Error( "idSoundCache: error unloading data from OpenAL hardware buffer" );
-       } else {
-               openalBuffer = 0;
-               hardwareBuffer = false;
+               common->Warning( "idSoundCache: error unloading data from OpenAL hardware buffer" );
        }
 
+    openalBuffer = 0;
+    hardwareBuffer = false;
+
        if ( amplitudeData ) {
                soundCacheAllocator.Free( amplitudeData );
                amplitudeData = NULL;
~~~

**Comment by och-dx** [comment]
I am getting the same error, I have even tried upgrading OpenAL soft to the latest version. When switching levels the game crashes with Error: unloading data from OpenAL hardware buffer

**Comment by DanielGibson** [comment]
Here's a Windows-build including the fix from #235, can you test it?
[dhewm3-oalfix.zip](https://github.com/dhewm/dhewm3/files/4142053/dhewm3-oalfix.zip)

Thanks in advance! :)

**Comment by och-dx** [comment]
> Here's a Windows-build including the fix from #235, can you test it?
> [dhewm3-oalfix.zip](https://github.com/dhewm/dhewm3/files/4142053/dhewm3-oalfix.zip)
> 
> Thanks in advance! :)

Daniel, thank you, this has done the trick!

**Comment by DanielGibson** [comment]
Great, thanks for testing!

**Comment by och-dx** [comment]
Are you going to upload it to the main site as update?

**Comment by DanielGibson** [comment]
eventually yeah.. probably not right now
