### ISSUE TITLE
Gun sounds are near inaudible

### ISSUE THREAD

**Issue by DashRetro** [dhewm/dhewm3#179]
Hello!

I just installed Dhewm3 and it's my first experience with a source port.  Immediately upon loading in, I'm noticing that the gun sounds are nearly inaudible.  When I shoot a gun, I mostly can just hear the bullets hitting the wall and a very faint echo of the gunfire.

I have EAX turned off and speakers set to Stereo.  No mods are installed; just vanilla game + Dhewm3.

Thanks!

**Comment by RalfVB** [comment]
Do you use Pulseaudio or Alsa?

**Comment by DanielGibson** [comment]
What operating system are you using?
If not Windows, what version of OpenAL is installed on your system?

**Comment by DashRetro** [comment]
I'm using Windows 7 64-bit.

As for Pulseaudio vs Alsa, I'm not sure what either of those are, sorry.

**Comment by DanielGibson** [comment]
Doesn't matter, pulseaudio and alsa are Linux specific things.

What kind of speakers are you using?
Are they configured properly in the Windows system sound settings?
I'm not sure if the Stereo setting in Dhewm3 even does anything, it's probably just a leftover from the original Doom3 menu. OpenAL should get the speaker setup from Windows and use Stereo or 5.1 or whatever accordingly.

Are only the gun sounds so muted and other sounds ok?
What about music in the main menu?
What about gun sounds from enemies?
What about talking NPCs?

**Comment by DashRetro** [comment]
I use HDMI out for stereo sound.  This is great information, so I'll go double-check all my Windows settings.

As for the rest of the sounds, I'll move around a bit more and double check all that.  The main menu music works for sure.  I'll record a video for you if I don't find the problem in the Windows sound settings.

**Comment by DanielGibson** [comment]
Great!
It's entirely possible that Windows thinks that the HDMI output is 5.1 or some other surround format, but only two of the channels are actually talking to your speakers, so whether you hear something depends on the sounds source (in game) position. For example, if those two existing speakers for some reasons play the rear channels of surround, sounds that are in front of you would be very silent and ones behind you would have normal volume (and the other way round).

One more thing you could try in case changing Windows speaker settings doesn't help is updating OpenAL:
* rename dhewm3/OpenAL32.dll to OpenAL32.dll_backup (or whatever)
* download the latest OpenAL-soft binaries from http://kcat.strangesoft.net/openal-binaries/openal-soft-1.18.2-bin.zip 
* from that zip, copy /openal-soft-1.18.2-bin/bin/Win32/soft_oal.dll to dhewm3/
* rename soft_oal.dll to OpenAL32.dll
* start the game and check if it works better now

**Comment by DashRetro** [comment]
I double checked my audio device only shows two speakers, and also updated OpenAL with the one you linked, and no luck.

I am noticing the issue is *mostly* obvious with the shotgun and when shooting a wall, as if the sound of the bullets hitting the wall is overpowering and even dampening other sounds.

Here is a video showing the symptom clearly: https://youtu.be/X-FkY4AELY4

**Comment by DanielGibson** [comment]
what does it sound like if you shoot into the direction of the door, but with much more distance (so the sounds of the projectiles hitting the door should be less loud)?

**Comment by DashRetro** [comment]
It seems like the effect lasts until I'm pretty far away from the wall, but does go away at some point.

Video: https://youtu.be/gDatvWA_WC8

**Comment by DanielGibson** [comment]
Ok.

I briefly tested this on Linux with 5.1 speakers and it sounds pretty much the same.
Will have to investigate..
Might have something to do with the shotgun shooting several pellets at once and each of them generates a sound on impact (while pistol only shoots one bullet => one impact sound).. just guessing here; however, @Yamagi observed something similar in Yamagi Quake2 with the shotgun hitting the powershield of "Brain" monsters.
Funny how no one ever noticed this and now two people notice the same problem in two different games I'm involved with within a day

**Comment by Yamagi** [comment]
I've just pushed a fix to yquake2: https://github.com/yquake2/yquake2/commit/e3e5bd1bdd1cc403cf3096d60ea143c400971db3

After I understood what's going on the fix was easy: The Brain monsters have an energy shield (the "power screen"). Whenever a bullet hits the shield a nice splash sound is played. Quake IIs super shotgun spawns 20 pellets, if all of them hit the shield 20 sounds are played in the next frame. With 20 splash sounds played at once the overall volume level increases too mush, OpenAL is forced to scale all other sounds (including the background music) down to avoid clipping. That leads to a noticable and annoying drop in volume. My fix just limits the number of splash sounds played in one frame to 16. That doesn't have a audible effect but solves the problem.

My guess is that dhwem3 has a variant of that problem. The impact sounds of the shotgun pellets is too loud, everything else is scaled down. It just not as noticeable as in Quake II since dhewm3 has no background music.

**Comment by DashRetro** [comment]
That's exactly what I was thinking the issue was, I just don't really know how openAL works or really anything about this stuff.

**Comment by DanielGibson** [comment]
Ok, I think I found a simple workaround: Just set Doom3's "global" (in Options -> System) down a bit.
That way *all* sound will be a bit less loud (so you may have to turn your speakers up a bit), but as everything will reach OpenAL with a lower volume, it doesn't cut off/downscale everything as much.

This can also be done via CVar, it's called `s_volume_dB` and is 0 by default, a value of `-8` works ok for me.
Not sure yet what I'll do about this, maybe I'll give `s_volume_dB` a lower default value or just multiply everything with some factor (but first I wanna make sure this actually works for everyone :))

**Comment by DanielGibson** [comment]
any update?

**Comment by DashRetro** [comment]
Yes!  This did indeed solve the issue for me.  Sorry I didn't get back sooner... I also have an issue with my video card black-screen crashing during this game specifically whether it's the source port or not, so it's been one issue after another...  I really appreciate your work on this issue!

**Comment by RalfVB** [comment]
Just wanted to chime in this improved my experience too. Before, the sound of firing the shotgun was drowned out by the sounds of the pellet impacts, which was harsh on the ears.

Why not make this setting default?

**Comment by DanielGibson** [comment]
I pushed a fix for this to the git repository. Will be part of the next commit (not sure yet when that will happen).

Until then you can just reduced s_volume_dB as a workaround, as described above :)
