### ISSUE TITLE
Doesn't work wtih SUSE 12.2 catalyst-13.1 legacy

### ISSUE THREAD

**Issue by 88aleksandr88** [dhewm/dhewm3#181]
Hello. I have old laptop TOSHIBA Satellite A300-15D with AMD HD3650 Mobility video card. When I tried to play on Fedora with opensource driver (Radeon), game has little freezes when I moved mouse. Than I install open suse 12.2, proprietary driver, installed from rpms /compiled from source libs, compiled dhewm3 with gcc-7.2.0, installed to /usr/local/... and got this:

aleksandr@suse:~> dhewm3
dhewm 3 1.4.1.1304 linux-x86_64 Jan  3 2018 22:18:18 using SDL v2.0.7
terminal support enabled ( use +set in_tty 0 to disable )
pid: 9650
3968 MB System Memory
found interface lo - loopback
found interface wlan0 - 192.168.1.33/255.255.255.0
doom using MMX & SSE & SSE2 for SIMD processing
Flush-To-Zero mode is already enabled
Denormals-Are-Zero mode is already enabled
WARNING: base path '/usr/local/share/dhewm3' does not exist
----- Initializing File System -----
Loaded pk4 /home/aleksandr/.config/dhewm3/base/pak000.pk4 with checksum 0x1a586c38
Loaded pk4 /home/aleksandr/.config/dhewm3/base/pak001.pk4 with checksum 0x20a36d36
Loaded pk4 /home/aleksandr/.config/dhewm3/base/pak002.pk4 with checksum 0x916b20c6
Loaded pk4 /home/aleksandr/.config/dhewm3/base/pak003.pk4 with checksum 0x9b62e180
Loaded pk4 /home/aleksandr/.config/dhewm3/base/pak004.pk4 with checksum 0x2986790a
Loaded pk4 /home/aleksandr/.config/dhewm3/base/pak005.pk4 with checksum 0x8ffc3621
Loaded pk4 /home/aleksandr/.config/dhewm3/base/pak006.pk4 with checksum 0x95b65ab
Loaded pk4 /home/aleksandr/.config/dhewm3/base/pak007.pk4 with checksum 0x666bdb3c
Loaded pk4 /home/aleksandr/.config/dhewm3/base/pak008.pk4 with checksum 0x23ae5993
Loaded pk4 /home/aleksandr/.config/dhewm3/base/zpak003.pk4 with checksum 0x268f98b7
Current search path:
/home/aleksandr/.config/dhewm3/base
/home/aleksandr/.config/dhewm3/base/zpak003.pk4 (15 files)
/home/aleksandr/.config/dhewm3/base/pak008.pk4 (3 files)
/home/aleksandr/.config/dhewm3/base/pak007.pk4 (38 files)
/home/aleksandr/.config/dhewm3/base/pak006.pk4 (48 files)
/home/aleksandr/.config/dhewm3/base/pak005.pk4 (52 files)
/home/aleksandr/.config/dhewm3/base/pak004.pk4 (5149 files)
/home/aleksandr/.config/dhewm3/base/pak003.pk4 (4754 files)
/home/aleksandr/.config/dhewm3/base/pak002.pk4 (6120 files)
/home/aleksandr/.config/dhewm3/base/pak001.pk4 (8983 files)
/home/aleksandr/.config/dhewm3/base/pak000.pk4 (2700 files)
/home/aleksandr/.local/share/dhewm3/base
Addon pk4s:
----- Initializing Decls -----
5307 strings read from strings/english.lang
Couldn't open journal files
execing editor.cfg
execing default.cfg
execing dhewm.cfg
Unknown command '#'
Unknown command '#'
couldn't exec autoexec.cfg
5307 strings read from strings/english.lang
----- Initializing OpenAL -----
Setup OpenAL device and context
OpenAL: found device 'Встроенное аудио Аналоговое стерео'
OpenAL: found device 'RV635 HDMI Audio [Radeon HD 3600 Series] Цифровое стерео (HDMI)'
OpenAL vendor: OpenAL Community
OpenAL renderer: OpenAL Soft
OpenAL version: 1.1 ALSOFT 1.14
OpenAL: found EFX extension
OpenAL: found 256 hardware voices
----- Initializing OpenGL -----
Initializing OpenGL subsystem
WARNING: No usable GL mode found: Could not initialize OpenGL / GLES library
Initializing OpenGL subsystem
WARNING: No usable GL mode found: Could not initialize OpenGL / GLES library
shutting down: Unable to initialize OpenGL
idRenderSystem::Shutdown()
Shutting down OpenGL subsystem
Sys_Error: Unable to initialize OpenGL
shutdown terminal support

What do I need to make it work?

**Comment by revility** [comment]
Over the last decade most issues I've encountered with Doom3 have been ati catalyst related.  Everything from crashes, not starting, custom shaders breaking, upside down screens, to dds files making the screen black. The dds part blows my mind because ati compressonator is the most used tool for D3 dds file creation. It seems the older  the ati card, the chance of there being some kind of issue is greater.   I still receive a message/email/comment every couple months that ends up being ati related.
