### ISSUE TITLE
Widescreen FOV issue

### ISSUE THREAD

**Issue by Evilbaka** [dhewm/dhewm3#190]
Field of view for widescreen appears to be not corrected and no way to correct it besides config file.

**Comment by DanielGibson** [comment]
The FOV should be correct, independently of the resolution/aspect ratio (I think .
I think the only problem is that the HUD is stretched - the world (and monsters etc) itself looks like it should, doesn't it?
If not, make sure that `r_aspectRatio` is set to `-1` (that should be the default, but maybe you have an old .cfg or sth)
