### ISSUE TITLE
UIs sometimes unresponsible

### ISSUE THREAD

**Issue by Yamagi** [dhewm/dhewm3#192]
Sometimes UIs only register clicks after a random key on the keyboard is pressed. A good place to reproduce this in playing video disks through the PDA. Every one and then video doesn't start, even if the "play" button is clicked several times.

**Comment by Yamagi** [comment]
This is somewhat strange:

* The event is registered and - when testing with the PDA - the first frame of the requested video is played. The video stucks at the second frame.
* The bug is not reproduceable with all videos (and likely GUIs in general but I'm not sure on that).
* Not every key has the same probability to get things going. Closing the PDA with <tab> always starts the video playback.

**Comment by DanielGibson** [comment]
merged your fix so this can be closed :)
