### ISSUE TITLE
Quick saving interrupts certains sound

### ISSUE THREAD

**Issue by Yamagi** [dhewm/dhewm3#193]
If a quick save is written certain sounds interrupt. This easy to reproduce with playing an audio log throug the PDA an hitting the quick save button. Or in low oxygen areas some background sound stop.

**Comment by svdijk** [comment]
This is probably the same issue as #137.

**Comment by Yamagi** [comment]
A possible fix is here: https://github.com/Yamagi/dhewm3/tree/alfix It needs some testing if there side effects.
