### ISSUE TITLE
List of new console commands and features?

### ISSUE THREAD

**Issue by revility** [dhewm/dhewm3#195]
Is there a complete list of the new features added?  I've seen various comments that seem to show there is more than just the main ones listed in the read me file.  I was also looking to see if there is a list of any new console commands that had been added.  I'm eager to start tinkering with the souce, but would like to know what has been fully added and changed since the days of using the sdk for d3 related modding and stand alones.

**Comment by DanielGibson** [comment]
I don't think we added that many new cvars, so probably most (maybe all) can be found at https://www.iddevnet.com/doom3/cvars.php and https://modwiki.xnet.fi/CVars_(Doom_3)

**Comment by revility** [comment]
ok.  Sounds like I don't need to worry about that then.  Was there a change or addition to the materials?  I keep thinking I read something about the specular maps having more settings?

**Comment by DanielGibson** [comment]
I haven't changed anything in the renderer, and I don't think dhewg added any features there either.

RBDoom3BFG did lots of changes to the BFG renderer and for the original Doom3 there is also https://github.com/eXistence/fhDOOM which has a heavily modified renderer.

**Comment by revility** [comment]
Thanks for the quick reply.  I've looked at the various bfg sources.  It's looking like there were quite a bit of changes in rbdoom.  BFG doom also has many minor small changes in the script and def files as well... so porting the mods over would a larger scale project I'm going to stick with this for compatibility reasons and ease of porting.
