### ISSUE TITLE
Fails to load first level

### ISSUE THREAD

**Issue by acowle3** [dhewm/dhewm3#200]
I keep getting this error: 

`ERROR: Function 'map_marscity1::main' not found in script for 'call' key on worldspawn`

What is going on with this?

**Comment by acowle3** [comment]
I got it from Steam.

**Comment by DanielGibson** [comment]
ok.
are there any other files in base/ than the ones listed in the aforementioned link?

**Comment by acowle3** [comment]
Not originally.  But then I copied the other files found in maps, materials, and script. there are also two other files called "default.cfg" and "consolehistory.dat"

**Comment by acowle3** [comment]
There's also another directory called home/.config/dhewm3 with some config files, should I take a look at them?

**Comment by DanielGibson** [comment]
so there were only pak000.pk4 to pak008.pk4, not zpak000.pk4 or similar?

what operating system are you on? what version of dhewm3 are you using (and how did you install it)?

**Comment by acowle3** [comment]
Only Pak000.pk4 to pak008.pk4.

I'm using Ubuntu 18.04, and I compiled it.

**Comment by DanielGibson** [comment]
from latest git?

**Comment by acowle3** [comment]
Yes.  Latest git.

**Comment by DanielGibson** [comment]
where did you put the game data? are you running the game from the build directory?

**Comment by acowle3** [comment]
I put the game data in Home/.local/share/dhewm3/base

**Comment by DanielGibson** [comment]
ok. haven't tried that in a while, though it *should* work theoretically.
can you try putting it somewhere else and start the game with `./dhewm3 +set fs_basepath /path/to/gamedata/` ?
(where gamedata/ contains base/ which contains the .pk4 files)

**Comment by acowle3** [comment]
When I compiled, I cannot find where it's builded, so I run it from my shell.

**Comment by acowle3** [comment]
The menu boots up, just not the game itself.

**Comment by DanielGibson** [comment]
it's built in the directory you built it in?
like usually you'd do something like
```
cd dhewm3
mkdir build
cd build
cmake ..
make -j8
```
then wait until it's done compiling
and then the dhewm3 executable is right there, in the build/ directory, and you can execute
`./dhewm3 +set fs_basepath /path/to/gamedata/`

please try that.

**Comment by acowle3** [comment]
It still doesn't work.

**Comment by DanielGibson** [comment]
Weird.
Do you know what compiler (version) was used to build it?

And can you post the whole console output from starting the game up to the error message you posted? (maybe put it into a pastebin, or a .txt file that you attach here)
Thanks!

(BTW, not sure if putting the game data into $HOME/.local/share/dhewm3/base is supposed to work after all, at least that path is not mentioned in https://github.com/dhewm/dhewm3/wiki/FAQ#where-do-i-need-to-put-the-game-data-files)

**Comment by acowle3** [comment]
Attached the txt file.

Are you planning on creating a package or something that can be installed with apt-get install or something like that?  That would really simplify things for me.
[
[log.txt](https://github.com/dhewm/dhewm3/files/2321168/log.txt)
](url)

**Comment by acowle3** [comment]
Still doesn't work.

I'm just going to delete all traces of dhewm3 off of my system and then install the package you mentioned.

**Comment by DanielGibson** [comment]
ok, please let me know if that works better!
if it doesn't, please check the md5sums of all the pk4's
(this just looks like somehow files are missing or corrupted)

**Comment by acowle3** [comment]
What do I do with the md5sums of them?

**Comment by DanielGibson** [comment]
in the shell, execute `md5sum base/pak000.pk4` etc
and then compare the result with the md5 sums listed at https://dhewm3.org/#getting-the-doom3-game-data

**Comment by DanielGibson** [comment]
not sure, but at least we have an explanation for your problems then ;)

if they indeed are different you could try downloading the data again from steam (or if it's in one of the paks from the patch you could just download and extract the patch)

**Comment by acowle3** [comment]
Another question before I try again:  does your source port work with other Id Tech 4 games like Quake 4 or the Dark Mod?

**Comment by DanielGibson** [comment]
as I already wrote in the other issue: it only works with doom3.
*maybe* it could be made to work with the dark mod, as it originally was a doom3 mod, but I can imagine that they made lots of changes to doom3 for their own purposes, so probably not.
the dark mod provides linux binaries though, it's probably best to just use those.

**Comment by acowle3** [comment]
It works!

One more question before you close this:  Where do you have your copyright/license information?  I want to develop a game with your engine, and I want to know if I'm permitted to do so.

**Comment by DanielGibson** [comment]
https://github.com/dhewm/dhewm3#license
https://github.com/dhewm/dhewm3/blob/master/COPYING.txt

**Comment by DanielGibson** [comment]
so what fixed your problems? using the ubuntu package? or was a .pk4 file corrupted?

because it should of course be possible to build the game yourself on Ubuntu 18.04 (and get something that works)

**Comment by acowle3** [comment]
I simply used the package.  Packages are more idiot proof.

I need to learn more about how to properly compile stuff.

**Comment by acowle3** [comment]
Also, have you gotten multiplayer to work on it yet?

**Comment by DanielGibson** [comment]
well, compiling *should* be pretty idiot-proof as well - and as you could start the game there obviously were no errors during compiling.

can you run `g++ -v` in a terminal and give me the output, so I know which compiler version was used?

yes, multiplayer works.
not sure if it's compatible with original doom3 servers, but if both the server and the clients run dhewm3 it definitely works.

**Comment by acowle3** [comment]
My guess is that it's not.

I can browse for servers just fine on Windows, but I turn up blank on Linux.

**Comment by DanielGibson** [comment]
on windows with dhewm3 or with original doom3?

**Comment by acowle3** [comment]
Original Doom3.  I use a dual boot system, and I have the steam version of Doom 3 installed on Windows.

**Comment by DanielGibson** [comment]
It doesn't show any servers on Linux for me either - but maybe there just are none for dhewm3?
Not sure, haven't looked at the MP code in ages.

But apart from this the multiplayer code should work - it does in LAN, and it should over the internet if you explicitly connect to a server IP in the console with `/connect 1.2.3.4`

**Comment by acowle3** [comment]
If you want, I can test it out on windows so that you have data to work with for future releases.  :3

**Comment by DanielGibson** [comment]
that'd be nice :-)
if it turns out to work on Windows (with dhewm3) but not on Linux then it's definitely a bug
