### ISSUE TITLE
Quake 4, ETC

### ISSUE THREAD

**Issue by acowle3** [dhewm/dhewm3#201]
I just thought I'd ask, does this source port also support other games like Quake 4, Quake Wars, or Wolfenstein 2009?

**Comment by DanielGibson** [comment]
No, only Doom3.

**Comment by xDShot** [comment]
To think of, does Quake 4 engine differ so much compared to Doom 3? It seems the game code is only thing different. Maybe someone could try porting game code from SDK on top of the engine, though legality is questionable.
