### ISSUE TITLE
Crash with specific weapons configuration

### ISSUE THREAD

**Issue by RalfVB** [dhewm/dhewm3#202]
In player.def, I have this set in entity player_base:

"def_weapon0" "weapon_fists"
"weapon0_cycle" "0"
"weapon0_toggle" "1"

... the idea is to start the player with nothing but the fists (he has to acquire everything himself), which are only selectable through a key, not by cycling through the weapons.

The problem with this is that dhewm3 completely locks up (requiring the process to be killed) whenever I cycle through my available weapons (_impulse14 or _impulse15) before I picked up any.

**Comment by RalfVB** [comment]
Hate to bump, but this issue has been registered 9 days ago with no replies so far.

I'm guessing the problem is related to the fact that, when a weapon is selected and it's set to toggle, it switches back to the weapon that was previously selected when toggling. But when no previous weapon was selected, dhewm3 attempts to switch to an invalid weapon. I admit it's an unorthodox setup, but dhewm3 should be able to handle this, and not freeze.

**Comment by DanielGibson** [comment]
I don't know much about weapon scripts and definitions - are you sure this is a bug in dhewm3 and not your player.def?
Have you tried asking at http://idtechforums.fuzzylogicinc.com/ or some other more modding-focused place? Maybe there is a better/proper way to do this?

**Comment by RalfVB** [comment]
I appreciate the suggestion, but it's not useful in this case since you can't pick up the fists as a weapon ;)
Ultimately the idea is to implement a quick melee type attack, which works by toggling the fists, doing a Fire() in the Raise() function, then switch back to the previous weapon. Dhewm3 doesn't appear to check whether a previous weapon is available and crashes.

**Comment by revility** [comment]
you would change the toggle key to 1 with a script when you gain a weapon after the fist since you don't need the fist  to actually toggle until that point.
$player.setkey/weapon.setkey

Have you checked the denton mod source?  He updated the toggle system with half life style weapon switching..  Should be able to search it for toggle.  i don't remember what file at the moment it was in.
