### ISSUE TITLE
Are you going to port tools?

### ISSUE THREAD

**Issue by PROPHESSOR** [dhewm/dhewm3#203]
Such as script editor, pda editor, etc.

**Comment by DanielGibson** [comment]
Nope.
If someone makes them build and work on Windows again I'd gladly accept a pull request for that, but I'm (most probably) not gonna spend much time on this myself - and I'll certainly not spend any time on reimplementing the tools to make them work on other platforms (I don't have the time and I personally have no use for the tools).

**Comment by PROPHESSOR** [comment]
It's bad news...
Because developing on Linux is almost impossible ...
We need to change files manually, starting from the PDA, ending with the maps ...

**Comment by DanielGibson** [comment]
For the maps you could use DarkRadiant or NetRadiant

**Comment by PROPHESSOR** [comment]
DarkRadiant crashes with the "Segmentation fault" error.
NetRadiant as GTKRadiant for idTech3

**Comment by DanielGibson** [comment]
Then I suggest reporting the crash to the Darkradiant developers...

NetRadiant at least used to support Doom3 as well, no idea about the current state

**Comment by PROPHESSOR** [comment]
I've told developers a long time ago about the crash ... Now we are waiting for the version with fix in the Linux Mint repositories, because at compilation a lot of insoluble dependencies arise ...
In general, I'm talking about the fact that it's not very difficult to port several separate C++ files, but they will make it much easier to develop under the DHEWM3 (I'm not about radiant)

**Comment by DanielGibson** [comment]
> I'm talking about the fact that it's not very difficult to port several separate C++ files

If you think it's so easy, then do it. I'm looking forward to your pull requests.

**Comment by RalfVB** [comment]
I use DarkRadiant on Linux, and it works great.
The other tools are really just fluff. You can edit GUI's just fine using a text editor.

**Comment by PROPHESSOR** [comment]
@DanielGibson Unfortunately, I just started learning C ++, so it takes time
@RalfVB What version? What distribution? =D I tried to use DarkRadiant on Linux too, but it didn't work)

**Comment by RalfVB** [comment]
I'm on a heavily modified Kubuntu 18.04 atm
DarkRadiant is in the repositories, so it can be easily installed using apt, though it's not the most up-to-date version

You can get a Debian package from DarkRadiant's website, but I cannot install that one either without succumbing to dependency hell, though I haven't looked into it extensively yet. 2.5 works fine for me, and it's a splendid editor.

**Comment by PROPHESSOR** [comment]
```but I cannot install that one either without succumbing to dependency hell```
I too... 2.5 works but repositories contains only 2.0.2
