### ISSUE TITLE
Intel Display-Audio sucks (was: no audio with sdl >2.0.7)

### ISSUE THREAD

**Issue by j4reporting** [dhewm/dhewm3#209]
following problem with latest stable 1.4.1 and with the new 1.5.0-rc1:

audio device is Intel Display audio  
If game is configured to a lower fullscreen resolution ( 1920x1080)  than the desktop (2560 x 1440 ) then audio output is not possible.  seems to be sdl related, because audio works in this configuration with sdl version  <= 2.0.7 
Audio works if I set screen resolution same as desktop, or if game is in a window.

I tried to restart audio with s_restart but no luck so far.  Is it possible to implement a proper audio restart procedure, or delay audio initialisation for a few seconds after switching resolution?

It looks like audio device is not available for a few seconds if screen resolution changes. 
system is win10.

**Comment by DanielGibson** [comment]
First of all: Thanks a lot for testing and for taking the time to try different SDL versions! :-)

Ok, this is weird, especially considering that dhewm3 doesn't even use SDL for audio (but OpenAL)..
So apparently SDL > 2.0.7 switches the resolution in a different way than before, and that new way disables your intel display audio device for a few seconds?

I'll look at the audio initialization code and see what I can do when I have some more time (maybe this weekend) - so far that code just worked and I didn't have to modify it, so I'm not very familiar with it yet.

**Comment by j4reporting** [comment]
it seems that sdl 2.0.7 does not change the resolution at all.  Screenshots still have desktop resolution.
I don't know if it's just a frame buffer stretched to desktop size. Game reports the configured lower resolution. 

what I can see is that audio is unavailable for a few seconds if resolution changes. switching back to desktop I can see a red cross over the loudspeaker symbol in the notification area. 
Usually normal status is restored after a few seconds. 

yamagi quake2 has the same 'problem', but a snd_restart  fixes this. 
quakespasm same issue.

**Comment by DanielGibson** [comment]
I hoped that I could reproduce the problem with my Gigabyte Brix system (also running Win10) that has intel Iris Pro 5200 Graphics and is connected via DisplayPort to a display that also has internal speakers..
But it seemed to work, the audio just started playing after changing the resolution, the audio device wasn't gone or anything.
What kind of intel GPU do you have? Are you running the latest drivers? How is your display connected?

Also: My GPU driver settings tool has audio settings that let me enable "audio without video" which means that audio is supposed to continue playing even if the display is turned off for energy saving. While audio worked for me even with this disabled, maybe enabling it might help on your machine?

**Comment by j4reporting** [comment]
Does the Brix system also use Intel Display audio or some Realtek High Definition audio?
What win10 version did you test on?

my system is a NUC6i5SYH  running win10 Prof version 1709 (RS3)
Monitor is connected with DP but a test using HDMI showed same issue.

here are the relevant lines from stdout.txt 
----- Initializing OpenAL -----
Setup OpenAL device and context
OpenAL: found device 'OpenAL Soft on DELL U2518D **(Intel(R) Display Audio)**'
OpenAL vendor: OpenAL Community
OpenAL renderer: OpenAL Soft
OpenAL version: 1.1 ALSOFT 1.19.1
OpenAL: found EFX extension
OpenAL: found 256 hardware voices
----- Initializing OpenGL -----
Initializing OpenGL subsystem
Using 8 color bits, 24 depth, 8 stencil display
OpenGL vendor: Intel
OpenGL renderer: Intel(R) **Iris(R) Graphics 540**
OpenGL version: 4.5.0 - Build 25.20.100.6373

the intel audio driver is version 10.26.0.1  
Video driver is the latest version. I had video driver 24.20.100.6286 installed when I reported the issue.

I also did a test on my Win7 Laptop ( HD 530 Gfx controller)  with the same monitor connected with DP.
And here audio works. It's muted for few seconds but recovers automatically. 
So maybe it's an issue with win10 1709 release or a combination with this win10 version and the installed drivers.

----- Initializing OpenAL -----
Setup OpenAL device and context
OpenAL: found device 'OpenAL Soft on DELL U2518D (Intel(R) Display-Audio)'
OpenAL vendor: OpenAL Community
OpenAL renderer: OpenAL Soft
OpenAL version: 1.1 ALSOFT 1.19.1
OpenAL: found EFX extension
OpenAL: found 256 hardware voices
----- Initializing OpenGL -----
Initializing OpenGL subsystem
Using 8 color bits, 24 depth, 8 stencil display
OpenGL vendor: Intel
OpenGL renderer: Intel(R) HD Graphics 530
OpenGL version: 4.4.0 - Build 21.20.16.4860

**Comment by j4reporting** [comment]
I took a quick look at snd_system.cpp  (not a c++ programmer myself)
it would be interesting to get an idea what devices are available after a resolution switch

did some tests,  started in windows mode  
listSoundDecoders  gives this output: (while in title screen)
]listSoundDecoders 
  0 decoding   7% OGG: sound/musical/d3theme.wav
1 decoders
0 waiting decoders
1 active decoders
0 kB decoder memory in 0 blocks

after switch to fullscreen   
]listSoundDecoders 
  0 decoding   4% OGG: sound/musical/d3theme.wav
1 decoders
0 waiting decoders
1 active decoders
0 kB decoder memory in 0 blocks
]listSoundDecoders 
  0 decoding  25% OGG: sound/musical/d3theme.wav
  1 decoding   0% OGG: sound/musical/d3theme.wav
2 decoders
0 waiting decoders
2 active decoders
0 kB decoder memory in 0 blocks
]listSoundDecoders 
  0 decoding  31% OGG: sound/musical/d3theme.wav
  1 decoding   7% OGG: sound/musical/d3theme.wav
2 decoders
0 waiting decoders
2 active decoders
0 kB decoder memory in 0 blocks

can't reproduce this though.

most of the time I get this:  ( blocked device?)
]listSoundDecoders 
  0 decoding 100% OGG: sound/ed/gui/chirpconnect.wav
1 decoders
0 waiting decoders
1 active decoders
0 kB decoder memory in 0 blocks

are there any debug flags I can enable to get more useful output?

**Comment by j4reporting** [comment]
> Also: My GPU driver settings tool has audio settings that let me enable "audio without video"
I can't find such setting in Intel Iris Graphics Control Panel, in fact I don't see any settings regarding Audio.
Just Display, VIdeo, 3D, Power and 'Options and Support' are available

**Comment by DanielGibson** [comment]
For me that part from stdout.txt looks like:
```
----- Initializing OpenAL -----
Setup OpenAL device and context
OpenAL: found device 'OpenAL Soft on 24EB23 (Intel(R) Display-Audio)'
OpenAL: found device 'OpenAL Soft on Digitalaudio (S/PDIF) (High Definition Audio-Gerät)'
OpenAL vendor: OpenAL Community
OpenAL renderer: OpenAL Soft
OpenAL version: 1.1 ALSOFT 1.19.1
OpenAL: found EFX extension
OpenAL: found 256 hardware voices
----- Initializing OpenGL -----
Initializing OpenGL subsystem
Using 8 color bits, 24 depth, 8 stencil display
OpenGL vendor: Intel
OpenGL renderer: Intel(R) Iris(TM) Pro Graphics 5200
OpenGL version: 4.3.0 - Build 20.19.15.5058
```

I'm running Win10 1803 Build 17134.407

Your driver is probably newer than mine, because your GPU is a newer generation (this is a 5 year old Haswell CPU after all)

The aforementioned Settings are under Display -> Audio Settings (translated from German, might be called slightly different)
![intel-graphics-audio](https://user-images.githubusercontent.com/1216493/48973785-14148200-f048-11e8-9a87-995ca97e912e.jpg)

BTW, my display audio stopped working once I switched my display from DP input to DVI-D input (my big desktop PC is connected to the same display via DVI) and hasn't recovered yet.
I guess that's the reason why instead of using display audio I connected a cable from the Brix' headphone jack to my displays line-in - that at least works reliably.

**Comment by DanielGibson** [comment]
Does `reloadEngine` instead of `s_restart` work better? It seems to completely restart OpenAL (and everything else)

**Comment by DanielGibson** [comment]
Ok, it's a pity reloadEngine doesn't work.

Problem is that apparently the integration of OpenAL into Doom3 (which as AFAIK been done by Creative Labs after they extorted id Software into supporting EAX sound effects with their infamous "Carmack's Reverse" patent) isn't super clean. Many sound-related types that were originally meant to be independent of the hardware (so closing/reopening the device wouldn't affect them) now have OpenAL handles in them that become invalid when re-opening OpenAL.. so I fear I can't fix this issue easily :-/

(I might take another shot later today, but I'm not too optimistic about it right now)

BTW, about that excerpt of stdout.txt you posted earlier: Is this what you get when sound is broken?
Because I would have expected it to **not** find any device (or at least not that device) in that case..
I mean, if initializing OpenAL failed I *maybe* could keep on trying for 20sec or so until it succeeds, but if it succeeds and doesn't work anyway that's not possible..

So in case that stdout.txt was from a dhewm3 run with working sound (maybe in windowed mode), I'd like the same excerpt for the broken case :)

**Comment by j4reporting** [comment]
it looks exactly the same because sound is initialized before OpenGL. So the switch to a lower resolution happens after OpenAL already aquired the audio device. Is it possible to initialize opengl before openal?

here is a start with fullscreen 
```
----- Initializing OpenAL -----
Setup OpenAL device and context
OpenAL: found device 'OpenAL Soft on DELL U2518D (Intel(R) Display Audio)'
OpenAL vendor: OpenAL Community
OpenAL renderer: OpenAL Soft
OpenAL version: 1.1 ALSOFT 1.19.1
OpenAL: found EFX extension
OpenAL: found 256 hardware voices
----- Initializing OpenGL -----
Initializing OpenGL subsystem
Using 8 color bits, 24 depth, 8 stencil display
OpenGL vendor: Intel
OpenGL renderer: Intel(R) Iris(R) Graphics 540
OpenGL version: 4.5.0 - Build 25.20.100.6373
```


then in main menu I  opens console:
```
]listSoundDecoders 
  0 waiting OGG: sound/misc/idlogo_audio.wav
  0 decoding  18% OGG: sound/musical/d3theme.wav
2 decoders
1 waiting decoders
1 active decoders
0 kB decoder memory in 0 blocks
]s_restart 
Shutting down sound hardware
]reloadEngine 
============= ReloadEngine start =============
----- Game Map Shutdown -----
Shutting down sound hardware
idRenderSystem::Shutdown()
Shutting down OpenGL subsystem
----- Game Shutdown -----
----- Game Map Shutdown -----
Shutdown event system
----- Initializing File System -----
[deleted]
----- Initializing Decls -----
5206 strings read from strings/english.lang
Couldn't open journal files
execing editor.cfg
execing default.cfg
execing dhewm.cfg
couldn't exec autoexec.cfg
5206 strings read from strings/english.lang
----- Initializing OpenAL -----
Setup OpenAL device and context
OpenAL: found device 'OpenAL Soft on DELL U2518D (Intel(R) Display Audio)'
OpenAL vendor: (null)
OpenAL renderer: (null)
OpenAL version: (null)
OpenAL: EFX extension not found
OpenAL: found 0 hardware voices
----- Initializing OpenGL -----
----- Initializing Game -----
gamename: baseDOOM-1
gamedate: Nov 12 2018
Initializing event system
...473 event definitions
Initializing class hierarchy
...142 classes, 191092 bytes for event callbacks
Initializing scripts
Compiled 'weapon_handgrenade::Lower': 729 ms
----- Compile stats -----
Memory usage:
     Strings: 79, 9648 bytes
  Statements: 67875, zd bytes
   Functions: 2109, 250532 bytes
   Variables: 147376 bytes
    Mem used: 2576440 bytes
 Static data: zd bytes
   Allocated: 3481696 bytes
 Thread size: zd bytes
...6 aas types
----- Initializing Session -----
============= ReloadEngine end ===============
]quit
----- Game Map Shutdown -----
Shutting down sound hardware
----- Game Map Shutdown -----
********************
ERROR: idSoundCache: error unloading 

````
game crashed after exit.

**Comment by j4reporting** [comment]
one more thing,
after a `reloadEngine`  the command `listSoundDecoders` will crash the game.  
nothing in stdout.txt  and stderr.txt

**Comment by DanielGibson** [comment]
yeah, I guess reloadEngine shouldn't really be used after all.
good point about initializing sound first and opengl second; not sure I can switch those - at least vid_restart currently works (after changing the resolution)

it's all messy and complex :-/

**Comment by j4reporting** [comment]
I've  found this, [https://github.com/kcat/openal-soft/pull/237](url)

**Comment by turol** [comment]
Initializing OpenGL first and audio second is potentially a bad idea on Linux. OpenGL usually creates threads for background processing (either compiling shaders or building command buffers). OpenAL on the other hand might intialize PulseAudio which can fork the process. The combination of threads and forking can potentially deadlock though in this case it probably won't if you haven't issues any GL commands yet. Reinitializing audio in the middle of game might also bring the same problem. This is somewhat theoretical since I've never actually seen this in the wild but you still want to be careful.

**Comment by DanielGibson** [comment]
Do you have details on the "PulseAudio can fork the process" thing? Sounds incredibly error-prone

**Comment by turol** [comment]
No details, just saw it once in my Valgrind trace when debugging some program which used libpulse. Not sure under which exact conditions it does that.

**Comment by DanielGibson** [comment]
Maybe it does fork()+exec() to start the pulse demon if it isn't running?
Might be possible to do that in a "safe" way though, possibly with clone() instead of fork()?

**Comment by DanielGibson** [comment]
Ok, I tried to implement a workaround last weekend, but didn't really get it anywhere near stable, so I'm sorry, but this issue won't be fixed anytime soon :-/

Have you considered just buying a cheap USB soundcard (I think you can get reasonable ones for ten to fifteen Dollars) and plug your speakers/headphones in there to avoid this broken display audio mess?

**Comment by j4reporting** [comment]
thanks for trying. It's not that important. I wanted to have this issue documented.

It's not the only system connected to this monitor, that's the reason why audio over HDMI or DP is so handy ;) .  A workaround is to change desktop resolution before starting the game. I can also use a headphone, than audio device is realtek something. 

Issue seems to be in openal-soft, I found at least two pull requests.  And today I found [this entry](https://communities.intel.com/thread/124731) in Intel's community forum. According to this, it's pretty normal that there is an up to 8 seconds long audio loss. Applications should recover this issue.

openal-soft pull requests 
[241](https://github.com/kcat/openal-soft/pull/241)
[237](https://github.com/kcat/openal-soft/pull/237)

**Comment by DanielGibson** [comment]
I can't believe this fucking arrogance of Intel - this shit seems to break tons of games and they insist that it's the applications fault, despite very well knowing that older games will never be patched :-(
Also, I don't care what the HDMI standard tells them, I see no reason to take the audio device down. They can stop sending audio to the display for all I care, but the device itself should stay up?

I also strongly doubt that "The fact that the same game runs on different hardware is most likely because they have a higher time defined for modeset." - how would a game work better if the device is down for an even longer time? It works because other drivers don't take down the audio device...

**Comment by j4reporting** [comment]
I guess it makes sense in one case, if user switches display to another display device. Than the audio driver would need to aquire new device's capabilities first.  But setting another resolution on the same device does not change the audio device at all.

**Comment by DanielGibson** [comment]
Even if it's another display device - in >90% of cases it'll still just have simple stereo speakers so nothing except for the name should change?

**Comment by j4reporting** [comment]
It seems that Intel might finally address this issue in an upcoming driver release. 
Today I found this in the latest dirver's [release notes](https://downloadcenter.intel.com/download/29058/Intel-Graphics-Windows-10-DCH-Drivers) under 'Known Issues' 

> Some games may not have audio when using Intel Display Audio in full screen mode when the resolution is different than what is set in Windows or Intel Graphics Command Center.

**Comment by DanielGibson** [comment]
At least they finally acknowledge it - let's hope they indeed fix it in 
the future!

And let's also hope they don't only fix it for the latest GPUs but also 
for older ones that for some stupid reason use different drivers on 
Windows, even though (back to Sandy Bridge IIRC) they all use the same 
driver on Linux so they can't be all that different..

**Comment by j4reporting** [comment]
AFAIK only win10 drivers for Skylake or newer  core generations are affected. I guess this will take some more time before Intel might provide a solution. Issue  was not listed in last two driver's release notes. 
Here is the [link to Intel's support article](https://www.intel.com/content/www/us/en/support/articles/000035049/mini-pcs/intel-nuc-kits.html).

**Comment by DanielGibson** [comment]
I think I have a workaround for this - can you please test [dhewm3-oal-fixes.zip](https://github.com/dhewm/dhewm3/files/4699110/dhewm3-oal-fixes.zip) ?

**Comment by j4reporting** [comment]
I can confirm this build does  indeed restore audio almost instantly after a mode switch. 
This workaround works much better than the current, more static workaround in yquake2.

**Comment by DanielGibson** [comment]
Awesome, thanks for testing! :)

**Comment by DanielGibson** [comment]
This fix in master, but I have another OpenAL related fix that needs testing, see https://github.com/dhewm/dhewm3/pull/296

There you can also get Windows binaries for  testing that include all the OpenAL fixes of the build linked above, the aforementioned timing fix and latest changes from master.
Thanks in advance for testing! :)

**Comment by palmerj** [comment]
Hi I'm finding this issue on Ubuntu 20.04 x86_64 running on an old Intel NUC which uses a Intel HD Graphics 4000 (IVB GT2) with a Core i5-3427U CPU connected to monitor with sound via HDMI. When I run in windowed mode I get sound ok. In fullscreen I get no sound. The console the reports the following:

```
----- Initializing OpenAL -----
Setup OpenAL device and context
OpenAL: found device 'Built-in Audio Digital Stereo (HDMI)'
OpenAL vendor: OpenAL Community
OpenAL renderer: OpenAL Soft
OpenAL version: 1.1 ALSOFT 1.19.1
OpenAL: found extensions for resetting disconnected devices
OpenAL: found EFX extension
OpenAL: found 256 hardware voices

WARNING: OpenAL device disconnected! Will try to reconnect..
WARNING: OpenAL device still disconnected! Giving up!
```

I'm running latest commit from master.

Thanks for any help.

**Comment by DanielGibson** [comment]
Try building latest openal-soft (1.21.0 or from git) yourself, that might work better.
IIRC this wouldn't work with any version before 1.20

**Comment by palmerj** [comment]
Ok thanks heaps. I will give that a try

**Comment by drewwoods** [comment]
Thanks @DanielGibson I can confirm that [openal-soft 1.21.1](https://github.com/kcat/openal-soft/releases/tag/1.21.1) fixed the lack of audio in fullscreen for me
