### ISSUE TITLE
Performance issues - unstable framerate

### ISSUE THREAD

**Issue by lazycrypt** [dhewm/dhewm3#210]
I've been having issues running dhewm3. I have compiled the latest source for x64 Windows 10 with ONATIVE on and off however when running the game the framerate is all over the place (20-60FPS with slowdowns) even though my system should be able to handle it with no problem.

I've tried putting the following `autoexec.cfg` into the base folder.
```
seta r_swapInterval "1"
seta com_fixedTic "1"
```
Using this the framerate mostly sticks to the screens refresh rate (75Hz) but still drops down to 50FPS occasionally. However the major side effect is that audio goes out of sync in cutscenes.

**Comment by DanielGibson** [comment]
I just pushed a workaround for an SDL 2.0.9 bug that causes little freezes, so it would impair the framerate as well - can you see if it helps?

**Comment by lazycrypt** [comment]
Yep, seems to have helped, now the framerate tends to stick to 60FPS +/- a few frames.

**Comment by DanielGibson** [comment]
great, thanks for testing!
