### ISSUE TITLE
Several issues

### ISSUE THREAD

**Issue by RalfVB** [dhewm/dhewm3#211]
Hi there,

Nice to see a new version of dhewm3 coming up. I'm putting the release candidates through their paces with this mod project I'm working on, which should see a first release soon.

I'm running into what seem to be hardcoded restrictions residing in the engine, though. I'm currently adding weapons from other idTech4 games to my mod, but Doom 3 only allows up to 13 weapons definitions (0-12), since _impulse13 is reserved for reloading.

Is there a way to get past that limit?

**Comment by RalfVB** [comment]
Okay, I'll take a peek.

Does it increase available ammo types as well? There's a hard limit on 16 different types, there - why not have as many as we'd like?

Another legacy issue is the fact that 'shakes' won't work with .ogg files in soundshaders. Shakes use the waveform to create a screen shaking effect, but it will only work with .wav files. Perhaps this was a restriction in the .ogg library all the way back in 2004? Interestingly Quake4 appears to have added a bunch of commands that work in sound shaders, among them one to define shakes manually.
So how about lifting that restriction? I hate having to mix .wav and .ogg files together. 

Another limit I keep getting frustrated by is the lack of true 16:9 GUI support. I know implementing this will affect in-game things such as the effect you see when hit, but this effect appears to be hardcoded in the gamecode - which should be easy enough to adapt.

Speaking of GUIs, there appear to be a lot of little bugs there as well. It's fairly easy to trigger unpredictable behavior in many ways, and currently I have to code around the issue.

**Comment by revility** [comment]
I never tinkered with added that many ammo types.  Most of the stuff I’ve done uses shared.  Maybe it’s a memory thing?

Nor have I ever looked into adding shakes,  only removing.  
There’s more support for 16:9 guis in the latest dhewm3 rc.  Rivensin has multiple ones for different aspect ratios if your looking for an example.  It uses 2 kinds for the cursor & hud.  Minimum work was needed converting the actual gui to 16:9

**Comment by RalfVB** [comment]
By the way, this is why I asked the first question > http://idtechforums.fuzzylogicinc.com/index.php?topic=681.0

**Comment by RalfVB** [comment]
In regards to the ammo limit, I have no idea. It'd be great if the limit was removed. Even with some weapons sharing ammo (all the shotguns use the same shells, for example), it's still not enough for what I have in mind.

**Comment by DanielGibson** [comment]
I don't see changing this in the near future (and maybe it's possible via script after all)
