### ISSUE TITLE
Support for Quake 4 and other idTech4 game definition tags

### ISSUE THREAD

**Issue by RalfVB** [dhewm/dhewm3#212]
Hi,

I'm busy porting all Quake 4 content for use in Doom 3.

Quake 4 recognizes additional tags in material, soundshader and animation definitions. This requires the unrecognized tags to be commented and worked around for them to work in Doom 3.

It would be absolutely splendid if dhewm3 would recognize and skip these tags with a message to the console along the likes of 'tag <tagname> is not supported by Doom 3', instead of halting with an error.

Wishfully thinking, if all these tags would actually be *supported*, this would mean dhewm3 would be pretty much Quake 4 compatible - but I don't know what some of them actually do. For now, ignoring them is good enough.

There is one addition to animation definitions that I would love to see supported outright, though.

For example, here's an animation definition from Doom3:

```
anim walk models/md5/characters/enemy/sec_pistol/walk2.md5anim {
    frame 4 sound_body snd_footstep
    frame 12 sound_body snd_footstep
    frame 22 sound_body snd_footstep
    frame 34 sound_body snd_footstep
}
```
In Quake 4, it's done like this:

```
anim walk models/md5/characters/enemy/sec_pistol/walk2.md5anim {
    frame 4,12,22,34 sound_body snd_footstep
}
```
So you can define the same action for several frames in one go, comma-separated. If dhewm3 supported this, it would make porting content much easier still, not to mention reduce a lot of potential bloat for modders.

**Comment by RalfVB** [comment]
Another question: Doom 3 uses 1.0 collision models. Quake 4 uses 3.0. Dhewm3 doesn't trip over them, but prints a warning to the console. Changing the tag in the .cm file causes a bunch of errors, so I'm leaving it as it is at the moment. Maybe it's worth looking into support v3, or would it be better to convert them down to 1.0?

**Comment by RalfVB** [comment]
Daniel, are you reading this?

**Comment by DanielGibson** [comment]
I currently don't have time to add support for new features.

If those formats are properly documented somewhere, please post links for reference, in case I (or ideally someone else) get around to this in the future.

**Comment by RalfVB** [comment]
... hello? Could you please answer the question? I'm stuck, and it's ruining my momentum.

**Comment by DanielGibson** [comment]
If you have proper support for whatever those tokens are supposed to do (without breaking the original format), I might be interested in a PR.
If you just ignore/skip them, not.
