### ISSUE TITLE
Port of dhwem3 to WebAssembly [not really an issue, just for info]

### ISSUE THREAD

**Issue by gabrielcuvillier** [dhewm/dhewm3#217]
Hello,
I recently made a port of dhewm3 to WebAssembly, meaning you can run Doom 3 straight from an Internet Browser.

More info here:  https://groups.google.com/forum/#!topic/emscripten-discuss/pKcWvKppjUA
including a link to a live demonstration of D3 in the browser, using the D3 demo data files (side note: I also did a few fixes to allow dhewm3 support the demo data), as well as a link to the forked repository.

Maybe you could find this interesting!

**Comment by DanielGibson** [comment]
Cool project!

For dhewm3 the changes needed to support demo data would be particularly interesting :)

**Comment by gabrielcuvillier** [comment]
Ok, I'll make a pull request of those demo-related changes then. This is just a couple of lines to tweak

**Comment by gabrielcuvillier** [comment]
Done. I also have a small fix to let compile D3+game in one single executable (and no DLL), in case you might be interested
