### ISSUE TITLE
getting error when trying to run dentonmod

### ISSUE THREAD

**Issue by Newk77** [dhewm/dhewm3#219]
When i run the game with `./dhewm3 +set fs_game dentonmod`
it seems to load OK with a few warnings in the console
but after the menu screen and loading into the intro it halts with:
`ERROR: Missing 'WEAPON_SPECIAL' field in script object 'weapon_fists'`

what strikes me also as a bit odd is that in the beginning of the console output there is a mention:
```
Initializing scripts
Compiled '/home/newk/.local/share/dhewm3/dentonmod/script/doom_main.script': 1080 ms
```
But when i look at that location there is no script folder (also not during running the game, and no mention of it being deleted again)

What am i missing or doing wrong?
cheers!

**Comment by DanielGibson** [comment]
Did you compile dhewm3 yourself or is this the official Linux binaries?
Does the main game work? (If not, is it patched, i.e. are `pak005.pk4` to `pak008.pk4` in the base/ folder?)
Is the dentonmod game data in place? The `dentonmod/` folder (with small 'D'!) should contain a few .pk4 files, I think at least dentonmodv2final.pk4 and dentonDllKit.pk4

If those questions don't lead you to a solution, can you post (attach as .txt file to comment) all the console output you get from `./dhewm3 +set fs_game dentonmod` up to the end?

**Comment by Newk77** [comment]
Hi, thanx for the quick response!
I was hoping that my short error discription would be enough to pinpoint the issue,
but it's ofcourse no problem to be fully elaborate now:

Dhewm3 (vanilla) 1.5.0, from here, runs otherwise fine on my system! :D
I did indeed used the pre-compiled game and mod .so from the "releases" section on this github
running on updated (L)ubuntu 16.04 64bit.
I did put all the original pak files from the original 3 cds and from the 1.3.1 update in a folder where dhewm3 finds them (see attached log).
Downloaded dentonmod 2.02 from the given link on ModDB. and renamed the folder changing the capital D to a lower-case one.

It didn't seem to make any difference overwriting DentonDLL.pk4 with the one from the "extras" folder.
Also in the Readme.txt inside extras it states that DentonDllKit.pk4 are only neaded inside dentonmod folder when you don't want to use assets of Denton's mod and only its features, and bloom.pk4 is to be used with that... but i get the same error with or without these.
Should these files have all lowercase filenames? Because they do have capitals.
anyway here is a copy of my console output:
[dhewm3-dentonmod-console-log1.txt](https://github.com/dhewm/dhewm3/files/2741701/dhewm3-dentonmod-console-log1.txt)
Hope this will shed light upon the issue.
Thank you very much!

**Comment by DanielGibson** [comment]
Weird, it doesn't mention any dentonmod pk4's in the console log - where did you put them?

**Comment by Newk77** [comment]
in the directory where i start dhewm3 from: /media/newk/shed/games/ID-Tech-4/Doom3/dhewm3/dentomod/

**Comment by Newk77** [comment]
sorry for the later response back but got lost in testing, since it works now :P !
I took your advice as to put things more together in one place and moved the whole dentonmod directory into /home/username/.config/dhewm3/
And now after starting i was directly greeted with the red text at the top of the ID splash animation and menu-screen stating this is now Denton's mod :D.

Seems to run good now but i experienced some segfaults now and then.
Tried to reproduce them but they don't happen always at the same spots.
The last one i found says this at console:
```
WARNING: rigid body moved outside world bounds for entity 'idMoveableItem_moveable_item_skull_pork_112' type 'idMoveableItem' at (-2277 -1788 -492)
WARNING: Dentonmodv2final.pk4/script/ai_monster_base.script(296): Thread 'monster_zsec_pistol_3': Unknown wakeup_target 'trigger_once_31' on entity 'monster_zsec_pistol_3'
Segmentation fault (core dumped)
```
and another game run:
```
WARNING: rigid body moved outside world bounds for entity 'idMoveableItem_moveable_item_skull_pork_367' type 'idMoveableItem' at (-918 -1724 -487)
Segmentation fault (core dumped)
```
can't say for sure if these lines before are related to the segfault since there is no timestamps..
i have no experience in catching core dumps.. but if i can help out bughunting i will do so gladly!

Another thing that i was wondering about is the settings... there seems to be 2 files for dentonmod:

/home/username/.config/dhewm3/dentonmod/DoomConfig.cfg
and
/home/username/.config/dhewm3/dentonmod/dhewm.cfg

not sure which one overrides the other and if one of the two better be removed

**Comment by Newk77** [comment]
maybe we better open a new issue for that segfault thing so this one could be closed

**Comment by DanielGibson** [comment]
good idea about opening a new issue for this

I think dhewm.cfg should override the other one (maybe the other one is even ignored, not sure) - maybe better remove the other one to be sure

for the segfaults it'll probably best if you tell me where they happen and what you do there so I can try to reproduce them

**Comment by revility** [comment]
I have encountered many warnings when it comes to gibs in doom3 over the years...

There are a few gibs, such as brains that do not have collision models.  Debris models are also missing collision & spit out warning btw.

The skull gib model is greatly offset from the 0 axis.  Moveable items should be slightly above the plane, not zero or too far above to prevent clipping when spawned in. They are easy model fixes... most of them i have done for Rivensin & hardqore,  but not uploaded publicly.

Ones related to debris are in the current rivensin build.  The models can easily extracted to your base directly if needed.
