### ISSUE TITLE
Dhewm3 unexpected crash 

### ISSUE THREAD

**Issue by motorsep** [dhewm/dhewm3#22]
.../neo/sound/snd_decoder.cpp:525: int idSampleDecoderLocal::DecodeOGG(idSoundSample*, int, int, float*): Assertion `false' failed.
Aborted (core dumped)

It happened after first level was loaded and I was hitting Esc to skip intro.

**Comment by DanielGibson** [comment]
no news on this in 3 years (we had another ogg crash bug because of a (patched) libvorbis  bug though).. so I'll close this
