### ISSUE TITLE
Cmake fails looking for X11 on Apple macOS

### ISSUE THREAD

**Issue by Klezstyle** [dhewm/dhewm3#220]
Hi,

Using  cmake on Apple macOS fails because looks for installed X11 libraries.

The log is pretty straightforward:

> cmake neo
> -- The C compiler identification is AppleClang 10.0.0.10001044
> -- The CXX compiler identification is AppleClang 10.0.0.10001044
> -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
> -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
> -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Found ZLIB: /usr/lib/libz.dylib (found version "1.2.11") 
> -- Found JPEG: /usr/local/lib/libjpeg.dylib (found version "90") 
> -- Found OGG: optimized;/usr/local/lib/libogg.dylib;debug;/usr/local/lib/libogg.dylib  
> -- Found VORBIS: optimized;/usr/local/lib/libvorbis.dylib;debug;/usr/local/lib/libvorbis.dylib  
> -- Found VORBISFILE: optimized;/usr/local/lib/libvorbisfile.dylib;debug;/usr/local/lib/libvorbisfile.dylib  
> -- Found OpenAL: /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenAL.framework  
> CMake Error at /usr/local/Cellar/cmake/3.13.2/share/cmake/Modules/FindX11.cmake:429 (message):
>   Could not find X11
> Call Stack (most recent call first):
>   CMakeLists.txt:125 (find_package)
> 
> 
> -- Configuring incomplete, errors occurred!

The culprit check is the one in "neo/CMakeLists.txt" lines 124 - 127
> if(NOT AROS)
>         find_package(X11 REQUIRED)
>         include_directories(${X11_INCLUDE_DIR})
> endif()

If i comment out the check, cmake can create makefiles correctly.
I propose as solution removing the check for X11 in macOS operative systems, which should be something obvious by the way, because there is no X11 on modern macs.

**Comment by DanielGibson** [comment]
I just removed that X11 stuff from cmake, thanks for reporting this!
