### ISSUE TITLE
Input lag?

### ISSUE THREAD

**Issue by LethalManBoob** [dhewm/dhewm3#225]
Hello i once posted 2 years ago, an issue complaining of input lag. This rings true. My system is all new compared to when i first used it. The input lag is still there and feels just off compared to the vanilla doom. Im not sure how to fix it, r_finish 1 makes it bearable but not as good as vanilla. swapinterval makes no difference. Im not sure what is the matter here.

**Comment by LethalManBoob** [comment]
Ive done some testing. it is lesser than it used to be. But i really feel like somthing is off. Maybe this is just some major placebo, but input lag is somthing i am sensitive to. From an arena shooter standpoint.

**Comment by DanielGibson** [comment]
I have never observed any input lag in dhewm3 and still have no idea if there's anything wrong with your system, but for reference the prior (closed) issue for this was #176.

Are you still on Win10?
Do you still have a mouse input lag of 50ms (how did/do you measure that)?
Is it just for mouse movement or also for clicks?
Did you test dhewm3 1.5.0 (latest release from December 2018)?

**Comment by LethalManBoob** [comment]
So i did some testing with the most recent build. identical settings to vanilla, I test by loading up the intro level and doing a lot of fast strafing and flicker movements like when in an arena shooter 1 on 1 situation. The difference is small enough that i can accept being wrong but it feels like those flicker movements are just a big more sluggish than vanilla just, like as if they had a bit of custard thrown in, it may be due to not raw lag but a number of things getting in the way of mouse input, i know that achieving 1 to 1 mouse input is not just a matter of raw lag but where input is sampled and how, it just feels less snappy here by a fraction of a fraction of a second. Again, i could be wrong, but i certainly had that issue when i first reported it a long time ago. It was very noticeable.

**Comment by lachs0r** [comment]
Is dhewm3 running in exclusive fullscreen mode on your system? Windows’ compositor introduces input lag otherwise.

**Comment by LethalManBoob** [comment]
I was indeed using fullscreen optimisations for a while. However when disabled, im not 100% sure, but the input lag difference seems to now be imperceptible. I will let you know if i notice anything on further testing.

**Comment by DanielGibson** [comment]
I guess this can be considered fixed then?

**Comment by LethalManBoob** [comment]
Yup ha.
