### ISSUE TITLE
dbus error on dhewm3 startup under Linux4Tegra

### ISSUE THREAD

**Issue by danboid** [dhewm/dhewm3#231]
I have installed dhewm3 from the Linux4Tegra Ubuntu 18.04.2 repos on a NVIDIA Jetson Nano dev board but it fails to start:

```
dbus[7580]: arguments to dbus_message_new_method_call() were incorrect, assertion "path != NULL" failed in file ../../../dbus/dbus-message.c line 1362.
This is normally a bug in some application using the D-Bus library.

  D-Bus not built with -rdynamic so unable to print a backtrace
Aborted (core dumped)
```

**Comment by DanielGibson** [comment]
dhewm3 certainly doesn't talk to dbus itself, this most probably is from SDL2 (or possibly indirectly some other lib called by SDL2).

You could try building SDL2 yourself, maybe that works better

**Comment by danboid** [comment]
I've installed the SDL2 version (2.09) from Ubuntu 19.04 by building the 19.04 sdl2 source package and I no longer have any DBUS errors when starting SDL2 apps.

**Comment by DanielGibson** [comment]
Great, I glad it works now!

BTW, I'm curious how well dhewm3 runs on the Jetson Nano :)

**Comment by danboid** [comment]
It's about a week overdue and its still pretty shoddy (out of sync sound) but today I uploaded a video showing rbdoom3bfg running on the Jetson Nano:

https://youtu.be/wtz5OHx7TGA

I don't suppose dhewm3 is going to run much faster is it?

**Comment by DanielGibson** [comment]
Thanks for reporting! :)

Don't know, depends on what the bottleneck is etc.
If it's CPU bound, then it won't be feaster, as D3BFG is able to use more cores.
If the GPU is slowing it down, /maybe/ dhewm3 would run faster as lacks some fancy effects that were added in RBD3BFG. (OTOH BFG generally has a more modern renderer that might run better on modern GPUs, but nvidia has very good support for all versions of OpenGL so unsure how much that helps).

In the end, I think it would be worth a try at least :)

**Comment by aansrajpoot** [comment]
Hello guy's,
I'm also facing same issue. Can someone help by telling or refer me it's proper solution line by line. 
Here it is:

**pygame 2.0.0 (SDL 2.0.8, python 3.6.9)
Hello from the pygame community. https://www.pygame.org/contribute.html
dbus[25440]: arguments to dbus_message_new_method_call() were incorrect, assertion "path != NULL" failed in file ../../../dbus/dbus-message.c line 1362.
This is normally a bug in some application using the D-Bus library.

  D-Bus not built with -rdynamic so unable to print a backtrace
Aborted (core dumped)**

Thank you so much.
