### ISSUE TITLE
CMake version check should be updated

### ISSUE THREAD

**Issue by blargelJim** [dhewm/dhewm3#232]
I think the CMake version in the cmake_minimum_required is to low.
I tried running it on CMake 3.5 which comes with the ubuntu 16.04 LTS but the cmake file includes a source_group with a TREE parameter which I belive is firstly supported in CMake 3.8.2 (says so on their documentation site https://cmake.org/cmake/help/v3.8/command/source_group.html). So when running cmake it spits out a error message at line 937 (source_group(TREE ${CMAKE_CURRENT_SOURCE_DIR} PREFIX neo FILES ${src_idlib}))

No biggie but sure was a bit confusing until I realized the missmatch in CMake version. Updated my CMake to the latest version and now it seems to build fine.

/Jimmie

**Comment by DanielGibson** [comment]
Thanks for reporting, I just pushed a fix :)
