### ISSUE TITLE
16:9 GUIs

### ISSUE THREAD

**Issue by RalfVB** [dhewm/dhewm3#233]
Hi,

I'm trying to build a nice native 16:9 1920x1080 GUI for my upcoming project, but I'm running into all sorts of apparent restrictions and undefined behavior.

The in-game resolution works without problems, just not the GUIs.

Simple example (mainmenu.gui)

windowDef Desktop{
    rect 0,0,1920,1080
    forceaspectwidth 1920
    forceaspectheight 1080
    menugui 1
}

The 'menugui' tag forces the display to 4:3, for starters. If it's not there, dhewm3 will crash when the player hits the ESC key (and the mainmenu pops up) while playing.

Omitting the forceaspect tags means it'll display the image at 640x480, regardless of window size.

Creating a subwindow with the same aspects appears to work, but then the mouse cursor is trapped in the left hand upper corner, making the UI unusable.

Is it even possible to do this?

**Comment by DanielGibson** [comment]
GUIs must be 640x480.
No, I'm not gonna change that, it's too hard, this 640x480 and 4:3 assumption is hardcoded in too many places.

https://github.com/dhewm/dhewm3-sdk#scale-guis-to-43 has some information on how to have fullscreen GUIs scaled/stretched (vs cropped to 4:3 with black/empty bars on left/right), but if they are scaled they'll still look distorted (=> 4:3 GUI stretched to 16:9 or whatever).

You could create 4:3 GUIs that are distorted "the other way" so they look correct when stretched to 16:9 - the **Rivensin** mod does that.

**Comment by revility** [comment]
I believe the only images I squashed were main menu bg & loading screen bg’s.  Basically anything full screen. Rest were window defs which is easy to do. It was around 20% less for the width.  This allowed me to use same image files for both menu versions.  Feel free to poke around the gui files.

**Comment by RalfVB** [comment]
Ugh, no, no hacks. 

Here's why I bring it up again -

**Comment by DanielGibson** [comment]
> Ugh, no, no hacks.

You're not get anything but hacks though :-P
It is what it is.. the SteelStorm team tried to change the gui system to support different resolutions and failed, I'm not gonna waste time on that.
As I said, that 640x480 and 4:3 assumption is all over the place.

You can probably use higher res images and scale them down in the .gui so when they're scaled up again to match their real resolution they don't look blurry (compared to "real" 640x480 images that are scaled up and each image pixel makes up several screen pixels then)

**Comment by RalfVB** [comment]
No images were used though, all you see here are windowDefs (and a renderdef for the gun).
I want to get the layout right before I make it look nice. I could scale back the buttons and text, but then it would look worse still.

**Comment by DanielGibson** [comment]
¯\_(ツ)_/¯

if you're working with a 15y old game/engine you gotta live with the limitations

**Comment by RalfVB** [comment]
I don't agree with that.

Look at GZDoom.

**Comment by DanielGibson** [comment]
I don't care about GZDoom.

If you can implement this (without breaking existing GUIs) I'm happy about a pull request, but I won't spend any time on this myself.

**Comment by RalfVB** [comment]
I understand that. You don't owe anybody your time.
I also understand that it's not straightforward to fix.

Oh well :)

**Comment by RalfVB** [comment]
Of course, you understand, if I ever get round to this myself, I'll do it in my fork, not in dhewm3?

**Comment by DanielGibson** [comment]
Your point being?

**Comment by RalfVB** [comment]
Well, you seem to have little interest in moving dhewm3 forward.

Again, I appreciate dhewm3 a lot, and I'm grateful for your work. Modding Doom 3 has become a near-full time hobby of me now.

**Comment by DanielGibson** [comment]
So if you end up implementing this yourself you don't want to share it because dhewm3 can only have features that I implement myself?

**Comment by Nable80** [comment]
> if I ever get round to this myself, I'll do it in my fork, not in dhewm3?

This is the usual way of doing things, isn't it? Almost nobody develops experimental things in a main project repo. People develop anything in a separate fork and then (if the process was successful) just send pull-requests to the main repo. Then it can be merged, it can always be decided after the code is written for real. No need for drama (at least before the work is done).
