### ISSUE TITLE
dhewm3 on rpi4

### ISSUE THREAD

**Issue by Askmewho** [dhewm/dhewm3#251]
This great port runs just "great" on rpi4, but it should run much better if we could use opengl 3.0 ES instead of opengl 2.1 desktop api. could you suggest any other port of this game than runs on opengl 3.0 ES or if this one could do that??

thanks as always

https://www.youtube.com/watch?v=o723tOcRq0o&t=638s

**Comment by Askmewho** [comment]
oh, no, ive tried it with sdl2 w/gl and it starts with opengl 3.0 ES but it lacks of some features... maybe on 3.1 ES or 3.2 ES??

**Comment by DanielGibson** [comment]
I guess a problem is that Doom3 uses the ancient OpenGL ARB shaders, while OpenGL ES only supports the newer GLSL shaders.

You could try D3wasm which is based on dhewm3 and I think it supports OpenGL ES: https://github.com/gabrielcuvillier/d3wasm
Its main focus is compiling to webassembly with emscripten, but I think it also supports a native build with a normal copiler for running natively on Linux (at least it used to).

**Comment by Askmewho** [comment]
Yeah, it does work with opengl 3.0 ES, but its doesnt run as better I expected, lot of heavy stutterings, but maybe its related to the unpolished states of the mesa driver. runs better with your approach right now.  thanks!

**Comment by DanielGibson** [comment]
Could be the driver, or maybe the CPU/GPU gets too hot and reduces the clockspeed? I heard the RPi4 gets a lot hotter than the RPi3.
Maybe you could check that somehow - at least the CPU clockspeed should be easy to obtain with `grep MHz /proc/cpuinfo`, no idea if the RPi4 has hardware sensors that tell you the temperature (and if they are currently supported by Linux).
If this is the case, there are cooling solutions for the RPi, like passive heatsinks you can glue on the CPU and other components, and also cases that contain small fans (probably a combination is best).

**Comment by Askmewho** [comment]
Thanks @DanielGibson , but i have it extremely cool. No, for some reasons opengl 3.0 goes very bad on that fork. I will try it again when newer profile of mesa gets available. Rpi4 is gles 3.2 capable on the hard.
