### ISSUE TITLE
Lenguaje Error

### ISSUE THREAD

**Issue by sodomon2** [dhewm/dhewm3#255]
i have an error running the game with the spanish translation here the error

Addon pk4s:
----- Initializing Decls -----
Assertion failed: kv.key.Cmpn( STRTABLE_ID, STRTABLE_ID_LENGTH ) == 0 (/home/diego/Descargas/FPS/games/dhewm3-1.5.1_PRE1/neo/idlib/LangDict.cpp: Load: 103)
Looks like dhewm3 1.5.1pre crashed with signal SIGABRT (6) - sorry!
(No Backtrace on this platform)
Aborted

**Comment by DanielGibson** [comment]
can you show which pk4 files are loaded? should be further up the console output.
I assume that you don't have all needed zpak* files, there were some that came with the 1.3 or 1.3.1 patch, see also https://github.com/dhewm/dhewm3/issues/227#issuecomment-468935259

**Comment by sodomon2** [comment]
dhewm3 1.5.1pre.1304 linux-x86_64 Sep 27 2019 22:57:33 using SDL v2.0.9
WARNING: terminal type 'xterm-256color' is unknown. terminal support may not work correctly
terminal support enabled ( use +set in_tty 0 to disable )
pid: 32710
1760 MB System Memory
found interface lo - loopback
found interface wlan0 - 172.16.16.20/255.255.255.0
found interface docker0 - 172.17.0.1/255.255.0.0
doom using MMX & SSE & SSE2 for SIMD processing
enabling Flush-To-Zero mode
enabling Denormals-Are-Zero mode
WARNING: base path '/usr/share/dhewm3' does not exist
----- Initializing File System -----
Loaded pk4 /home/diego/.local/share/dhewm3/base/pak000.pk4 with checksum 0x28d208f1
Loaded pk4 /home/diego/.local/share/dhewm3/base/pak001.pk4 with checksum 0x40244be0
Loaded pk4 /home/diego/.local/share/dhewm3/base/pak002.pk4 with checksum 0xc51ecdcd
Loaded pk4 /home/diego/.local/share/dhewm3/base/pak003.pk4 with checksum 0xcd79d028
Loaded pk4 /home/diego/.local/share/dhewm3/base/pak004.pk4 with checksum 0x765e4f8b
Loaded pk4 /home/diego/.local/share/dhewm3/base/pak005.pk4 with checksum 0x8ffc3621
Loaded pk4 /home/diego/.local/share/dhewm3/base/pak006.pk4 with checksum 0x95b65ab
Loaded pk4 /home/diego/.local/share/dhewm3/base/pak007.pk4 with checksum 0x666bdb3c
Loaded pk4 /home/diego/.local/share/dhewm3/base/pak008.pk4 with checksum 0x23ae5993
Loaded pk4 /home/diego/.local/share/dhewm3/base/zpak000.pk4 with checksum 0xfaa41155
Current search path:
/home/diego/.config/dhewm3/base
/home/diego/.local/share/dhewm3/base
/home/diego/.local/share/dhewm3/base/zpak000.pk4 (830 files)
/home/diego/.local/share/dhewm3/base/pak008.pk4 (3 files)
/home/diego/.local/share/dhewm3/base/pak007.pk4 (38 files)
/home/diego/.local/share/dhewm3/base/pak006.pk4 (48 files)
/home/diego/.local/share/dhewm3/base/pak005.pk4 (63 files)
/home/diego/.local/share/dhewm3/base/pak004.pk4 (5137 files)
/home/diego/.local/share/dhewm3/base/pak003.pk4 (4676 files)
/home/diego/.local/share/dhewm3/base/pak002.pk4 (6120 files)
/home/diego/.local/share/dhewm3/base/pak001.pk4 (8972 files)
/home/diego/.local/share/dhewm3/base/pak000.pk4 (2698 files)
Addon pk4s:
----- Initializing Decls -----
5206 strings read from strings/english.lang
Couldn't open journal files
execing editor.cfg
execing default.cfg
execing dhewm.cfg
couldn't exec autoexec.cfg

These are the pak you carry.

**Comment by DanielGibson** [comment]
Yeah, zpak003.pk4 is missing.

I extracted it from the windows patch and attached it here: [zpak003.pk4.zip](https://github.com/dhewm/dhewm3/files/3699545/zpak003.pk4.zip)
As Github doesn't allow .pk4 attachments, I added a .zip at the end, you need to rename the file again to zpak003.pk4 (without .zip) for it to work.

**Comment by sodomon2** [comment]
ok gracias
