### ISSUE TITLE
Delta Labs Level 2A, Records Office

### ISSUE THREAD

**Issue by ghost** [dhewm/dhewm3#256]
Not sure if this has been addressed already but in my fist play through dhewm3_1.5.0, in Delta Labs Level 2A, Records Office I can not enter the glassed room to collect the Plasma cells. I've moved the box around and broken all the glass but can't enter from any direction. It seems fenced off.

**Comment by DanielGibson** [comment]
You can break the windows and duck-jump from the box through a broken upper window.
(Turn towards the broken glass, press the forward key, jump and right after pressing the jump key press the duck/crouch
![alpha1](https://user-images.githubusercontent.com/1216493/82958549-e6e6be00-9fb5-11ea-8bb9-11168c40467f.jpg)
![alpha2](https://user-images.githubusercontent.com/1216493/82958553-e77f5480-9fb5-11ea-91e8-f8cba9d8a7af.jpg)

 key)
