### ISSUE TITLE
Sound reverb has too much echo

### ISSUE THREAD

**Issue by joeg1484** [dhewm/dhewm3#266]
I just started using this and it works great, but the sound reverb or what ever has way too much echo and its quite annoying.

Is there a way to turn this off?

Im running Kubuntu 19.10, Nvidai, Asus GU501 ROG Laptop.
Let me know if you need any more info.

Thanks!
Joe

**Comment by DanielGibson** [comment]
You can disable EAX in the options (Options -> System -> set "EAX 4.0 HD" to off)

**Comment by joeg1484** [comment]
> You can disable EAX in the options (Options -> System -> set "EAX 4.0 HD" to off)

Thanks, that worked great!

Joe
