### ISSUE TITLE
Rear/Front Audio Inverted

### ISSUE THREAD

**Issue by mgpat-gm** [dhewm/dhewm3#273]
I have the front and rear audio flipped when I run the dhewm 3 version 1.5.0 for amd64 (x86_64) Linux. Left/right is good. I tried turning on QjackCtl and could not get any audio from dhewm3.

Specs:
Ubuntu 18.04 (updated)
Nvidia GTX 1080
AMD Ryzen 3900x
Presonus Studio 26

**Comment by DanielGibson** [comment]
This is most probably an OpenAL problem, maybe it's not configured correctly?

**Comment by mgpat-gm** [comment]
It is a system wide problem. Thanks.
