### ISSUE TITLE
Controller support

### ISSUE THREAD

**Issue by aidorin** [dhewm/dhewm3#274]
Hi @DanielGibson

Is there any way to use a controller? I checked the dhewm.cfg created at MyGames/dhewm but I didn't see anything about joystick cvars or commands.

And I saw this, so It seems that maybe its possible:
https://github.com/dhewm/dhewm3-libs/blob/master/i686-w64-mingw32/include/SDL2/SDL_gamecontroller.h

**Comment by DanielGibson** [comment]
Hi,
Joystick/Gamepad/Controller input is currently not supported.
It's on my longterm TODO list, but I have no idea when I get around to implementing it.

**Comment by RalfVB** [comment]
In the meantime you could use an app that maps joystick inputs to keyboard to tide you over.
Should work well though I haven't got a clue what to recommend on the Windows platform.

**Comment by aidorin** [comment]
@DanielGibson 
Oh, I see. Well, patience then. Thanks for the replay!

@RalfVB yeah, I know there are those app, but they don't work as well as native controller support. I prefer to wait. Thanks anyway.
