### ISSUE TITLE
Apsyr Doom 3 for Mac CD-Key is reported as not working

### ISSUE THREAD

**Issue by henryyeh** [dhewm/dhewm3#275]
I purchased Doom 3 for Mac published by Aspyr.  My CD-Key is not working in dhewm.  It looks like it's a different format.

**Comment by parkerlreed** [comment]
Are you on the latest dhewm3? I'm fairly certain it hasn't asked for a key for quite a while now.

**Comment by henryyeh** [comment]
Hmm, probably not.  I’ll try to compile the latest and try again.  Thanks!

**Comment by parkerlreed** [comment]
Did this work out?

**Comment by henryyeh** [comment]
I’m getting a build error fatal error: 'AL/alext.h' file not found.

Let me debug this and get back to you.

Thanks.

**Comment by DanielGibson** [comment]
see the last paragraph of https://github.com/dhewm/dhewm3/#compiling

**Comment by henryyeh** [comment]
Thanks.  I got it to build and it indeed does not ask me for a CD-Key anymore, but a different problem.  The screen is not centered.  Everything is shifted up a bit.

**Comment by parkerlreed** [comment]
What was the screen issue?

**Comment by henryyeh** [comment]
I closed this issue as it was related specifically to the CD-Key and created a new one #276 to describe the screen issue in more detail.

Thanks.
