### ISSUE TITLE
Display anomolies on Mac

### ISSUE THREAD

**Issue by henryyeh** [dhewm/dhewm3#276]
I tried building off both master and 1.5.0 release.

On Mac OS Catalina 10.15.3.

Dhewm displays the game only in the bottom 1/4 of the open window, in windowed mode.

In Full Screen mode, the entire display is shifted 1/4 up, so the top 1/4 of the game is not visible.

**Comment by DanielGibson** [comment]
This might be caused by HighDPI/Retina mode.
Can you try starting the game from terminal like `SDL_VIDEO_HIGHDPI_DISABLED=1 ./dhewm3` ?

**Comment by henryyeh** [comment]
@DanielGibson Thanks.  That seems to work in Full Screen mode at some resolutions (like 1080p), but not others.  Windowed mode is still displaying in a corner, and out of the resolutions I tried in full screen higher than 1080p, the display is still shifted up.  Also, is there any way I can put environment variable into a dhewm3 configuration file somewhere?  Thanks.

**Comment by DanielGibson** [comment]
Not in a config, but you could write a startscript and call that instead of dhewm3 itself.
you could call it dhewm3.sh and it could look like:
```sh
#!/bin/sh
export SDL_VIDEO_HIGHDPI_DISABLED=1
/path/to/dhewm3
```
(I think you need the full path to the dhewm3 executable, at least if you're gonna call dhewm3.sh from a starter or shortcut or whatever where the current working dir might not be the one the dhewm3 executable is in)

**Comment by henryyeh** [comment]
@DanielGibson Yeah I made a shell script to launch it with the variable, but I was trying to get it to work by launching the .app file.  I modified the Info.plist with:

	<key>LSEnvironment</key>
	<dict>
		<key>SDL_VIDEO_HIGHDPI_DISABLED</key>
		<string>1</string>
	</dict>

But this doesn't seem to work.

**Comment by DanielGibson** [comment]
no idea about that, sorry, I don't have a Mac and have no experience with .app files

**Comment by DanielGibson** [comment]
> Very surprised this port works as well as it does on Big Endian Apple Silicon though

Apple Silicon isn't Big Endian.

The fullscreen bug you reported sounds strange, but as I don't have a Mac I can't reproduce or fix it

**Comment by mkrupczak3** [comment]
@MacSourcePorts Awesome! This version launches Doom3 Resurrection of Evil (`d3xp`) first try with no issues

Still encountering the display settings and fullscreen issue as described in previous comment. 


It's possible I've mucked up something with my windowing system though. I'm not an experienced Mac user so I wouldn't know how to troubleshoot this further
<img width="274" alt="Screen Shot 2022-04-25 at 3 20 53 PM" src="https://user-images.githubusercontent.com/25494111/165159333-a2ed3edb-7bbf-414d-9f5f-ad284345ff30.png">

**Comment by DanielGibson** [comment]
are you sure X is involved? it really shouldn't.

**Comment by MacSourcePorts** [comment]
> are you sure X is involved? it really shouldn't.

This is correct, dhewm3 does not require X11 or anything like that. There are apps that do, like the GiMP, and some games do, but not dhewm3. 

This is not to say it's impossible X11 is interfering if it's running (and it's an icon in the dock when it is running) but it's unlikely.

**Comment by mkrupczak3** [comment]
I just tried again, and somehow the issue fixed itself. Weird. 

Can no longer reproduce the behavior

More details [here](https://github.com/MacSourcePorts/dhewm3/issues/2#issuecomment-1109171648)

**Comment by mkrupczak3** [comment]
Thanks for taking a look anyways

**Comment by DanielGibson** [comment]
thanks for letting me know! :)
