### ISSUE TITLE
dentonmod.so does not exist

### ISSUE THREAD

**Issue by revevil** [dhewm/dhewm3#277]
Hello,

I am really enjoying Dhewm3 in Linux Mint 19.3 Mate 64-bit. I wanted to say thanks to creators of Dhewm3 and Denton's Enhanced Doom and Classic Doom. Have tried to get various mods to work. Classic Doom works, but I cannot get Denton's Enhanced Doom to work. I get this weird line in the console output:

WARNING: couldn't load mod-specific dentonmod.so, defaulting to base game's library!

Now I don't see how to load a file that doesn't exist. I downloaded the zip file from moddb, and there is no such file. I copied the Dentonmod folder to my .config/dhewm3 and renamed it to be lowercase. Then I created a shell script to launch dhewm3 with the mod and I get that weird line right after the loading screen crashes. So I am attaching a text file for my entire console output. I just wanted to ask if anyone could help me please. I know I am overlooking something and already feeling stupid for it. But I have a lot of stupid moments, so try to bear with me. If there is anything else you need to know, please ask. And thanks to anyone who can help me with this. BTW, I have seen the screenshots for Denton's Mod and it looks amazing!

[console.txt](https://github.com/dhewm/dhewm3/files/4247856/console.txt)

**Comment by DanielGibson** [comment]
Did you download dhewm3-mods_1.5.0_Linux_amd64.tar.gz from https://github.com/dhewm/dhewm3/releases/tag/1.5.0 ? It contains the .so files for the supported mods, including dentonmod.so

**Comment by DanielGibson** [comment]
oh yeah, also make sure to use dhewm3_1.5.0_Linux_amd64.tar.gz from the same download page instead of the dhewm3 that comes from your distributions apt repository, I think Linux Mint 19.3 is based on Ubuntu 18.04 which still ships dhewm3 1.4.1, but mod support has only been added in 1.5.0

Also, I'm glad you're enjoying dhewm3 and the mods :)

**Comment by revevil** [comment]
> Did you download dhewm3-mods_1.5.0_Linux_amd64.tar.gz from https://github.com/dhewm/dhewm3/releases/tag/1.5.0 ? It contains the .so files for the supported mods, including dentonmod.so

I told ya I was overlooking something! =) You just solved my problem totally! Thank you very much! It's amazing what that mod does to the weapons and the particle effects. Even the flashlight looks better and brighter.

Also, thank you for getting back to me so fast. This all makes me want to learn how to mod. I have only made mods for one other game, and they were ok, but nothing this awesome.
