### ISSUE TITLE
Author's opinion on enabling alwaysrun in SP?

### ISSUE THREAD

**Issue by dobosken** [dhewm/dhewm3#278]
Howdy.

What is the author's stance on allowing alwaysRun to be enabled in singleplayer?
It is not vanilla behaviour, however personally I don't foresee it negatively affect any Doom 3 player no matter their stance on the subject.

Those that want it, get it. Those that don't want it, won't have to change a thing as it's not the default behaviour.

My current implementation just rips out the multiplayer check for that specific feature. It is still controlled by the cvar and the toggle in the multiplayer menu.
I assume the main thing that would have to be addressed here, is the fact that the toggle from the multiplayer menu would now affect the game in singleplayer.

Adding another cvar just to control the same feature in sp seems superfluous to me. What would be a good approach, assuming this feature is accepted by the author?

**Comment by DanielGibson** [comment]
hmm I would indeed use a separate cvar for singleplayer, otherwise I wouldn't mind the feature

**Comment by DanielGibson** [comment]
In https://github.com/dhewm/dhewm3/pull/576 I'm adding a new CVar `in_allowAlwaysRunInSP`
When that's set, in_alwaysRun and in_toggleRun also work in SP.

Haven't done anything about the stamina (yet?) though
