### ISSUE TITLE
SIGSEGV when certain files are missing

### ISSUE THREAD

**Issue by Urfoex** [dhewm/dhewm3#28]
Having a default.cfg and a materails/default.mtr
when those two files:
→    script/doom_main.script
→    script/doom_defs.script

are missing dhewm3 will crash with:

Program received signal SIGSEGV, Segmentation fault.
0x00007fffe3102221 in Remove (node=0x3ccd820, this=0x7fffe37801f0)
    at /home/kakarott/projects/iodoom3/dhewm3/neo/idlib/containers/BTree.h:231
231                     if ( parent->key > parent->lastChild->key ) {

(gdb) print parent->lastChild
$3 = (idBTreeNode<idDynamicBlock<char>, int> *) 0x0

**Comment by DanielGibson** [comment]
with https://github.com/DanielGibson/d3-base-assets (and the included patch) things shouldn't crash, so use that.. or maybe https://github.com/OpenTechEngine/OpenTechBFG if you wanna use the superior doom3 bfg engine.
