### ISSUE TITLE
dhewm3 does not start - "_default material not found"

### ISSUE THREAD

**Issue by mcc1984** [dhewm/dhewm3#281]
Hello,
I installed this dhewm3 edition:
https://www.moddb.com/mods/ruiner/downloads/rivensin-0976-for-dhewm3-150-windows-64 

When I start dhewm3.exe the console shows me this error:

"----- Initializing Decls -----
shutting down: _default material not found
idRenderSystem::Shutdown()
Shutting down OpenGL subsystem
_default material not found"

I don't know what this means.

I also can't start Rivensin.
It will show me this error:
"execing default.cfg
Initializing scripts
----- Game Map Shutdown -----
********************
ERROR: file E:\Dhewm3\rivensin\script\doom_main.script, line 1: file 'script/doom_defs.script' not found
********************
Error during initialization
Shutting down OpenGL subsystem"

I find it kinda strange that noone else is reporting these errors in the moddb-comments bc if files r missing it should not work, right?

Can someone plz tell me why it does not work & help me fix the problem?
Thanks

**Comment by DanielGibson** [comment]
It means that the game data (from original Doom3) is missing, see https://dhewm3.org/#how-to-install for details

**Comment by mcc1984** [comment]
> It means that the game data (from original Doom3) is missing, see https://dhewm3.org/#how-to-install for details

Thanks.
I somehow did not copy the pak000.pk4.
This was the problem.

Thread can be closed.

**Comment by DanielGibson** [comment]
Great, glad it works now :)
