### ISSUE TITLE
[cdoom] Music volume tied to master volume & slider has no effect

### ISSUE THREAD

**Issue by sinisterseed** [dhewm/dhewm3#288]
Hello there,

I've recently found out about Dhewm3 and I've been testing it out a little with mods. So far I've tried only Classic Doom 3 and it seems to play quite nicely, very smooth - although I had to change com_fixedtic to 1, 0 doesn't play very well for me and -1 is even worse, apparently.

That being said, I opened this issue because I noticed that the music volume is actually tied to the master volume, so if I change that, the music volume also changes. More than that, the music slider does not seem to work at all, it does nothing in cdoom. I've not investigated the base game or the expansions yet, however. This is on W10 version 1909.

I should also mention that I've experienced the game (or rather OpenAL, according to the console) failing to clear sound buffers occasionally as well, which results in the map failing to load, but after starting a new game once I deleted the dhewm3 folder in Documents/My Games it seems to be fine now. I'll be sure to report back if the issue resurfaces.

**Comment by DanielGibson** [comment]
It should work, except in the menu apparently, and except when loading a savegame (instead of starting a map "freshly").
I just fixed the savegame bug, no idea about the menu bug I don't think that's very important.

Thanks for reporting!

**Comment by DanielGibson** [comment]
the third (and hopefully last) release candidate for 1.5.1 is out, including an updated cdoom.dll which should fix this bug - please test! :)
https://github.com/dhewm/dhewm3/releases/tag/1.5.1_RC3
