### ISSUE TITLE
error unloading data from OpenAL hardware buffer

### ISSUE THREAD

**Issue by BenzoSt** [dhewm/dhewm3#289]
I am working on a mod that uses Denton's .dll.  I frequently have crashes when completing a level.  Crashes have occured consistently upon completion of Delta3 and Cpuboss.

![problem3](https://user-images.githubusercontent.com/54503797/82722952-f5249980-9c98-11ea-97b6-996b47ad67d8.png)

**Comment by DanielGibson** [comment]
Sounds like https://github.com/dhewm/dhewm3/issues/178
Can you try if the build linked in https://github.com/dhewm/dhewm3/issues/178#issuecomment-580978690 fixes the issue for you?
Or alternatively, build dhewm3 yourself from latest git master (which includes that fix) and try that?

**Comment by DanielGibson** [comment]
Or try the build linked in https://github.com/dhewm/dhewm3/pull/296, it's more recent and has some additional OpenAL fixes
