### ISSUE TITLE
Error Generating OpenAL Hardware buffer when all audio devices are disabled

### ISSUE THREAD

**Issue by TommyHanusa** [dhewm/dhewm3#292]
On Windows 10 64-bit disabling all audio devices will prevent maps from loading and an error will be generated.
[stdout.txt](https://github.com/dhewm/dhewm3/files/4686247/stdout.txt)

Repro steps:
1. Disable all audio devices in settings>Manage Sound Settings.
2. Launch Dhewm3 1.5.1pre and progress to the main menu.
3. Start a new game with any difficulty.

Notes: using the console command "map mapname" will also generate an error.

**Comment by DanielGibson** [comment]
What's audio device maps?
What operating system is that on? openal-soft or something else?
Also, having the actual error message and when exactly it happens (after starting the dhewm3 executable? when loading a map? ...) would be very helpful :)

**Comment by TommyHanusa** [comment]
> What's audio device maps?
> What operating system is that on? openal-soft or something else?
> Also, having the actual error message and when exactly it happens (after starting the dhewm3 executable? when loading a map? ...) would be very helpful :)

Sorry, I fat fingered a submit on the bug.

**Comment by TommyHanusa** [comment]
Lemme know if you can't get a repro.

**Comment by DanielGibson** [comment]
> Sorry, I fat fingered a submit on the bug.

no worries :)

I think I have an idea for a workaround (ok, two actually), but I gotta go to bed before I get around to implementing it (and building fresh Windows binaries for you to test).
I'll also try to reproduce it on Win10 (where do I disable audio devices? I rarely use Windows..), good to know there seems to be a generic way to do it - I don't have a bluetooth headset..

**Comment by TommyHanusa** [comment]
> I think I have an idea for a workaround 
The work around is literally 'enable an audio device'.

I only found this issue because I was using a Bluetooth headset that would go into sleep mode and disconnect from my computer. Reconnecting a device solves the issue.

**Comment by DanielGibson** [comment]
No, I mean a workaround in the code ;)
On the one hand Doom3 without sound really sucks, but on the other hand it at least shouldn't crash and might be useful for testing..
It's just that right now the sound initialization code assumes that initializing openal eventually succeeds (if not with a user configured device then with a default device); I should check for this and disable sound if the default device also fails.
However, I'm not 100% sure disabling sound even is enough, if the game still tries to do things to openal that it doesn't like then I can make it use openal-softs "null" driver which just doesn't output any sound, but otherwise pretends to work.

**Comment by DanielGibson** [comment]
I think I fixed this issue, and also #209 and #291.
I created a build with all those fixes (and otherwise based on latest master), can you test it?
[dhewm3-oal-fixes.zip](https://github.com/dhewm/dhewm3/files/4699110/dhewm3-oal-fixes.zip)
Thanks in advance! :)

**Comment by DanielGibson** [comment]
These fixes are in master, but I have another OpenAL related fix that needs testing, see https://github.com/dhewm/dhewm3/pull/296

There you can also get Windows binaries for  testing that include all the OpenAL fixes of the build linked above, the aforementioned timing fix and latest changes from master.

**Comment by TommyHanusa** [comment]
Okay, I'll try to give this a look tonight.

**Comment by TommyHanusa** [comment]
This is confirmed fixed.

**Comment by DanielGibson** [comment]
Great, thanks for testing!
