### ISSUE TITLE
Beeping sound played in case of missing sounds

### ISSUE THREAD

**Issue by IvanTheB** [dhewm/dhewm3#294]
I hear a "beeping" sound in case the sound referenced by the sound shader is missing.
Steps to reproduce (note that 'light_hum_101' is a vanilla D3's shader referencing a non existing file):
1) Run the game
2) testSound light_hum_101

Expected behavior: console warning and no sound emitted.
Actual behavior: console warning and beeping sound emitted.

Of course this can be avoided by changing the game content (after all, using such shader is 'wrong'), but it can be a daunting task while porting an existing mod to dhewm3.

**Comment by DanielGibson** [comment]
This is no bug - the beep is supposed to play if a sound isn't found.
It can be disabled by setting the `s_playDefaultSound` CVar to 0 (it's 1 by default even in Vanilla Doom3).

Isn't this good to have as a reminder that there's still sounds missing and that you should look in the console for details?

**Comment by IvanTheB** [comment]
Thanks for the quick response!
Sorry, I didn't know about this feature. It's indeed useful for mod developers! On the other hand, it makes a lot harder porting an existing mod to dhewm3. 
I'd prefer to just ignore these warnings instead of hunting missing sounds in 50 already-tested maps (which I'd prefer not to change at all) and tons of custom scripts.
I see s_playDefaultSound is an archived CVar. I guess I can simply override the default in the default.cfg of my mod and be done with this problem.
