### ISSUE TITLE
Glitches with overlay

### ISSUE THREAD

**Issue by vlad54rus** [dhewm/dhewm3#298]
I'm using RTSS 7.2.3 overlay for statistics display and for some reason it gets corrupted during cutscenes. Is there anything you can do about it?
https://youtu.be/b89BfzU1DCc

**Comment by vlad54rus** [comment]
Switching OpenGL context validation setting in RTSS config files seems to fix it, but i still wonder why this happens.

**Comment by DanielGibson** [comment]
Most probably a bug in RTSS
