### ISSUE TITLE
Map files do not seem to open properly in DOOMEdit if a period is in the file path.

### ISSUE THREAD

**Issue by TommyHanusa** [dhewm/dhewm3#301]
On Windows 10 64-bit when opening a map with DOOMEdit an incorrect file will be opened.

Repro steps:
1. Launch Dhewm3 1.5.1rc1 DOOMEdit with a shortcut using a shortcut targeted to "YOURPATH\dhewm.3\dhewm3.exe" +set r_fullscreen 0 +set r_multiSamples 0 +editor
2. Select File>Open to open a map. The map will not be loaded or displayed.

Note:
Sometimes it will display a different map or an incorrect map (maybe the last map it correctly had open?) I'm not really sure about the behavior on this.

This was checked against game/mars_city1.map and a custom map made in DarkRadient (provided as it quicker to dmap and load.)
[GuiTestmap.map.txt](https://github.com/dhewm/dhewm3/files/4943481/GuiTestmap.map.txt)

**Comment by DanielGibson** [comment]
I couldn't reproduce this problem (and neither #299) with my setup.
Can you test if the problems go away if you use a path without spaces?
If that doesn't help can you test a shorter path (like C:\doom3\)?
(Please use the latest built from https://github.com/dhewm/dhewm3/issues/300#issuecomment-660782532 for testing)

(I didn't get around to test this with different paths myself, it's already very late, #300 took longer than I thought)

**Comment by TommyHanusa** [comment]
> (I didn't get around to test this with different paths myself, it's already very late, #300 took longer than I thought)

I'm reproducing the issue by having a period '.' in my path such as C:\dhewm.3
(this is kinda a larger issue since you are distributing zips with periods in their name, so if someone were to just unzip and go... they would hit this issue)

**Comment by DanielGibson** [comment]
Oh, good point, I somehow missed the period in the path (but did see "Doom3 Engine" with a space and vaguely remembered that *some* game-related tool or sth had problems with spaces in paths).

I'll investigate, thanks! :)

**Comment by TommyHanusa** [comment]
> Oh, good point, I somehow missed the period in the path (but did see "Doom3 Engine" with a space and vaguely remembered that _some_ game-related tool or sth had problems with spaces in paths).

Do keep in mind that File>Save Selected seems to work fine (regardless of periods and such). I'm not sure why the different saving types are, umm different.

**Comment by DanielGibson** [comment]
Can you check if this fixes your problems? [dhewm3_1.5.1_RC1-editorfixes2_win32.zip](https://github.com/dhewm/dhewm3/files/4951127/dhewm3_1.5.1_RC1-editorfixes2_win32.zip)

Thanks :)

**Comment by TommyHanusa** [comment]
This issue no longer reproduces in dhewm3_1.5.1_RC1-editorfixes2_win32.zip

**Comment by DanielGibson** [comment]
Great, thanks for the confirmation!
If you find any more editor bugs please let me know :)
