### ISSUE TITLE
Compilation fails: VS2019, x64-Debug, VS Cmake Tools

### ISSUE THREAD

**Issue by spiralsam** [dhewm/dhewm3#304]
Using the internal CMake tools of VS2019 16.6.5 and vcpkg to install dependencies, I've gotten this when attempting compilation:

```
  "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/bin/cmcldeps.exe" RC C:\dhewm3\neo\sys\win32\rc\dhewm3.rc CMakeFiles\dhewm3.dir\sys\win32\rc\dhewm3.rc.res.d CMakeFiles\dhewm3.dir\sys\win32\rc\dhewm3.rc.res "Note: including file: " "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.26.28801/bin/HostX64/x64/cl.exe" C:\PROGRA~2\WI3CF2~1\10\bin\100183~1.0\x64\rc.exe -DWINVER=0x0501 -D_ALLOW_KEYWORD_MACROS -D_WIN32_WINNT=0x0501 -D__DOOM_DLL__ -IC:\vcpkg\installed\x64-windows\include -IC:\vcpkg\installed\x64-windows\include\AL -IC:\vcpkg\installed\x64-windows\include\SDL2 -I"C:\dhewm3\neo\out\build\x64-Debug (default)" -IC:\dhewm3\neo -DWIN32 -D_DEBUG   /MP /fo CMakeFiles\dhewm3.dir\sys\win32\rc\dhewm3.rc.res C:\dhewm3\neo\sys\win32\rc\dhewm3.rc
C:\dhewm3\neo\out\build\x64-Debug (default)\EXEC : fatal error RC1106: invalid option: /MP
```
I've removed the option from CMakeLists.txt to get a working compilation:
```
#add_definitions(/MP) # parallel build (use all cores, or as many as configured in VS)
```
Perhaps this can be fixed (to not add this /MP for this RC step for this VS Build workflow) to make it more friendly compiling with VS2019's CMake implementation(?).

**Comment by DanielGibson** [comment]
I'd prefer not to remove that option - compiling takes **a lot** longer without that option (only one CPU core is used then instead of all available ones).

Can you try changing `add_definitions(/MP)` to `add_compile_options(/MP)`?
Hopefully then CMake only uses that flag for compiling C/C++ source, not .res files (no idea if that's actually the case and if parallel building still works then, but it's worth a try).

**Comment by spiralsam** [comment]
Yep it'll build successfully now with add_compile_options(/MP) instead.

**Comment by DanielGibson** [comment]
Good to know, thanks for testing this and for reporting the issue!
I'll change this when I have some time, maybe this weekend.

**Comment by DanielGibson** [comment]
The fix is in master, thanks again!
