### ISSUE TITLE
Bug with autosaves

### ISSUE THREAD

**Issue by rakantoh** [dhewm/dhewm3#305]
I already played until alpha labs sector 4, in each stage the game creates an autosave in the beginning of the stage, but the alpha labs have a problem, in sector 1, it creates the autosave of alpha labs sector 1, when i pass the alpha labs sector 1 and i go to the alpha labs sector 2, the game creates the autosave of the alpha labs sector 2, but the autosave of sector 1 dissapears, the autosave of sector 2 rewrite the autosave of sector 1, and the autosave of sector 3 do the same with the autosave of sector 2, and the autosave of sector 4 do the same with the autosave of sector 3.
This is a bug of dhewn3.

**Comment by DanielGibson** [comment]
So this behaves differently with original Doom3 1.3.1?
Or is it maybe normal that the game only keeps the last/latest autosave?

**Comment by rakantoh** [comment]
I use windows 10 pro x64 v2004, doom 3 v1.3.1 steam version, i renamed doom3.exe to doom3.bak.exe and renamed dhewm3.exe to doom3.exe, and language in spanish. Do you need my hardware specs?

**Comment by DanielGibson** [comment]
Thanks!
I hope the hardware doesn't play a role; I'll try to reproduce this when I have some time, hopefully this weekend.

**Comment by rakantoh** [comment]
ok. thanks, the project is awesome!

**Comment by DanielGibson** [comment]
I just remembered one more thing: Can you tell me the whole path of the savegame directory and also its contents?
Should be something like `C:\Users\rakantoh\Documents\My Games\dhewm3\base\savegames\`

**Comment by rakantoh** [comment]
yes, that is the path.

**Comment by rakantoh** [comment]
yes, the username is "rakantoh", i attached the screenshot of the savegames folder.
![dhewm saves](https://user-images.githubusercontent.com/59809634/88872981-29f52580-d1e1-11ea-81ee-5f792d9cb073.png)

**Comment by DanielGibson** [comment]
Thanks!

Damn, it looks like it uses the localized level names (so in your case spanish ones) for the autosaves.. that probably causes the problem.
I have 
```
.../dhewm3/base/savegames/AutoSave__Alpha_Labs_Sector_1.save
.../dhewm3/base/savegames/AutoSave__Alpha_Labs_Sector_1.txt
.../dhewm3/base/savegames/AutoSave__Alpha_Labs_Sector_2.save
.../dhewm3/base/savegames/AutoSave__Alpha_Labs_Sector_2.txt
.../dhewm3/base/savegames/AutoSave__Enpro_Plant.save
.../dhewm3/base/savegames/AutoSave__Enpro_Plant.txt
.../dhewm3/base/savegames/AutoSave__Mars_City.save
.../dhewm3/base/savegames/AutoSave__MARS_CITY_SOUS_SOL.save
.../dhewm3/base/savegames/AutoSave__MARS_CITY_SOUS_SOL.txt
.../dhewm3/base/savegames/AutoSave__Mars_City.txt
.../dhewm3/base/savegames/AutoSave__Mars_City_Underground.save
.../dhewm3/base/savegames/AutoSave__Mars_City_Underground.txt
.../dhewm3/base/savegames/AutoSave__Subterr_neo_Mars_City.save
.../dhewm3/base/savegames/AutoSave__Subterr_neo_Mars_City.txt
.../dhewm3/base/savegames/AutoSave__UAC_Administration.save
.../dhewm3/base/savegames/AutoSave__UAC_Administration.txt
```

I'll try to fix this when I have some time, probably not straightforward..
Until then, as a workaround, you could either save manually (not rely on autosaves) or remove `zpak00*.pk4` from the gamedata so the game is back to English.

**Comment by rakantoh** [comment]
yeah, i use manual saves, however i want to say you the bug for you knowledge and further fixes.

**Comment by DanielGibson** [comment]
I think I have a fix for that problem, can you test it?
[dhewm3-autosavefix.zip](https://github.com/dhewm/dhewm3/files/5011524/dhewm3-autosavefix.zip)
Thanks! :)

**Comment by rakantoh** [comment]
ok, i will test now.

**Comment by rakantoh** [comment]
Ok, i played the alpha labs again and the fix works! now the game created the alpha labs autosaves correctly, without replacing each them. Thanks! great job!

**Comment by DanielGibson** [comment]
Awesome, thanks a lot for testing!

**Comment by rakantoh** [comment]
Oh man you are awesome, it's true that you fixed bugs of  the original game! The problem of autosaves is present in the original doom 3 without any mod, i apologize for give you additional work for this. Great job!
Apart, i comment here because i dont want to open other issue, in the delta labs 2b (the first time when the player use the teleporter), when the player walks accross of ductes, the player falls in a room where a scientific is doing an autopsy to a imp, the scientific begins to talk with the player and to the end the scientific gives to the player the code for two lockers in the same room, in english, the scientific say the code normally, but in spanish, and in others languages, the code (or the sound of the scientific saying the code) is missing, isn't hear. Can you fix this issue/bug?
Again, i apologize for give you additional work, but this enhance this very useful mod.
Many thanks.
![deltalabs2](https://user-images.githubusercontent.com/59809634/89136601-240d8600-d4fa-11ea-90a4-adf95e7ee5eb.png)
