### ISSUE TITLE
Cmake error: Can't find jpeg library, altough it is included.

### ISSUE THREAD

**Issue by Rodolfo377** [dhewm/dhewm3#308]
> CMake Error at C:/Program Files/CMake/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find JPEG (missing: JPEG_LIBRARY) (found version "90")
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.15/Modules/FindJPEG.cmake:100 (find_package_handle_standard_args)
  CMakeLists.txt:121 (find_package)

![image](https://user-images.githubusercontent.com/13386622/91080875-b21ded80-e61c-11ea-8b12-dea9a3af7740.png)
![cmake-gui_No87OBCS7s](https://user-images.githubusercontent.com/13386622/91080889-bba75580-e61c-11ea-9d3c-535734d87bc0.png)

**Comment by DanielGibson** [comment]
are you using the dhewm3-libs as described in https://github.com/dhewm/dhewm3/#using-the-provided-windows-binaries ?

**Comment by Rodolfo377** [comment]
Yes, in fact I have downloaded the libs in a separate folder and ran the same command from terminal: 
![explorer_HNLxohpLqV](https://user-images.githubusercontent.com/13386622/91097909-e8686680-e636-11ea-89a2-e6e43155c02c.png)
![cmd_sCjbDSh61d](https://user-images.githubusercontent.com/13386622/91097925-ef8f7480-e636-11ea-8d8a-73da1ec5a756.png)

**Comment by Rodolfo377** [comment]
The jpeglib.h is obviously there in the folder structure, and the terminal says it found version 90, but I dont understand why it says not found, breaking the configuration.

**Comment by Rodolfo377** [comment]
Any updates on this? Im really eager to contribute to the project but this issue is holding me back :/

**Comment by DanielGibson** [comment]
I'll have a look this weekend.
I must admit I haven't tried building with MinGW on windows in ages - I use Visual Studio Community Edition there (though mostly I'm on Linux).

**Comment by DanielGibson** [comment]
What version/distribution of MinGW are you using?

**Comment by Rodolfo377** [comment]
gcc version 4.8.3

**Comment by DanielGibson** [comment]
that's horribly outdated.

also, what mingw distro is  that (where did you download what)?

**Comment by DanielGibson** [comment]
I was able to build dhewm3 with the nuwen MinGW distro from https://nuwen.net/mingw.html

However, I'd heavily recommend using Visual Studio on Windows, as debugging with it is way more reliable than gdb on Windows.

**Comment by Rodolfo377** [comment]
oof, grabbed mingw from here http://win-builds.org/doku.php had no idea it was so outdated. Will try with that one you shared then!

**Comment by DanielGibson** [comment]
so did it work eventually?

**Comment by hemebond** [comment]
@Rodolfo377 ping
