### ISSUE TITLE
how to install this?

### ISSUE THREAD

**Issue by DOOMMARINE117** [dhewm/dhewm3#315]
what are the steps?

i hve the cd version of doom 3 an roe version hae already updated it to 1.3.1

then the patch fix.

what is next?

**Comment by DanielGibson** [comment]
https://dhewm3.org/#how-to-install

**Comment by DOOMMARINE117** [comment]
> 
> 
> https://dhewm3.org/#how-to-install
> 
> (if any of the steps there are unclear please describe what's unclear, so I can improve the instructions)

i still don't udnerstand what to do. im assuming i can't laod the game through the website?

**Comment by DanielGibson** [comment]
Well the first part(s) is getting the (patched) gamedata , which you already did if I understand you correctly.
Then the last part is getting the dhewm3 executables and adding them so they can use the game data: https://dhewm3.org/#getting-dhewm3-executables
So you download `dhewm3_1.5.1_RC2_win32.zip` from https://github.com/dhewm/dhewm3/releases, open that zip and unpack it into the directory with the game data, so it looks kinda like
```
your_doom3_directory/
    base/
        pak000.pk4
        pak001.pk4
        ... (and the other .pk4 files of base/)
    d3xp/
        pak000.pk4
        pak001.pk4
    dhewm3.exe
    dhewm3ded.exe
    base.dll
    d3xp.dll
    libcurl-4.dll
    ... (and all the other .dlls from the dhewm3 .zip file and maybe some .txt files)
```
Afterwards you can just start dhewm3.exe

**Comment by DOOMMARINE117** [comment]
> 
> 
> Well the first part(s) is getting the (patched) gamedata , which you already did if I understand you correctly.
> Then the last part is getting the dhewm3 executables and adding them so they can use the game data: https://dhewm3.org/#getting-dhewm3-executables
> So you download `dhewm3_1.5.1_RC2_win32.zip` from https://github.com/dhewm/dhewm3/releases, open that zip and unpack it into the directory with the game data, so it looks kinda like
> 
> ```
> your_doom3_directory/
>     base/
>         pak000.pk4
>         pak001.pk4
>         ... (and the other .pk4 files of base/)
>     d3xp/
>         pak000.pk4
>         pak001.pk4
>     dhewm3.exe
>     dhewm3ded.exe
>     base.dll
>     d3xp.dll
>     libcurl-4.dll
>     ... (and all the other .dlls from the dhewm3 .zip file and maybe some .txt files)
> ```
> 
> Afterwards you can just start dhewm3.exe

i see. so its just an exe

so this is different from: https://wasm.continuation-labs.com/d3demo/

so it seems i done everything correctly. 

the main main menu will be in fullscreen mode?

or i can change that?

**Comment by DanielGibson** [comment]
Yes, D3wasm is based on dhewm3, but dhewm3 is just a "normal" native source port, not running in a browser.

You can switch fullscreen on/off and change the resolution in the Options -> System menu.

**Comment by DOOMMARINE117** [comment]
> 
> 
> Yes, D3wasm is based on dhewm3, but dhewm3 itself is just a "normal" native source port, not running in a browser.
> 
> You can switch fullscreen on/off and change the resolution in the Options -> System menu.

i see. so i missunderstoodd between the two. 

so completely different. understood. 

this source ports supports all mods?

**Comment by DanielGibson** [comment]
No, this source port only supports mods that **either** don't need their own game DLL **or** have been ported to dhewm3, see https://dhewm3.org/mods.html

**Comment by DOOMMARINE117** [comment]
> 
> 
> No, this source port only supports mods that **either** don't need their own game DLL **or** have been ported to dhewm3, see https://dhewm3.org/mods.html

will the lost mission mod, the dark mod, Blade yaujtia, thenverdead 2 mod an phantasm armagaddeon mod work  on here?

**Comment by DanielGibson** [comment]
TheDarkMod is its own thing providing its own executable, so it's completely independent of any other source port.

The Lost Mission Mod has been ported but isn't mentioned on the page yet. In the next dhewm3 release (which should happen in the next weeks) there will be a dhewm3 mod DLL for it.
Googling `"Blade yaujtia" doom3` gets zero results so apparently that mod doesn't even exist, same for `thenverdead 2`.
"Phantasm Armageddon" seems to be a Unreal Engine 4 project.
There used to be a "Phantasm" (without "Argmageddon") mod for Doom3 apparently, and it seems like it had its own DLL which is not ported to dhewm3 so it won't work

**Comment by DOOMMARINE117** [comment]
> 
> 
> TheDarkMod is its own thing providing its own executable, so it's completely independent of any other source port.
> 
> The Lost Mission Mod has been ported but isn't mentioned on the page yet. In the next dhewm3 release (which should happen in the next weeks) there will be a dhewm3 mod DLL for it.
> Googling `"Blade yaujtia" doom3` gets zero results so apparently that mod doesn't even exist, same for `thenverdead 2`.
> "Phantasm Armageddon" seems to be a Unreal Engine 4 project.
> There used to be a "Phantasm" (without "Argmageddon") mod for Doom3 apparently, and it seems like it had its own DLL which is not ported to dhewm3 so it won't work

https://www.moddb.com/mods/blade-yautja

here is the link. i think i spelled it wrong.

https://www.moddb.com/members/bladeghost/downloads

her eis the user account for his files for the mods.

**Comment by DanielGibson** [comment]
that one might work, at least BadeYautja_1.2.zip doesn't seem to contain any custom DLL (I haven't looked closely at the standalone thing, but it being standalone probably means that it doesn't need Doom3 or dhewm3)

**Comment by DOOMMARINE117** [comment]
> 
> 
> that one might work, at least BladeYautja_1.2.zip doesn't seem to contain any custom DLL (I haven't looked closely at the standalone thing, but it being standalone probably means that it doesn't need Doom3 or dhewm3)

cool so i guess as long it doesn't need need doom 3 or dhwem3 im ok to load them in the dhwem 3 folder. all i do is load the folder of the mod an it add it in the dhewem 3 mod in the main menu?

**Comment by DanielGibson** [comment]
the standalone things don't belong in the dhewm3 folder and don't need the doom3 gamedata (it could even be that adding the doom3 gamedata breaks them).
they have their own .exe files to start them.
they have nothing to do with dhewm3.

**Comment by DOOMMARINE117** [comment]
> 
> 
> the standalone things don't belong in the dhewm3 folder and don't need the doom3 gamedata (it could even be that adding the doom3 gamedata breaks them).
> they have their own .exe files to start them.
> they have nothing to do with dhewm3.
> 
> the mod version can be extracted into the dhewm3 folder and should be available in the main menu

cool. 

what should it be named for Dwhem 3 mod menu? any name can work?

**Comment by DanielGibson** [comment]
In `your_doom3_directory/` (as in the example above), **next to** the `base/` directory, add another directory for the mod, like `bladeyautja/`.
In that directory put all the Blade Yautja gamedata (the .pk4 files etc), so it looks like
```
your_doom3_directory/
    base/
        pak000.pk4
        ... (and the other .pk4 files of base/)
    bladeyautja/
        custom_images/
        custom_tunes/
        guis/
        autoexec.cfg
        predwarrior_D3_EXTRA_SHINE.pk4
        ... (and all the other files)
```

**Comment by DOOMMARINE117** [comment]
> 
> 
> In `your_doom3_directory/` (as in the example above), **next to** the `base/` directory, add another directory for the mod, like `bladeyautja/`.
> In that directory put all the Blade Yautja gamedata (the .pk4 files etc), so it looks like
> 
> ```
> your_doom3_directory/
>     base/
>         pak000.pk4
>         ... (and the other .pk4 files of base/)
>     bladeyautja/
>         custom_images/
>         custom_tunes/
>         guis/
>         autoexec.cfg
>         predwarrior_D3_EXTRA_SHINE.pk4
>         ... (and all the other files)
> ```

cool. 

how should i named the folders for neverdead an phantasm armagaddeon? what about the lost mission?

**Comment by DanielGibson** [comment]
Generally the foldernames don't matter too much, but they'll have to match the name of the corresponding game DLL, if one is needed (**dhewm3-compatible game DLLs for phantasm and neverdead don't exist so those won't work anyway**).
The correct foldername for Lost Mission is `d3le/`

**Comment by DOOMMARINE117** [comment]
> 
> 
> Generally the foldernames don't matter too much, but they'll have to match the name of the corresponding game DLL, if one is needed (**dhewm3-compatible game DLLs for phantasm and neverdead don't exist so those won't work anyway**).
> The correct foldername for Lost Mission is `d3le/`

https://www.moddb.com/mods/phantasm-beyond-ii-the-neverdead/downloads/theneverdead-phantasmbeyond2-full

https://www.moddb.com/games/phantasm-armageddon-pc-game/downloads/phantasmarmageddon

here are the links.

**Comment by DanielGibson** [comment]
> Phantasm Armageddon PC-Game Unreal Engine 4 Updated game from Phantasm Doom 3 Mod as an Independent game rebuilt with other and new elements.

Why do you assume this will work with Doom3?

And the other one that actually is for Doom3 **has it's own game DLL that hasn't been ported to dhewm3 so it will not work either, I already wrote that, do you only read every second sentence I write?**.
