### ISSUE TITLE
Game doesn't properly switch to 4K resolution on 1080p display with DSR

### ISSUE THREAD

**Issue by DanielGibson** [dhewm/dhewm3#317]
From https://twitter.com/natzaw_/status/1311292103067078657

> When playing at 4K, game remembers the resolution set in options but don't automatically switch to it after starting. (using nvidia DSR on 1080p screen). If I want to play at 4K, first I have to set the windows resolution to 4K.  After switching this back to normal res and starting the game again - there's severe tearing across screen.
Second problem is minor - RTSS doesn't show itself in the cut scenes.

**Comment by DanielGibson** [comment]
turns out this is an SDL bug that I reported myself: https://bugzilla.libsdl.org/show_bug.cgi?id=4700
Yamagi Quake II has a workaround (there it was reported in https://github.com/yquake2/yquake2/issues/302) that I should probably also use (until this bug finally gets fixed in SDL), see https://github.com/yquake2/yquake2/blob/master/src/client/vid/glimp_sdl.c#L94 and following

**Comment by DanielGibson** [comment]
This is hopefully fixed in: [dhewm3_1.5.1_RC2+fullscreenfix.zip](https://github.com/dhewm/dhewm3/files/5611056/dhewm3_1.5.1_RC2%2Bfullscreenfix.zip) (built from https://github.com/DanielGibson/dhewm3/tree/fullscreen_fixes).

I couldn't test it because I don't have a nvidia card in my windows machine and AMDs VSR doesn't seem to support OpenGL.

**Comment by DanielGibson** [comment]
Ok, AMD VSR is great fun, turns out:
* It does *not* work with a normal dhewm3.exe (like the one I linked above; note that it might still work with nvidia DSR)
* It does work with original Doom3.exe
* It does work if I rename dhewm3.exe to doom3.exe
  - surprisingly it still works with the original Doom3.exe if I rename it to dhewm3.exe
* It does work with dhewm3.exe if I build without tools support
  - If I build dhewm3.exe without tools support *but* still link MFC, it does *not* work

So apparently just linking MFC breaks it, no matter what the code does - but OTOH, vanilla Doom3 still works despite linking MFC (and even if renamed so their executable-name-based quirk probably doesn't match - unless they *also* match by the binaries hash or sth?)

"Doesn't work" above always means that it looks like this:
![dhewm3_vsr_display](https://user-images.githubusercontent.com/1216493/100530643-c4e42780-31f4-11eb-823b-22ab762b53dd.jpg)
and when taking a screenshot it has the right resolution (3840x2400, my screen is 1920x1200) but looks like this:
![dhewm3_vsr](https://user-images.githubusercontent.com/1216493/100530612-674fdb00-31f4-11eb-931e-3b8fa6bee143.jpg)

**Comment by Yamagi** [comment]
I gave it a try on my trusty Geforce 750 TI under Windows. As long a I use fullscreen resolutions up to the native resolution of my display (2560x1440) evenrything is okay. As soon as I try to switch to the DSR 2x resolution (5120x2880), the work around for the SDL bug we've implemented yesterdays triggers and somehow I'm ending in an endless loop trying to recreate the SDL windows. The log is here: [stdout.txt](https://github.com/dhewm/dhewm3/files/5611950/stdout.txt)

The same works with YQ2. I can set 5120x2880, the game is rendered in that resolution and downscaled by the driver. I've checked it by taking a screenshot.

**Comment by DanielGibson** [comment]
Seems to work for the reporter on Twitter though: https://twitter.com/natzaw_/status/1332989671958327297
> Hello Daniel, it works 100% :) thank you very much for this.

I hate computers.

**Comment by DanielGibson** [comment]
Here the same code build without tool support (just the .exe) [dhewm3_notools.zip](https://github.com/dhewm/dhewm3/files/5612698/dhewm3_notools.zip)

**Comment by Yamagi** [comment]
Okay, some more investigation. For a better understading the display setup is 1280x1024 - 2560x1440 - 1280x1024. The leftmost display is the primary one. Some Windows application have problems when the primary display isn't the left- or rightmost, so I can not set the 2560x1440 as primary.

* dhewm3.exe with fix: Nvidia doesn't detect dhewm3.exe as game (it doesn't show up in the list of known games) and sends 2560x2048 as  DSR resolution. That's likely derived from the primary display. If I set the 2560x1440 display as primary, 5120x2880 is send. But the game isn't scaled, it looks like on the screenshot above. As a side  note this doesn't happen with yquake2.exe. Nvidia detects it as a game after the first start and everything works.
* doom3.exe, renamed from dhewm3.exe with fix: Doesn't change anythings.
* dhewm3_notools.exe: Nvidia detects it as a game after the first start and everything works.

So compiling the tools into the executable (adding MFC calls to it) break the game detection.

**Comment by DanielGibson** [comment]
> So compiling the tools into the executable (adding MFC calls to it) break the game detection.

At least on AMD it's enough to just **link** MFC without calling it (ok, maybe the DLL has constructors that do implicit calls, but I didn't call anything myself).

**Comment by DanielGibson** [comment]
the fix is in master, the next binaries will include a dhewm3_notools.exe that should work better with DSR and VSR (due to not linking against MFC)
