### ISSUE TITLE
Improve error message when loading mod.so fails

### ISSUE THREAD

**Issue by DanielGibson** [dhewm/dhewm3#318]
I think right now it only says "couldn't load mod-specific bla.so ..." - it should be possible to get some more details (does the file exist at all? were symbols missing? ...), at least print  whatever `dlerror()` returns

**Comment by HarrievG** [comment]
Created https://github.com/HarrievG/d3wasm/tree/upstream-dllLoadErrors to implement this for WINDOWS

**Comment by DanielGibson** [comment]
Thanks a lot for working on this! :)

**Comment by DanielGibson** [comment]
done (thanks to @HarrievG for doing the windows-part!)
