### ISSUE TITLE
specify custom folder config

### ISSUE THREAD

**Issue by legluondunet** [dhewm/dhewm3#321]
Hello,
is it possible to specify another folder for config files than ~/.config/dhewm3/base?
It would be interesting to specify another folder for config files in goal to make dhew3 portable on Linux.

**Comment by parkerlreed** [comment]
It can go in any number of folders. ~/.local/share/dhewm3 is another

Anyways, read `--help`

There's examples towards the bottom. 

fs_gamepath

**Comment by garoto** [comment]
`+set fs_basepath <path> +set fs_configpath <path> +set fs_savepath <path>`

I guess these are the options.

**Comment by legluondunet** [comment]
it works thank you very much.
