### ISSUE TITLE
Some keys are not recognized

### ISSUE THREAD

**Issue by Sol1vaN** [dhewm/dhewm3#323]
Hi! and thanks for this great port.

I've tested and this work awesome.

But, are some things that need to check in the keys detection.

For example, I use the keys semicolon, Win Keys, and all many other keys are not recognized. Well, Win Key is recognized, but this minimizes the game.

In CstDoom3, all the keys can be binded, even the Win key can be binded without problem.

Here's a resume of all keys that have problems:

1) RWin key (is recognized but minimizes the game)
2) Aphostrope is not recognized
3) Semicolon is not recognized
4) \ or | (the same physic key) is not recognized
5) = or EQUAL (the same physic key) is not recognized
6) CTRL and RAlt are recognized like only ONE KEY, I mean only CTRL
7) LCTRL and RCTRL are recognized like only ONE SAME KEY, I mean, CTRL

In CstDoom3 the not recognized keys in dhewm3 are detected very fine, but I noticed are detected with different symbols (not names):

1) RWin key is recognized and NOT minimizes the game
2) Aphostrope is recognized like  '
3) Semicolon is recognized like Ñ
4) \ or | (the same physic key) is recognized like Ç
5) = or EQUAL (the same physic key) is recognized like ;
6) CTRL and RAlt are recognized like diffrerent KEYS, I mean ALT or CTRL respectively
7) LCTRL and RCTRL sadly, are recognized like only ONE SAME KEY too, I mean, CTRL

but ey! the key layer detection in CstDoom3 are mostly perfect!

So, any way to bring all this stuff to dhewm3 too?

**Comment by DanielGibson** [comment]
I think I have fixes for most of these issues in #397.

> LCTRL and RCTRL are recognized like only ONE SAME KEY

Somehow I fail to see how one would use the keyboard while playing when using both Ctrl keys?
I mean, if you play on WASD or ESDF or whatever, you can only reach the left Ctrl key - and if you play on the cursor keys you can only reach the right one..

> CTRL and RAlt are recognized like only ONE KEY, I mean only CTRL

So if you press Ctrl, it is recognized as Ctrl, and if you press RAlt it is also recognized as Ctrl?
I somehow would've expected RAlt to be recognized as Alt (it is on my keyboard)..

> RWin key (is recognized but minimizes the game)

I guess this is a feature (on Windows; on Linux I can bind and use it, at least with XFCE).. but there might be a way to disable it (but then Alt-Tab won't work anymore either, I think). If I allow this, it'll have to be enabled with a CVar.

I'll create a Windows testbuild later today

**Comment by DanielGibson** [comment]
A Windows Testbuild is available at https://github.com/dhewm/dhewm3/pull/397#issuecomment-873413013 - I think it should fix all the problems you mentioned here, can you please verify?
Thanks in advance!

**Comment by DanielGibson** [comment]
I merged those fixes now and assume that your issues are resolved, otherwise please reopen.
