### ISSUE TITLE
Intro hijacks mouse in windowed mode

### ISSUE THREAD

**Issue by darkcharmander** [dhewm/dhewm3#329]
When running the game in windowed mode, the intro hijacks your mouse and locks it in the center of the window. I've sometimes had the issue of the game getting in a bugged state, and I was unable to use my mouse and kill it via task manager (Had to navigate using the keyboard). After playing the intro, the mouse becomes unlocked again.

In full screen mode, the problem isn't really that noticeable when playing the intro.

Is it possible to skip the intro? That would be a simple fix. Nobody wants to see the intro anyways :p

**Comment by DanielGibson** [comment]
`dhewm3.exe +disconnect` skips the intro video (I assume you mean that id logo thing at startup, not the scripted intro when starting a new game?)

**Comment by darkcharmander** [comment]
>I assume you mean that id logo thing at startup, not the scripted intro when starting a new game?

Indeed, I am talking about the id thingy at startup.

I'll just launch the game with the `+disconnect` parameter then. That indeed skips the intro and 'fixes' this. I'll close the issue, because I assume that you don't want to look into the source of the mouse hijacking problem. It's up to you though ;) Thanks!
