### ISSUE TITLE
Chaingun sound loops when pressing escape

### ISSUE THREAD

**Issue by darkcharmander** [dhewm/dhewm3#330]
When shooting the Chaingun, the sound will loop whenever you open the menu while shooting. It will stop afterwards.
Attached is a small video which clearly shows this issue. (I had to zip it, because Github refuses MP4...)
[Chaingun Sound Glitch.zip](https://github.com/dhewm/dhewm3/files/5548692/Chaingun.Sound.Glitch.zip)

**Comment by DanielGibson** [comment]
I think this is fixed, can you try out the testbuild linked in https://github.com/dhewm/dhewm3/pull/363 ?
Thanks!

**Comment by darkcharmander** [comment]
I've tested the mentioned build, and the glitch is no longer present. Good job!
