### ISSUE TITLE
Mars city Security mod no works

### ISSUE THREAD

**Issue by dj--alex** [dhewm/dhewm3#343]
Thanks for working doom3  its brilliant!! 
But Authors of mod Mars City guaratnee work with Doom 3 for Linux
But no work (using latest dhewm 1.5.0 linux amd64 ) 
Dhewm is not correct doom 3 1.3.1 binary (!) 
https://www.moddb.com/mods/mars-city-security/downloads/mcs-1239-all-os-installer-less-archive-949-mb

Run from doom3 (dhewm 1.5.0 64bit Linux) 
Error when running doom3 binary (dhewm 1.5.0 64bit)
WARNING: Could't load mod specific doom3-mcs.so defaulting
Run doom3-roe (dhewm) 

Full error log with run doom3-roe (dhewm 1.5.0) 
https://pastebin.com/fBiMVZCz

https://sun9-65.userapi.com/impg/SiBxhSwAB4v2gNepvtY_UDwbSaN5do_ZZZlZMQ/gYh1xG7tS0M.jpg?size=1280x800&quality=96&sign=c06fce6bb7bc320e216b597da9526035&type=album

Error:
Starting MCS as a Client.
mcs_run_client.sh: 15: mcs_run_client.sh: doom3: not found
user@pc1:/media/user/F/Games/doom3_en/Doom3$ 

official forum mod
http://www.scared-pixel-studios.com/forums/viewtopic.php?f=50&t=594

**Comment by DanielGibson** [comment]
Dhewm3 is incompatible with old unported Mods.

You could try to convince the Mars City Security developers to release the source code of their game.dll under GPL so it can be ported to dhewm3.
