### ISSUE TITLE
Fix issues with script-state in savegames and argsizes in scripts

### ISSUE THREAD

**Issue by DanielGibson** [dhewm/dhewm3#344]
As it turned out when debugging #328, the fix for #303 broke savegames.
Fixing this is practically impossible (without breaking #303 again, which might be the lesser of two evils in the short term).

## The original problem

To recap, the problem in #303 was that if you have a script where method **a** calls method **b** before **b**'s implementation (=> it is only known at all because of its prototype/declaration in the class/object definition), it reserves the wrong amount of space on  the stack for the passed function parameters, because their size is only calculated when parsing the implementation, not when parsing the prototype, see `idCompiler::ParseFunctionDef()`: https://github.com/dhewm/dhewm3/blob/280c95b52c5d39a4aec8ac033189d84d37f54c84/neo/game/script/Script_Compiler.cpp#L2147-L2173

## Initial fix and why it caused (other) problems

[My fix](https://github.com/dhewm/dhewm3/commit/c4c72363523fc65e635c7ad7ae86247b4f082340) was to already set the function parameter types and calculate their combined size when parsing the prototype.
Problem with this is, that it also allocations definitions for those parameters (`gameLocal.program.AllocDef( type->GetParmType( i ), type->GetParmName( i ), def, false );`), and those definitions get a number (to identify them in savegames and such) that is just incremented each time `AllocDef()` is called. As now this is done earlier and in another order than before, those definition numbers (`int idVarDef::num`) are different than they were before, which breaks  the savegames.
Specifically, `idProgram::CalculateChecksum()` returns a different value than before (and this checksum is saved in savegames), so `idProgram::Restore()` returns `false`, so `idGameLocal::InitFromSaveGame()` also returns `false` which causes `idSessionLocal::ExecuteMapChange()` to abort loading the savegame and restart the map from the beginning (though it seems like player stats like health and ammo are preserved).

## Possible improved fix and why that still has issues

Now this alone is fixable: In `idCompiler::ParseFunctionDef()` I can put the `if ( !CheckToken( "{" ) ) {` check back on top, and before returning I can calculate and set `func->parmTotal` (and probably also set `func->parmSize[i]`), *but not* do the parameter definition part (that calls `AllocDef()`) and that way the right sizes are used everywhere but the definitions are allocated in the same order as before so they don't change.
However, it turned out that the calculated checksum is still different, though there's much fewer differences in the statements.

The reason for that was that the bug I fixed (of methods argument-sizes not being known when needed) doesn't only affect "broken" scripts that trigger the assertions - this doesn't happen in the main game or d3xp, but only in mods (incl. script-only mods that people copy into base/ or d3xp/ like the weapon-flashlight mod or whatever).
The bug does also affect scripts from base/, it just doesn't trigger the assertions!
One example is weapon_fists.script line 62, in `weapon_fists::Fire()`:
`playAnim( ANIMCHANNEL_ALL, GetFireAnim() );`
The problem here is the call to `GetFireAnim()` **in a function call** (because that method is implemented *after* `Fire()`).
So the parameter size of `Fire()` isn't known (it doesn't have visible parameters, but the implicit `self` pointer which is like `this` in C++). For some reason that doesn't trigger any assertions, but it's still wrong and the size changes with my fix and that breaks the savegames.
The `statementBlock_t` in dhewm3 versions before I added the aforementioned fix looks like
`op: 47 a: 681 b: 682 c: 405 line: 62 file: 5` (this is just from my custom debug print I added in `CalculateChecksum()`)
in my local uncommitted version (that only calculates `parmTotal` but doesn't call `AllocDef()` when parsing the prototype) it looks like:
`op: 47 a: 681 b: 682 c: 427 line: 62 file: 5`
`c: ` is different and refers to `statementBlock_t::c` which is assigned from `statement_t::c->num` in `CalculateChecksum()`.
`47` is `OP_OBJECTCALL`, and in those cases `statement_t::c` is from `SizeConstant( func->value.functionPtr->parmTotal );` (see `idCompiler::EmitFunctionParms()`) which returns a constant of that size; size constants are cached, so only one exists for each size that's used everywhere that size is needed; `427` is **not** the size, but an identifier for the constant (similar to `idVarDef::num`).

## And now?

~~I don't think this is properly fixable without breaking savegame-compatibility, except by reverting my initial fix.
That's not really satisfying, of course..
One thing that makes working around this issue so hard is that the scripts are loaded and compiled once when the game starts, **not** on each level/savegame load. So "just detect old savegames and only in their case don't do the size calculations on prototypes" is not an option.~~
_**UPDATE:** I found a solution after all, see next post._

I have though of doing the following (not much fleshed out yet):
* Print a Warning when the savegame isn't loaded because the script-state checksum doesn't match (no idea why this doesn't happen already)
* Revert the fix **for now**, at least in the base game and d3xp.
  - I might keep it in mods, esp. mods whichs scripts cause assertions without it - if savegames break there only very few people will be affected
* Bump the savegame version and change the savegame format and add additional information to the savegame
  - Host-OS (Linux/Windows/...)
  - CPU Architecture (i386/amd64/...)
  - Pointer size (`sizeof(void*)`) - because 32bit savegames are incompatible with 64bit savegames as some sizes in the script state (which are pointers) are different
  - Endianess
  - Possibly more information about the script state than just the checksum of all statements?
  - The code will continue to load old savegames as it should: It'll check the savegame version and only load these new fields for new savegames
* In some future release I activate the fix again, compatibility with savegames from before 1.5.1 will be broken (but hopefully at that point not many of those will be around anymore), ones from 1.5.1 will hopefully continue to work, by adding workarounds based on the new information in the savegames.
  - Maybe I can just skip comparing the checksums if OS + CPU architecture or even just the pointer size + Endianess matches?
  - Or I could change the checksum calculation to ignore `statement.c` for `OP_OBJECTCALL` - if that's ok? And if that's the only broken case left? (Probably not, should be the same for other kinds of function calls or events that have another function call as parameter, but I only had those differences for OB_OBJECTCALL in the base game)
  - Or I can replace the checksum-based check with other checks based on other information about the script state I might save?
    For this to work I'd have to figure out what exact information I need **now** (before 1.5.1)!
    * In my test savegame there's almost 67900 statements, each `statementBlock_t` is 20 bytes, so that would be 1.36MB per savegame, which seems a bit excessive? Might be compressible though. OTOH, maybe even more information is needed?

**Comment by DanielGibson** [comment]
I think I have a solution after all.
I'm gonna do most of the things I listed above, and additionally adjust `idProgram::CalculateChecksum()` to set `statement.c` to the argSize constant for 0 when loading an old savegame and the statement is `OP_OBJECTCALL` and it's of a method whichs implementation hasn't been parsed yet (I'll add a flag to `statement_t` for that).

I tested it a bit and it seems to work (at least for the base game), but I haven't implemented it cleanly/properly yet, so I haven't commited it yet.
I think it should even work for "broken" scripts that would previously trigger assertions; it definitely does for the scripts in the base game that didn't trigger assertions but still gave a different checksum with the fix, see the other post above.
Or, more specifically, the old savegame loads with the workaround, I hope it doesn't break anything that the size assumed by the savegame is different that the one used by the script now. I doubt it, but if it does, this approach won't work either..

**Comment by HarrievG** [comment]
Hi Daniel, 

I have added an savegame, which does not trigger an checsum fail , while still exposing the bug.
I am not sure, that just not respecting the checksum to preserve savegame compatibilty coult _not_ work. I think i fail to see to total implications of it. 

Afaik: the moment the miscalculted argument size for the function is a problem, is only when a function with an implemented prototype is called, before it is parsed. And i find it debatable if this is not an author bug from the sripter, he is in essence calling an not (yet) declared function. 

Also, with the fix in place, the object size is wrong for classes that do _not_ implement that prototype function.
They will take up extra space, which is not needed.

Weapon_base and Weapon Fist.
Your statement that the GetFireAnim() is not parsed fully before it called is , i think, not correct.
That function is actually implemented int weapon_base itself.

```

object weapon_base {
				// required by game
	boolean		WEAPON_ATTACK;
	boolean		WEAPON_RELOAD;
	boolean		WEAPON_NETRELOAD;
	boolean		WEAPON_NETENDRELOAD;
	boolean		WEAPON_RAISEWEAPON;
	boolean		WEAPON_LOWERWEAPON;

				// required by player script.
	boolean		WEAPON_START_FIRING;

				// called by game
	void		EnterCinematic();
	void		ExitCinematic();
	void		NetCatchup();
	void		WeaponStolen();
	void		OwnerDied();
	void		UpdateSkin();

				// called by player script
	string		GetFireAnim();
};
/..../
weapon_base::GetFireAnim

Used by the player script to get the fire anim.  Subclasses can override this in order to sync the
viewmodel with the player model.
=====================
*/
string weapon_base::GetFireAnim() {
	return "fire";
}

```

With your fix it just already allocated before its gets to parse the implementation itself. So in this particular case, the end result would have been the same.

**Comment by HarrievG** [comment]
On a side note: 
There also seems to be (at least on windows) an wrong path in the filelist of the main program. They have two backslashes in stead of a single front.
This filename also gets written away in the save game. Does this not give different results on win/unix?

**Comment by DanielGibson** [comment]
I don't think the paths really matter - and when passing paths to windows file opening functions you need two backslashes, so e.g. `"dir\thing"` really is parsed as `"dir/thing"` and not `"dir<tab>ing"` (as '\t' is the escape code for tab - yes, Microsofts decision to use backslash to separate directories was really bad)

**Comment by DanielGibson** [comment]
https://github.com/dhewm/dhewm3/tree/344-fix-script-savegame contains two commits with the aforementioned changes.
I haven't gotten around to do them in d3xp/ as well, so it's only in the base-game's code (and some general code) for now (will probably do d3xp/ tomorrow).

**Comment by DanielGibson** [comment]
https://github.com/dhewm/dhewm3/pull/346 contains the fixes, I think this is the final state but it could need some testing before it's merged to master.

**Comment by HarrievG** [comment]
I will test it later tonight and let you know.

**Comment by HarrievG** [comment]
Builds and runs like normal.

_For reference : 

Build trace with added defs highlighted (win10 / visualstudio + vcpk / x32-Debug):

`[439/440] C:\PROGRA~2\MIB055~1\2019\COMMUN~1\VC\Tools\MSVC\1428~1.293\bin\Hostx64\x86\cl.exe  /nologo /TP -`_DD3_ARCH=\"AMD64\" -DD3_OSTYPE=\"windows\"_` -DD3_SIZEOFPTR=4 -DGAME_DLL -DWINVER=0x0501 -D_ALLOW_KEYWORD_MACROS -D_WIN32_WINNT=0x0501 -Dbase_EXPORTS -IE:\vcpkg\installed\x86-windows\include -IE:\vcpkg\installed\x86-windows\include\AL -IE:\vcpkg\installed\x86-windows\include\SDL2 -I. -I..\..\ -I..\..\game /DWIN32 /D_WINDOWS /W3 /GR /EHsc -D_DEBUG /Od /Zi /MDd /MP /W4 /we4840 /wd4100 /wd4127 /wd4244 /wd4245 /wd4267 /wd4714 /wd4996 /wd4068 /wd4458 /showIncludes /FoCMakeFiles\base.dir\game\physics\Push.cpp.obj /FdCMakeFiles\base.dir\ /FS -c ..\..\game\physics\Push.cpp`_

SaveFile 
[enhanced_saveinfo_1.zip](https://github.com/dhewm/dhewm3/files/5939844/enhanced_saveinfo_1.zip)

**Comment by HarrievG** [comment]
> I don't think the paths really matter - ~and when passing paths to windows file opening functions you need two backslashes, so e.g. `"dir\thing"` really is parsed like `"dir/thing"` and not `"dir<tab>ing"` (as '\t' is the escape code for tab - yes, Microsofts decision to use backslash to separate directories was really bad)~
> UPDATE: Thinking about it, this might still be wrong - in string literals you definitely need more backslashes, but in strings read from a file, probably not.. maybe it's wrong after all.
> But I'm also not sure what you're talking about, the few backslashes I see in the console or stdout.txt aren't double - and even if they were it shouldn't break anything, I think they just get ignored (`"bla\\foo"` handled like `"bla\.\foo"` which behaves the same as `"bla\foo"`)

Just checked the main program file list without my debugger changes in, to be sure it is not due to my changes:
For now, i will attach an image, which show the file list when the first script function gets executed (doom_main() in doom_main.script)
![image](https://user-images.githubusercontent.com/1131446/107157960-51def600-6987-11eb-96f0-e4f608d24020.png)

I will fix this when i integrate the script debugger.

**Comment by HarrievG** [comment]
and i have spotted one other potential save issue:
https://github.com/dhewm/dhewm3/blob/2139a122c58bfe2a449320ff669532add53c943b/neo/framework/CVarSystem.cpp#L247
![image](https://user-images.githubusercontent.com/1131446/107158065-e9444900-6987-11eb-813c-64dedf5624a0.png)

**Comment by DanielGibson** [comment]
Regarding the backslashes, the debugger displays it like that because that's the format you'd have to use in string literals in code.

Regarding `FindChar( value, '.' )`: yes, that looks fishy, but I'm not sure what they're trying to achieve there.
The check somehow is for the case if `IsNumeric()` returned false - do they want to do `valueString = idStr( integerValue );` if there is no dot at all in it (then `!= -1` is correct) - or if there is a dot, or maybe not, but **not** at position 0 (because then FindChar() returns 0, and `idStr::FindChar( value, '.' )` is equivalent to `idStr::FindChar( value, '.' ) != 0` after all)?
The latter sounds a bit stupid, but I imagine that `atoi()` returns `0` if you feed it `"0.123"`, but it probably returns nonsense if you pass `".123"` (which for floats is equivalent to the former)?
