### ISSUE TITLE
Incorrect transparency with aarch64 + panfrost + wayfire, opengl 3.1 

### ISSUE THREAD

**Issue by clort81** [dhewm/dhewm3#359]
Thought I'd share a funny rendering bug.
System is Khadas Vim3 with mali g52 GPU and panfrost drivers.
Wm+Compositor is Wayfire
When i use wayfire to scale-up the rendered window, i get very amusing transparency.

![dhewm3_wayfire_scaledwindow_panfrost1](https://user-images.githubusercontent.com/51511737/111864932-3393ef00-8964-11eb-91b7-00170dfdf156.jpg)
![dhewm3_wayfire_scaledwindow_panfrost2](https://user-images.githubusercontent.com/51511737/111864934-355db280-8964-11eb-847c-cbd8d72d725a.jpg)

 I'm guessing this is some odd interaction with Wayfire's scaling, since nothing else causes it.

**Comment by DanielGibson** [comment]
You could try setting `r_waylandcompat 1` (in the console, can be opened with shift+esc)

**Comment by clort81** [comment]
Brilliant!  That fixed it for me.  Closing.
