### ISSUE TITLE
SDL2.0.14  default changed for SDL_HINT_VIDEO_MINIMIZE_ON_FOCUS_LOSS

### ISSUE THREAD

**Issue by j4reporting** [dhewm/dhewm3#360]
DHEWM3 screen is no longer  minimized when switching from SDL fullscreen back to windows desktop via ALT+TAB. The default behaviour changed in SDL2.0.14. 

see also https://github.com/yquake2/yquake2/commit/11bcb785d0da60e21e2c9fbbe7bcc4179947a26e

**Comment by DanielGibson** [comment]
Does this cause real problems in dhewm3 (that doesn't have yq2's fragile Vulkan renderer)?

**Comment by j4reporting** [comment]
it affects all applications/games that use SDL fullscreen, regardless of the renderer.  On windows, it prevents the user from accessing the desktop because the SDL fullscreen application is not minimized and there is no way to minimize a fullscreen application without windows decorations.
Unfortunately, SDL does not evaluate SDL_HINTS set as enviroment variables on WIndows. Basically, this ruins the option to switch to desktop w/o quitting the game or switching to window mode.

**Comment by DanielGibson** [comment]
Fixed, thanks for reporting!
