### ISSUE TITLE
ERROR: Couldn't load script/doom_main.script

### ISSUE THREAD

**Issue by Does1tReallyMatter** [dhewm/dhewm3#361]
I literally have no idea what to do, I am very much pissed off.

**Comment by Does1tReallyMatter** [comment]
i should probably warn that i am unbelievably stupid and i am probably missing something painfully obvious

**Comment by Does1tReallyMatter** [comment]
nevermind, i am stupid, i am trying to run a non-bfg compatible mod with the bfg edition

**Comment by DanielGibson** [comment]
Gute Besserung!
