### ISSUE TITLE
Widescreen support

### ISSUE THREAD

**Issue by libcg** [dhewm/dhewm3#37]
Currently, modification of DoomConfig.cfg is needed to play at a native widescreen resolution.

For example, if I want to play at 1440x900 :

    seta r_customHeight "900"
    seta r_customWidth "1440"
    seta r_mode "-1"

This should be handled automatically by the engine.

**Comment by DanielGibson** [comment]
Ok, I added lots of resolutions to r_vidModes[] and wrote a really ugly hack that replaces the hardcoded shit from mainmenu.gui with strings generated from r_vidmodes[].

It's not in master yet but in the widescreen branch, see https://github.com/dhewm/dhewm3/tree/widescreen

If anyone still is interested in this (3 years later ;-)) please test it - as it's kinda ugly I didn't feel confident to immediately put this into master.

**Comment by DanielGibson** [comment]
the first feedback I got for that change was positive so I merged it into master.
