### ISSUE TITLE
Resurrection of Evil: Skyboxes in Phobos Labs levels and Hell fail to render.

### ISSUE THREAD

**Issue by Shockwave508** [dhewm/dhewm3#370]
Game: Doom 3 ROE
Issue: In the Phobos Labs levels (at least the ones that have outdoors segments) as well as the lone Hell level in the game, the skybox texture fails to render outright, showing a blank black void instead. Has no effect on overall gameplay, but it's quite noticeable regardless. Conversely, the Hell depicted in the first cutscene of the game (Erebus Sector 1) has its skybox rendered correctly.

**Comment by DanielGibson** [comment]
What operating system, GPU and driver are you using?

**Comment by DanielGibson** [comment]
I think this bug only exists in the "Delta Touch" Android port of dhewm3 that is developed by someone else (and uses a different OpenGL ES based renderer).
Please report that bug there.
