### ISSUE TITLE
Many issues loading mods

### ISSUE THREAD

**Issue by phobosslabs** [dhewm/dhewm3#371]
Hi, I'm having some issues loading the Classic Doom 3 (CDoom) and Lost Mission mods;
CDoom seems locked to fullscreen. I've tried changing the setting and different resolutions, but to no avail. The mod also appears in red text on the mods list? Not sure if relevant, but may be worth mentioning.
The Lost Mission doesn't even load at all. I just get a black window with the Doom 3 pointer magnified.
I have not tried any other mods aside from the RoE expansion; that works fine with no issues.
Any ideas on what I may have done wrong installing or something? I have both the provided dll's in both the base dhewm3 folder and in the respective mod folders.

**Comment by DanielGibson** [comment]
The Lost Mission can't be started with the Mods menu, you need to use d3le.bat (or, if you're not using Windows, start it like `dhewm3 +set fs_game d3le +set fs_game_base d3xp`)

Apparently CDoom doesn't have a fullscreen setting in their menu - but you should be able to open the console (`Shift` + `Esc`) and enter `r_fullscreen 0` and then `vid_restart` to enable windowed mode.

**Comment by DanielGibson** [comment]
I just pushed a commit that allows loading The Lost Mission via the mods menu (by hardcoding a special case for it)
