### ISSUE TITLE
MFC Tool issues

### ISSUE THREAD

**Issue by DanielGibson** [dhewm/dhewm3#378]
From https://github.com/dhewm/dhewm3/pull/377

- [x]  Particle Editor seems to work fine except it silently closed the whole engine (crash?) when I did Save As (I modified default particle emitter, clicked on Save As, specified particle emitter name, specified file name, clicked save/ok(?) button, got asked twice that file doesn't exist and if I want to create new one, after confirming twice Particle Editor closed silently).
- [ ] Light Editor works, along with saveLights cmd. After closing Lights Editor, even after reloading map, light entities are still shown as green wireframed boxes. Not a show stopper, but still a nuisance.
- [x] PDA Editor doesn't work at all (it works in 32bit SE2), but I am not even sure anyone uses it. Still it would be nice to have

**Comment by DanielGibson** [comment]
@motorsep: Does the PDA Editor in SE2 support "Add..." for Audio Logs and Videos? I got the PDA Editor working here, but those buttons don't seem to do anything, I wonder if that's "normal"

**Comment by DanielGibson** [comment]
> After closing Lights Editor, even after reloading map, light entities are still shown as green wireframed boxes. 

just enter `g_editEntityMode 0`, I guess it's a feature

**Comment by DanielGibson** [comment]
Here is an updated Win64 build which fixes the particle editor and PDAEditor issues mentioned above: [dhewm3-1.5.2pre-win64-tools2.zip](https://github.com/dhewm/dhewm3/files/6448184/dhewm3-1.5.2pre-win64-tools2.zip)

**Comment by motorsep** [comment]
Tested, seems to be working fine now. Thanks!
