### ISSUE TITLE
A Place of Malice Mod (pure map only with regular map script) crash the engine.

### ISSUE THREAD

**Issue by erickzmx** [dhewm/dhewm3#382]
This map crash the engine and the map is working with vanilla Doom3.
Loaded pk4 .local/share/dhewm3/d3xp/temple_sp2.pk4 with checksum 0xf163b023
...
loaded collision model models/z13sp2/temple/endarea_lava.ASE
loaded collision model models/z13sp2/temple/gooey_endarea.ASE
loaded collision model models/z13sp2/temple/floortile_b_1.ASE
loaded collision model models/z13sp2/temple/floortile_a_3.ASE
loaded collision model models/z13sp2/temple/floortile_a_1.ASE
loaded collision model models/z13sp2/temple/teleporter_room_cave.ASE
loaded collision model models/z13sp2/temple/gooey_hell_wall_3.ASE
loaded collision model models/items/shells_ammo/d3xp_shells_large_lo.lwo
Looks like dhewm3 1.5.1rc3 crashed with signal SIGSEGV (11) - sorry!

Backtrace:
  ./dhewm3() [0x5c25d9]
  /lib64/libpthread.so.0(+0x13a30) [0x7fc33f8b2a30]
  ./dhewm3() [0x4c4aaf]
  ./dhewm3() [0x436f53]
  ./dhewm3() [0x43a055]
  ./dhewm3() [0x43dd73]
  ./dhewm3() [0x519db5]
  ./dhewm3() [0x51a46f]
  /home/erick/dhewm3-1.5.1_RC3/build/d3xp.so(+0x8f6b5) [0x7fc31f63f6b5]
  /home/erick/dhewm3-1.5.1_RC3/build/d3xp.so(+0x8ffc1) [0x7fc31f63ffc1]
  /home/erick/dhewm3-1.5.1_RC3/build/d3xp.so(+0x171ec3) [0x7fc31f721ec3]
  /home/erick/dhewm3-1.5.1_RC3/build/d3xp.so(+0x171eaa) [0x7fc31f721eaa]
  /home/erick/dhewm3-1.5.1_RC3/build/d3xp.so(+0xaacaa) [0x7fc31f65acaa]
  /home/erick/dhewm3-1.5.1_RC3/build/d3xp.so(+0xb3a2f) [0x7fc31f663a2f]
  /home/erick/dhewm3-1.5.1_RC3/build/d3xp.so(+0xb3c5d) [0x7fc31f663c5d]
  /home/erick/dhewm3-1.5.1_RC3/build/d3xp.so(+0xb3d2d) [0x7fc31f663d2d]
  ./dhewm3() [0x4ef978]
  ./dhewm3() [0x4efcae]
  ./dhewm3() [0x4f0236]
  ./dhewm3() [0x4a0622]
  ./dhewm3() [0x4d0241]
  ./dhewm3() [0x4a49c7]
  ./dhewm3() [0x41493d]
  /lib64/libc.so.6(__libc_start_main+0xd5) [0x7fc33f375b25]
  ./dhewm3(_start+0x2e) [0x41551e]

Segmentation fault (`core' generado)

**Comment by DanielGibson** [comment]
I just pushed a fix to master, can you test it?

**Comment by erickzmx** [comment]
> I just pushed a fix to master, can you test it?
> 
> I didn't test the map very much, it loads now without errors and I walked around a bit. It's possible that those boxes now have some checkerbox standardtexture, not sure - would be great if you could keep your eyes open for something like that (and report if it looked different in orig Doom3)

It works now, we tested the map and everything works like in vanilla as far as we can see until now. I'll report you if I see differences between vanilla and dhewm3.
Thank you very much for fixing this.

**Comment by DanielGibson** [comment]
Awesome, I guess I can close this then :)
