### ISSUE TITLE
couldn't write dhewm.cfg

### ISSUE THREAD

**Issue by C4PTRAMPAGE** [dhewm/dhewm3#384]
release 1.5.1,
when i launch the game it says "couldn't write dhewm.cfg" in the console and changed settings dont persist after restart, iirc because the file its complaining about is where it stores that.

**Comment by DanielGibson** [comment]
what operating system are you using?
if windows, can you post `Documents/My Games/dhewm3/stdout.txt`?
if another OS, can you run the game in a terminal and post what it writes into the terminal?

thanks in advance!

**Comment by C4PTRAMPAGE** [comment]
i've never used the dewhm3 source port before so i dont know why this worked but deleting the Documents/My Games/dhewm3 folder fixed it.

heres the log if you still want it
[stdout.txt](https://github.com/dhewm/dhewm3/files/6664386/stdout.txt)

now i just need to fix enhanced edition refusing to run in 16:9 and refusing to launch with more than 64mb of vram...

**Comment by DanielGibson** [comment]
Ok, it's weird that you had to delete that folder - maybe it was created without write permissions for some reason (though I have no idea how/why that should happen).
Glad it works now!

(No idea about Doom3 Enhanced Edition, never tried it myself, sorry - I'm really surprised it apparently checks for the amount of RAM, mods really shouldn't care about that, it's business of the engine)

**Comment by DanielGibson** [comment]
I just tried Doom3 EE - I *think* it should work and that you can ignore the system menu displaying 64mb VRAM (dhewm3 doesn't have the corresponding CVar `com_videoRam`) and also that it shows the wrong aspect ratio - if in doubt, check the `r_aspectRatio` CVar (in the console, can be opened with Shift+Esc). If you just enter `r_aspectRatio` it'll show the current value and the meaning of the available values. By default dhewm3 uses `-1` which in the main game and the mods I tested works fine to automatically determine the aspect ratio based on the resolution; but if EE somehow uses that cvar itself and expecting it to be 0 (4:3), 1 (16:9) or 2 (16:10), you can make sure it's set accordingly.

**Comment by DanielGibson** [comment]
Oh, and if the menus look weirdly stretched (because maybe unlike original Doom3, D3 EE supports widescreen resolutions and stretched the fullscreen guis like main menu or PDA accordingly), you can set `r_scaleMenusTo43 0`

**Comment by C4PTRAMPAGE** [comment]
seta r_scaleMenusTo43 0? thats exactly the setting what i was looking for!

i'm probably the only person on the planet who would want this but i'd rather have 4:3 menus stretched to 16:9 than 4:3 with black bars, so thanks i didnt know about that cvar.
