### ISSUE TITLE
Include /dist/ documentation for different platforms

### ISSUE THREAD

**Issue by Eonfge** [dhewm/dhewm3#388]
This is a bit of a general request, but please bare with me: Could you add a platform specific documentation for (re)distributions and packaging?

### Details
_In this issue I'll mostly focus on Linux, but do mind that all major operating systems have similar standards._

Within Linux, there is a growing trend in not just providing code, but to also provide desktop and software-centre integration. One of these standards is called the App Steam standard:

https://www.freedesktop.org/software/appstream/docs/

Some of the key components of this standard, is the adherence to an reverse-url application slug, some icons, desktop files, and a template for meta info. Both of these are mandatory with more modern Linux packaging methods like Flatpak, and I hope that I can interest you.

For the record, I've already created a whole set of these files for Linux, and I'm asking you if you're interested in adding these to the project proper.

**Comment by DanielGibson** [comment]
Could you create a merge request with those files and changes you'd like to see?
Linux (or Linux-ish Desktop) specific files like icons or .desktop files should probably go to `neo/sys/linux/`.

**Comment by Eonfge** [comment]
I'll make a pull request once the files that I've submitted are approved, then I know that they have no errors. As for `neo/sys/linux`, it's a bit uncommon and it might be more clear to other package maintainers when the data is in `/dist/` as they don't have to delve deep into the source code.

As for the files themselves, they look like this:
https://github.com/flathub/flathub/pull/2384/files

**Comment by DanielGibson** [comment]
finally merged this, thanks

**Comment by Eonfge** [comment]
Steady wins the race. It's cool to work together and as we're working together, the Linux version only gets better.
