### ISSUE TITLE
crash on startup (couldn't load game dynamic library)

### ISSUE THREAD

**Issue by jali-peno** [dhewm/dhewm3#413]
`dhewm3 1.5.1rc2.1304 linux-x86_64 Jul 21 2020 13:37:42 using SDL v2.0.14
WARNING: terminal type 'xterm-256color' is unknown. terminal support may not work correctly
terminal support enabled ( use +set in_tty 0 to disable )
pid: 33421
7712 MB System Memory
found interface lo - loopback
found interface wlp4s0 - 192.168.0.221/255.255.255.0
found interface anbox0 - 192.168.250.1/255.255.255.0
doom using MMX & SSE & SSE2 for SIMD processing
enabling Flush-To-Zero mode
enabling Denormals-Are-Zero mode
WARNING: base path '/usr/share/games/doom3' does not exist
----- Initializing File System -----
Loaded pk4 /home/jalipeno/.config/dhewm3/base/pak000.pk4 with checksum 0x28d208f1
Loaded pk4 /home/jalipeno/.config/dhewm3/base/pak001.pk4 with checksum 0x40244be0
Loaded pk4 /home/jalipeno/.config/dhewm3/base/pak002.pk4 with checksum 0xc51ecdcd
Loaded pk4 /home/jalipeno/.config/dhewm3/base/pak003.pk4 with checksum 0xcd79d028
Loaded pk4 /home/jalipeno/.config/dhewm3/base/pak004.pk4 with checksum 0x765e4f8b
Loaded pk4 /home/jalipeno/.config/dhewm3/base/pak005.pk4 with checksum 0x8ffc3621
Loaded pk4 /home/jalipeno/.config/dhewm3/base/pak006.pk4 with checksum 0x95b65ab
Loaded pk4 /home/jalipeno/.config/dhewm3/base/pak007.pk4 with checksum 0x666bdb3c
Loaded pk4 /home/jalipeno/.config/dhewm3/base/pak008.pk4 with checksum 0x23ae5993
Current search path:
/home/jalipeno/.config/dhewm3/base
/home/jalipeno/.config/dhewm3/base/pak008.pk4 (3 files)
/home/jalipeno/.config/dhewm3/base/pak007.pk4 (38 files)
/home/jalipeno/.config/dhewm3/base/pak006.pk4 (48 files)
/home/jalipeno/.config/dhewm3/base/pak005.pk4 (63 files)
/home/jalipeno/.config/dhewm3/base/pak004.pk4 (5137 files)
/home/jalipeno/.config/dhewm3/base/pak003.pk4 (4676 files)
/home/jalipeno/.config/dhewm3/base/pak002.pk4 (6120 files)
/home/jalipeno/.config/dhewm3/base/pak001.pk4 (8972 files)
/home/jalipeno/.config/dhewm3/base/pak000.pk4 (2698 files)
/home/jalipeno/.local/share/dhewm3/base
Addon pk4s:
----- Initializing Decls -----
5206 strings read from strings/english.lang
Couldn't open journal files
execing editor.cfg
execing default.cfg
couldn't exec dhewm.cfg
couldn't exec autoexec.cfg
5206 strings read from strings/english.lang
----- Initializing OpenAL -----
Setup OpenAL device and context
OpenAL: found device 'Built-in Audio Analog Stereo'
OpenAL vendor: OpenAL Community
OpenAL renderer: OpenAL Soft
OpenAL version: 1.1 ALSOFT 1.19.1
OpenAL: found extensions for resetting disconnected devices
OpenAL: found EFX extension
OpenAL: found 256 hardware voices
----- Initializing OpenGL -----
Initializing OpenGL subsystem
Using 8 color bits, 24 depth, 8 stencil display
OpenGL vendor: Intel
OpenGL renderer: Mesa Intel(R) HD Graphics 620 (KBL GT2)
OpenGL version: 4.6 (Compatibility Profile) Mesa 21.0.3
...using GL_ARB_multitexture
...using GL_ARB_texture_env_combine
...using GL_ARB_texture_cube_map
...using GL_ARB_texture_env_dot3
...using GL_ARB_texture_env_add
...using GL_ARB_texture_non_power_of_two
...using GL_ARB_texture_compression
...using GL_EXT_texture_compression_s3tc
...using GL_EXT_texture_filter_anisotropic
   maxTextureAnisotropy: 16.000000
...using GL_1.4_texture_lod_bias
X..GL_EXT_shared_texture_palette not found
...using GL_EXT_texture3D
...using GL_EXT_stencil_wrap
...using GL_EXT_stencil_two_side
... got GL2.0+ glStencilOpSeparate()
...using GL_ARB_vertex_buffer_object
...using GL_ARB_vertex_program
...using GL_ARB_fragment_program
X..EXT_depth_bounds_test not found
ARB2 renderer: Available.
----- R_ReloadARBPrograms -----
glprogs/test.vfp
glprogs/test.vfp
glprogs/interaction.vfp
glprogs/interaction.vfp
glprogs/bumpyEnvironment.vfp
glprogs/bumpyEnvironment.vfp
glprogs/ambientLight.vfp
glprogs/ambientLight.vfp
glprogs/shadow.vp
glprogs/environment.vfp
glprogs/environment.vfp
glprogs/arbVP_glasswarp.txt: File not found
glprogs/arbFP_glasswarp.txt: File not found
using ARB_vertex_buffer_object memory
using ARB2 renderSystem
WARNING: couldn't load mod-specific base.so, defaulting to base game's library!
shutting down: couldn't load game dynamic library
Shutting down sound hardware
idRenderSystem::Shutdown()
Shutting down OpenGL subsystem
Sys_Error: couldn't load game dynamic library
shutdown terminal support
`

running pop!_os 21.04 and downloaded with apt-get

**Comment by DanielGibson** [comment]
you probably forgot to install the `dhewm3-doom3` package which contains the game lib on debian derivatives

**Comment by jali-peno** [comment]
ah yep that does it, thanks lol
