### ISSUE TITLE
high quality setting

### ISSUE THREAD

**Issue by actraiser30** [dhewm/dhewm3#415]
Hello
I have a Raspberry pi 4 with latest Raspbian buster desktop
and doom 3 seems to stuck in loading if i set from the options/system menu the video quality to high, i left it more than half an hour but it remained stuck in loading
if i set it to medium quality it loads ok
is this a common issue?

thanks

**Comment by DanielGibson** [comment]
On my RPi 4B 4GB with latest Raspberry Pi OS **Bullseye** it works both on High and Ultra, at 1680x1050: I can start a new game and run around the first level, didn't test further.
Performance isn't that great though (10-15fps I think?)
