### ISSUE TITLE
dhewm3ded.exe is encountering errors when executed (edit: false error, I was just being dumb)

### ISSUE THREAD

**Issue by AEther-AEternum** [dhewm/dhewm3#423]
I think it might be loading the wrong pk4s from the wrong directory, idk. Here's the error log:

dhewm3 1.5.1.1305 windows-x86 Mar 14 2021 04:02:49 using SDL v2.0.14
8096 MB System Memory
Winsock Initialized
Found interface: {BA2B525D-7E83-485A-AAAD-FDB6C9491723} Realtek PCIe GbE Family Controller - 192.168.100.67/255.255.255.0
Sys_InitNetworking: adding loopback interface
doom using MMX & SSE & SSE2 & SSE3 for SIMD processing
enabling Flush-To-Zero mode
enabling Denormals-Are-Zero mode
WARNING: using path of executable: D:/Program Files/Doom 3
----- Initializing File System -----
Loaded pk4 D:\Program Files\Doom 3\base\pak000.pk4 with checksum 0x28d208f1
Loaded pk4 D:\Program Files\Doom 3\base\pak001.pk4 with checksum 0x40244be0
Loaded pk4 D:\Program Files\Doom 3\base\pak002.pk4 with checksum 0xc51ecdcd
Loaded pk4 D:\Program Files\Doom 3\base\pak003.pk4 with checksum 0xcd79d028
Loaded pk4 D:\Program Files\Doom 3\base\pak004.pk4 with checksum 0x765e4f8b
Loaded pk4 D:\Program Files\Doom 3\base\pak005.pk4 with checksum 0x8ffc3621
Loaded pk4 D:\Program Files\Doom 3\base\pak006.pk4 with checksum 0x95b65ab
Loaded pk4 D:\Program Files\Doom 3\base\pak007.pk4 with checksum 0x666bdb3c
Loaded pk4 D:\Program Files\Doom 3\base\pak008.pk4 with checksum 0x23ae5993
Current search path:
C:/Users/Spectre/Documents/My Games/dhewm3/base
D:/Program Files/Doom 3/base
D:\Program Files\Doom 3\base\pak008.pk4 (3 files)
D:\Program Files\Doom 3\base\pak007.pk4 (38 files)
D:\Program Files\Doom 3\base\pak006.pk4 (48 files)
D:\Program Files\Doom 3\base\pak005.pk4 (63 files)
D:\Program Files\Doom 3\base\pak004.pk4 (5137 files)
D:\Program Files\Doom 3\base\pak003.pk4 (4676 files)
D:\Program Files\Doom 3\base\pak002.pk4 (6120 files)
D:\Program Files\Doom 3\base\pak001.pk4 (8972 files)
D:\Program Files\Doom 3\base\pak000.pk4 (2698 files)
Addon pk4s:
----- Initializing Decls -----
5206 strings read from strings/english.lang
Couldn't open journal files
execing editor.cfg
execing default.cfg
execing dhewm.cfg
execing autoexec.cfg
5206 strings read from strings/english.lang
----- Initializing OpenAL -----
Sound disabled with s_noSound 1 !
loaded game library 'D:/Program Files/Doom 3/base.dll'.
game using MMX & SSE & SSE2 & SSE3 for SIMD processing
Flush-To-Zero mode is already enabled
Denormals-Are-Zero mode is already enabled
----- Initializing Game -----
gamename: baseDOOM-1
gamedate: Mar 14 2021
Initializing event system
...473 event definitions
Initializing class hierarchy
...142 classes, 191092 bytes for event callbacks
Initializing scripts
Compiled 'interpolateShaderParm': 595 ms
----- Compile stats -----
Memory usage:
     Strings: 79, 9648 bytes
  Statements: 67875, 1357500 bytes
   Functions: 2109, 250532 bytes
   Variables: 147376 bytes
    Mem used: 2576440 bytes
 Static data: 2477552 bytes
   Allocated: 3481696 bytes
 Thread size: 13212 bytes
...6 aas types
----- Initializing Session -----
----- Warnings -----
during dhewm 3 initialization...
WARNING: using path of executable: D:/Program Files/Doom 3
1 warnings

Type 'help' for dedicated server info.

**Comment by AEther-AEternum** [comment]
Any help?

**Comment by DanielGibson** [comment]
I don't see any errors there, the loaded .pk4s look correct

**Comment by AEther-AEternum** [comment]
> 
> 
> I don't see any errors there, the loaded .pk4s look correct

Really? My game isn't launching though. I just have a blue error log window open. I'm trying to launch Resurrection of Evil btw.
I got it to work though, by launching the default exe for the main game with "+set fs_game d3xp"

**Comment by DanielGibson** [comment]
What exactly are you expecting to happen?

dhewm3ded.exe is the dedicated server, you're seeing its console.

To actually play the game use dhewm3.exe

**Comment by AEther-AEternum** [comment]
Wait a damn minute, for some reason I remember using that .exe to launch the Resurrection of Evil dlc in an older version of dhewm3. What is happening to my memory?
Anyway, I didn't know that, my bad. I is has stupid. :)
