### ISSUE TITLE
macOS version, notarized and Apple Silicon native

### ISSUE THREAD

**Issue by ikir83** [dhewm/dhewm3#430]
Hello, not a bug itself.

Just want to say to add to FAQ/readme/website macOS already compiled, notarised and update version. Also updated for Apple Silicon compatibility:

https://macsourceports.com

dhewm3 runs great 👍

**Comment by DanielGibson** [comment]
Thanks for the heads-up, I guess I should finally update the homepage

**Comment by DanielGibson** [comment]
I finally added a link: https://dhewm3.org/#getting-dhewm3-executables
