### ISSUE TITLE
Let player to override anti-root check

### ISSUE THREAD

**Issue by tyabus** [dhewm/dhewm3#431]
For example, imagine if somebody managed to build dhewm3 for very specific architecture that is really really hard to buils for (old old gcc or loss of build tools after the build), why not just add cmdline parameter (for example: -allowroot), to let user to run the game, maybe we can add some kind of warning and put sleep after to let user to think about possible risks.

**Comment by DanielGibson** [comment]
why would a specific/weird architecture require running the game as root?

**Comment by tyabus** [comment]
> why would a specific/weird architecture require running the game as root?

i've ran a few dedicated servers on mipsbe (yes, on a router lol) which didnt had openwrt firmware support, so you cant add any users, maybe we can implement it like in srcds, print warning about running as root and wait for 10 seconds for user to take action. (maybe exiting by default, 10 sec wait with cmdline parameter)

(yes, i'm that kind of guy that runs stuff on crappy&weird mips/arm/etc SoCs)

**Comment by DanielGibson** [comment]
are those things fast enough for doom3's dedicated server? (genuinely curios)

**Comment by tyabus** [comment]
> are those things fast enough for doom3's dedicated server? (genuinely curios)

i've ran quake 3 dedicated server on a tp-link, dhewm3 had too many errors during the compilation

**Comment by DanielGibson** [comment]
I think doom3 needs more power, that's why I'd be surprised if it ran on that kind of hardware

(it'll certainly run on a Raspberry Pi or such, but there you'll have a non-root user)

I'll think about adding this, but OTOH why care as long as no one actually runs into that problem..

**Comment by tyabus** [comment]
> I think doom3 needs more power, that's why I'd be surprised if it ran on that kind of hardware
> 
> (it'll certainly run on a Raspberry Pi or such, but there you'll have a non-root user)
> 
> I'll think about adding this, but OTOH why care as long as no one actually runs into that problem..

Feel free to close if you want, i'll try to cross-compile dhewm3ded as soon as i get home.

**Comment by turol** [comment]
No, if someone wants this they can remove the code themselves. And if you're running on a platform which only has root you probably need to compile from sources anyway.
