### ISSUE TITLE
Add different cmake arguments for Apple Silicon macs

### ISSUE THREAD

**Issue by rullinoiz** [dhewm/dhewm3#433]
Because of the deprecation of the `/usr/local/` directory, homebrew changed the install directory to `/opt/homebrew/` , leading to a whole lot compilation errors on other cmake and clang/gcc projects if you don't add the environment variable `SDKROOT=$(xcrun --show-sdk-path)`.

These new arguments for cmake account for homebrew's new installation path and work for Apple Silicon macs, and should allow M1 users utilize native arm64 binaries:
```cmake -DOPENAL_LIBRARY="/opt/homebrew/opt/openal-soft/lib/libopenal.dylib" -DOPENAL_INCLUDE_DIR="/opt/homebrew/opt/openal-soft/include" /path/to/repo/neo```

**Comment by DanielGibson** [comment]
I added this information to the README, thanks for letting me know!
