### ISSUE TITLE
Dedicated Server is always Pure

### ISSUE THREAD

**Issue by Ionwerks** [dhewm/dhewm3#437]
I'm honestly not sure if this is a bug or something I don't understand about D3. However I set si_pure 0 on the dedicated server, whether on the command line;

`DHEWM3DED.EXE +set si_pure 0 +set net_LANServer 1 +spawnserver`

or with the same settings embedded in a config;

```
start DHEWM3DED.EXE +exec "server.cfg"
	startserver

```
or just using the built in console;

```
start DHEWM3DED.EXE 
	set si_pure 0
	startserver
```

My client is always rejected with; _Data not in sync with server data._ (#str_04842)

In each case I can read back si_pure as actually being 0 via the console;

```
]si_pure
"si_pure" is:"0" default:"1"
server is pure and does not allow modified data
```

Obviously a non-pure server is a bad idea but right now I'm just trying to ascertain if it's possible to connect the Dhewm3 based Oculus Quest client (Doom3Quest) to a multiplayer server to work out how much it would take to get MP functioning properly. This apparent need to have completely matched server and client data right from the start is proving an early blocker.

**Comment by DanielGibson** [comment]
does it behave differently if you start the server in non-dedicated dhewm3.exe?

**Comment by DanielGibson** [comment]
The message you're seeing is explicitly for non-pure servers (otherwise you'd have a "(pure server)") at the end of the message.
It's from https://github.com/dhewm/dhewm3/blob/00b58d1f0fb63860cb956b8963ebe957740d1e5d/neo/framework/async/AsyncServer.cpp#L1686-L1690

I don't know what exactly it checks there, but apparently at least some data must be identical on client and server.

Why is having matching data an early blocker? Can't you just use the same game data on both machines?

**Comment by Ionwerks** [comment]
Hey, thanks for responding so quickly. Just tried with a listen server but same result.

The VR version has a highly non-standard player setup, extra bones and event handlers and, given the same data, the server dies with a script error.

**Comment by Ionwerks** [comment]
As you say the issue isn't that it's not pure (I'd missed that !) but something else that needs to match, I guess I'll have to work out what needs to be the same both ends.

**Comment by DanielGibson** [comment]
you can certainly just comment the check out for testing, at worst it crashes later..

**Comment by Ionwerks** [comment]
Roger, closing.
