### ISSUE TITLE
[macos] error via compile

### ISSUE THREAD

**Issue by xmansch** [dhewm/dhewm3#438]
/Users/mansch/Downloads/Doom/dhewm3/neo/sys/osx/DOOMController.mm:199:2: error: use of undeclared identifier 'use_idStr_snPrintf'
        snprintf(save_path, sizeof(save_path), "%s/Library/Application Support/dhewm3", [NSHomeDirectory() cString]);

**Comment by xmansch** [comment]
> Thanks for reporting!
> Just pushed a fix, can you try if it builds now?

just work !  thanks

**Comment by DanielGibson** [comment]
great, thanks!
