### ISSUE TITLE
[Linux] After adding fullscrean and 16x antialiasing game exec lods quickly then stops

### ISSUE THREAD

**Issue by hayguneys** [dhewm/dhewm3#440]
Hello everyone, was playing doom 3 on my Arch Linux setup here and after playing for a few hours with just the fullscreen option and 1080p resolution I turned AA up to 16x and now the game wont run at all, I ran the program through the terminal so I could see what was happening on the specifics. I'm using the steam version files, so everything is updated on the latest version and i'm on a Rx580 from AMD. Below is the output from the terminal:
```
Loaded pk4 /home/dumia/.var/app/org.dhewm3.Dhewm3/data/dhewm3/base/pak000.pk4 with checksum 0x28d208f1
Loaded pk4 /home/dumia/.var/app/org.dhewm3.Dhewm3/data/dhewm3/base/pak001.pk4 with checksum 0x40244be0
Loaded pk4 /home/dumia/.var/app/org.dhewm3.Dhewm3/data/dhewm3/base/pak002.pk4 with checksum 0xc51ecdcd
Loaded pk4 /home/dumia/.var/app/org.dhewm3.Dhewm3/data/dhewm3/base/pak003.pk4 with checksum 0xcd79d028
Loaded pk4 /home/dumia/.var/app/org.dhewm3.Dhewm3/data/dhewm3/base/pak004.pk4 with checksum 0x765e4f8b
Loaded pk4 /home/dumia/.var/app/org.dhewm3.Dhewm3/data/dhewm3/base/pak005.pk4 with checksum 0x8ffc3621
Loaded pk4 /home/dumia/.var/app/org.dhewm3.Dhewm3/data/dhewm3/base/pak006.pk4 with checksum 0x95b65ab
Loaded pk4 /home/dumia/.var/app/org.dhewm3.Dhewm3/data/dhewm3/base/pak007.pk4 with checksum 0x666bdb3c
Loaded pk4 /home/dumia/.var/app/org.dhewm3.Dhewm3/data/dhewm3/base/pak008.pk4 with checksum 0x23ae5993
Current search path:
/home/dumia/.var/app/org.dhewm3.Dhewm3/config/dhewm3/base
/home/dumia/.var/app/org.dhewm3.Dhewm3/data/dhewm3/base
/home/dumia/.var/app/org.dhewm3.Dhewm3/data/dhewm3/base/pak008.pk4 (3 files)
/home/dumia/.var/app/org.dhewm3.Dhewm3/data/dhewm3/base/pak007.pk4 (38 files)
/home/dumia/.var/app/org.dhewm3.Dhewm3/data/dhewm3/base/pak006.pk4 (48 files)
/home/dumia/.var/app/org.dhewm3.Dhewm3/data/dhewm3/base/pak005.pk4 (63 files)
/home/dumia/.var/app/org.dhewm3.Dhewm3/data/dhewm3/base/pak004.pk4 (5137 files)
/home/dumia/.var/app/org.dhewm3.Dhewm3/data/dhewm3/base/pak003.pk4 (4676 files)
/home/dumia/.var/app/org.dhewm3.Dhewm3/data/dhewm3/base/pak002.pk4 (6120 files)
/home/dumia/.var/app/org.dhewm3.Dhewm3/data/dhewm3/base/pak001.pk4 (8972 files)
/home/dumia/.var/app/org.dhewm3.Dhewm3/data/dhewm3/base/pak000.pk4 (2698 files)
/app/share/dhewm3/base
Addon pk4s:
----- Initializing Decls -----
5206 strings read from strings/english.lang
Couldn't open journal files
execing editor.cfg
execing default.cfg
execing dhewm.cfg
couldn't exec autoexec.cfg
5206 strings read from strings/english.lang
----- Initializing OpenAL -----
Setup OpenAL device and context
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
OpenAL: found device 'Ellesmere HDMI Audio [Radeon RX 470/480 / 570/580/590] Digital Stereo (HDMI 4)'
OpenAL: found device 'EasyEffects Sink'
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
OpenAL vendor: OpenAL Community
OpenAL renderer: OpenAL Soft
OpenAL version: 1.1 ALSOFT 1.21.1
OpenAL: found extensions for resetting disconnected devices
OpenAL: found EFX extension
OpenAL: found 256 hardware voices
----- Initializing OpenGL -----
Initializing OpenGL subsystem
```

**Comment by DanielGibson** [comment]
The AMD open source driver (maybe even all Mesa drivers?) only support up to 8x AA.

Sucks that the game seems to hang though - but that might be a bug I've fixed after the last release (https://github.com/dhewm/dhewm3/commit/52ea5b3877d676f3a9b1efa3985fd1664e6bb535) - I hope I'll get around to do another release soon-ish, but there's still a few bugs I wanted to fix first..
In the meantime I recommend building the latest git code.

Currently the game switches to 640x480 in that case, which is also unfortunate, I'll try to remember to first try to switch to a lower AA level before going back to 640x480.

**Comment by hayguneys** [comment]
Ok then, I went to the cfg file and reverted to a safe AA level, thanks for the response, maybe I'll check the proprietary driver to see if it works any different. I downloaded the engine from the flatpack, so maybe if I build from source I'll get the fix you are talking about. 

Thanks again for the support!

**Comment by DanielGibson** [comment]
The open source drivers AMD generally work better, esp. for games, I'd recommend to keep using them.
IMO the visual difference between 8x MSAA and 16x MSAA isn't that noticeable

**Comment by DanielGibson** [comment]
You could toy around with EQAA though, which can be enabled/configured with a Linux environment variable, see https://www.phoronix.com/scan.php?page=news_item&px=RadeonSI-EQAA-Mesa-18.2
and also this description: https://gitlab.freedesktop.org/mesa/mesa/-/blob/mesa-21.3.4/src/gallium/drivers/radeonsi/si_state.c#L3551-3591
