### ISSUE TITLE
Doesn't go to full screen in FreeBSD DRM driver

### ISSUE THREAD

**Issue by r9guy** [dhewm/dhewm3#449]
Tested the FreeBSD port.
On FreeBSD 13.0
Xorg server, using Intel drm-kmod driver.
With optional [x11-drivers/xf86-video-intel](https://www.freshports.org/x11-drivers/xf86-video-intel/).
Game start and runs well, however it is not able to switch to full screen.

**Comment by Yamagi** [comment]
I'm unable to reproduce it on FreeBSD 13.0 with drm-fbsd13-kmod 5.4.144.g20220223, and SDL 2.0.20_1. Regardless if I use the generic "modesetting" or the "intel" ddx driver, dhewm3 master switches to fullscreen just fine. Both into the native resolution and several smaller resolutions. This is a rather old Ivy Bridge GPU, though.

**Comment by r9guy** [comment]
@Yamagi  the driver I use is drm-kmod, is your driver ddx relevant? how can I try with ddx?
