### ISSUE TITLE
Linux is only 64bit while Windows can also be 32bit, right?

### ISSUE THREAD

**Issue by vorob1** [dhewm/dhewm3#450]
I'm experimenting with old laptop that has only core duo processor, it's not 64bit thing. But i wanna play doom :)

I saw dhewm3 in some package managers, but currently i'm on Debian and looks like it doesn't have such repositatium and on github only 64bit available...

**Comment by DanielGibson** [comment]
Wrong, dhewm3 also supports 32bit on Linux.
You can compile it yourself or use the `dhewm3-doom3` package from debians own repo.

**Comment by vorob1** [comment]
Thanks!
