### ISSUE TITLE
MacOS Monterey: couldn't load mod-specific d3xp.dylib (Resurrection of Evil)

### ISSUE THREAD

**Issue by mkrupczak3** [dhewm/dhewm3#452]
# Description

When trying to run Resurrection of Evil (`d3xp`) using the [signed build from macsourceports.com](https://macsourceports.com/) the following appears:

`WARNING: couldn't load mod-specific d3xp.dylib. defaulting to base game's library!`

...

`ERROR: Function 'map_erebus1::main' not found in script for 'call' key on worldspawn`

# Cause

The likely root cause of this issue is that d3xp.dylib is missing from the provided binary

On Ubuntu Linux this missing library can be obtained by installing the `dhewm3-d3xp` package, but no such equivalent is available on MacOS

[Previous discussion](https://github.com/dhewm/dhewm3/issues/334#issuecomment-735498093) in issue #334 suggests that this library can only be obtained by compiling from source, an operation which is technically prohibitive for most normal users

# Fix

`d3xp.dylib` should be included by default with Mac binaries of this source port. Users of other platforms (such as Linux) may benefit from the inclusion of this library as well

**Comment by DanielGibson** [comment]
The binaries you're using are built by the Mac Source Ports maintainer, I can't do anything about them missing a lib.
The proper place to report this probably is https://github.com/MacSourcePorts/dhewm3

**Comment by mkrupczak3** [comment]
Thanks for taking a look, I'll file an issue there

**Comment by DanielGibson** [comment]
Thanks!
