### ISSUE TITLE
Does not capture mouse on Linux Mint

### ISSUE THREAD

**Issue by KingNullpointer** [dhewm/dhewm3#454]
The game window will not properly capture the mouse in either fullscreen or windowed - in fullscreen, it will lag momentarily whenever the mouse leaves the window. The system mouse is visible during loading screens.

I have 2 monitors, which makes this a major problem - I effectively cannot turn too far right without un-focusing the game window.

I checked my compatibility, mouse, & window settings; nothing there seems to be the problem.

System Specs:
System:    Host: KingNull-Desktop-Linux Kernel: 5.4.0-109-generic x86_64 bits: 64 
           Desktop: Cinnamon 5.2.7 Distro: Linux Mint 20.3 Una 
CPU:       Topology: 8-Core model: AMD Ryzen 7 3700X bits: 64 type: MT MCP L2 cache: 4096 KiB 
           Speed: 2197 MHz min/max: 2200/3600 MHz Core speeds (MHz): 1: 2196 2: 2195 3: 2254 
           4: 2196 5: 2195 6: 2195 7: 2196 8: 2191 9: 2473 10: 2196 11: 2195 12: 2196 13: 2196 
           14: 2195 15: 2194 16: 2190 
Graphics:  Device-1: AMD Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT] driver: amdgpu 
           v: kernel 
           Display: x11 server: X.Org 1.20.13 driver: amdgpu,ati 
           unloaded: fbdev,modesetting,radeon,vesa resolution: 1920x1080~60Hz 
           OpenGL: 
           renderer: AMD Radeon RX 5700 XT (navi10 LLVM 14.0.1 DRM 3.35 5.4.0-109-generic) 
           v: 4.6 Mesa 22.0.3 - kisak-mesa PPA

**Comment by DanielGibson** [comment]
Which version of dhewm3 are you using? Can you try building from latest git source and see if that works better?
What's the SDL2 version on your system? (A newer version might be worth a try)

Did you change any cvars in the Doom3 console or configs? Make sure `in_nograb` is `0` (that's the default)

**Comment by KingNullpointer** [comment]
I build dhewm3 from the most recent push to the master. Tried pulling, was up to date. Ran 'make clean' & 'make', problem persists.

My libsdl2-2.0-0 & libsdl-2.0-0 package is version 2.0.10+dfsg1-3. libsdl-2.0-0 has the i386 architecture also installed, could that be causing problems? 

No, & the problem persists after setting cvars in $/.config/dhewm3/base/dhewm3.cfg 'seta in_nograb "0"' or in game via console

**Comment by DanielGibson** [comment]
Having SDL2 also installed for i386 shouldn't make a difference.
2.0.10 is pretty old though, it's possible that whatever causes your issue has been fixed since.
Could you try building SDL 2.0.22 (latest release) yourself and see if it makes a difference?
It shouldn't be too hard, from memory something like the following should work (after unpacking the source):
```
sudo apt build-dep libsdl2-2.0-0
cd /path/to/sdl2-source
mkdir mybuild
cd mybuild
../configure --prefix=/tmp/sdl2/
# if that run successfully
make -j8
# if that ran successfully
make install
```

Afterwards running dhewm3 with `LD_LIBRARY_PATH=/tmp/sdl2/lib/ ./dhewm3` should make it use the SDL2 version you just compiled. dhewm3 prints the SDL2 version to the terminal.

**Comment by KingNullpointer** [comment]
So version dhewm3 is using appears to be SDL v2.0.21, & apt can't find a source package for libsdl2

**Comment by DanielGibson** [comment]
> So version dhewm3 is using appears to be SDL v2.0.21

Does the mouse capture problem persist with SDL 2.0.21?

> apt can't find a source package for libsdl2

source packages have extra lines in apt's sources.list (starting with `deb-src` instead of just `deb`), maybe those are missing (there probably is a setting for that in some graphical configuration tool)

**Comment by KingNullpointer** [comment]
I just downloaded SDL 2.0.22 from the SDL website & ran the game with it preloaded as a library; seems to have fixed the issue at 1st glance. Thanks for the quick response & help, sorry it took a while to get back to you
