### ISSUE TITLE
Doomedit: Light inspector not working.

### ISSUE THREAD

**Issue by Arl90** [dhewm/dhewm3#456]
While using Doomedit, selecting any type of light and opening the light inspector (j) shows only default parameters with a message in the windows header that says: "no entities selected".

![image](https://user-images.githubusercontent.com/45338446/169635851-f3d70c15-7fe3-4d99-80f6-25c3f6b52ccf.png)

**Comment by DanielGibson** [comment]
I just fixed this, can you test this build: [dhewm3-1.5.2rc1-fixed-radiant-focus.zip](https://github.com/dhewm/dhewm3/files/8794405/dhewm3-1.5.2rc1-fixed-radiant-focus.zip) ?

Thanks :)

**Comment by DanielGibson** [comment]
(uploaded the wrong file first, the correct one is [dhewm3_1.5.2rc2%2Blighteditor-fix.zip](https://github.com/dhewm/dhewm3/files/8794407/dhewm3_1.5.2rc2%2Blighteditor-fix.zip))
