### ISSUE TITLE
Planning to play DHEWM3 with Bravo mod

### ISSUE THREAD

**Issue by Dredd893** [dhewm/dhewm3#457]
https://www.moddb.com/mods/doom-3-bravo-v3

1) By the way, when I play with 1920x1080 the guy is centered on the screen. Did I miss any 16:9 setting I should be aware of ?

Edit: you added the torch on weapons. Any way to revert that?

**Comment by hemebond** [comment]
> Edit: you added the torch on weapons. Any way to revert that?
That's a part of the mod, nothing to do with the engine.

**Comment by Dredd893** [comment]
I noticed it later. I apologize for not commenting fast enough to not waste your time.

**Comment by DanielGibson** [comment]
> when I play with 1920x1080 the guy is centered on the screen. 

This is a feature. The Doom3 GUIs are made for 4:3, at least for fullscreen GUIs there's not much I can do about it - except for centering them.
Alternatively, if you prefer them to be stretched to your display resolution, you can set `r_scaleMenusTo43 0` in the console - but then they look a bit distorted.

**Comment by Dredd893** [comment]
I want to leave a review for this mod. Thanks to all the people that have poured work into this and keep supporting it. Thanks to you, I don't have to play the new Doom 3 and I can enjoy mods. I cannot play Doom 3 without this mod, and you make it functional. Thanks a lot!

Hope you all get a great weekend.

**Comment by DanielGibson** [comment]
Thank you for the praise! :)

> there is only one flaw, I must admit. In the readme, all the stuff about compiling and so on is pretty confusing, considering that all I had to do was just drag and drop the archive into the Doom 3 folder to use the mod. (Basically I would put the technical things in a technical readme and I would put the "what to do" in the main readme - but that's just me).

I get what you mean. The README is taken from the source code repo, and there it makes sense just the way it is.
But for releases I should probably copy the "end user" install instructions from https://dhewm3.org/#how-to-install into the READMEs distributed with the win32 and Linux binary archives and remove the compiling instructions (which are irrelevant for binary releases).

**Comment by DanielGibson** [comment]
@Dredd893 this is what the README could look like for the final 1.5.2 release, do you think it's better?
https://gist.github.com/DanielGibson/8296bd12c7a3b7453052d0eb307881d3

**Comment by Dredd893** [comment]
I have an unrelated question: been reading around about not clicking the elevator buttons in the lobby in the delta labs 1 until you restart the reactor. Was this bug taken a look at in DHewm3?

**Comment by DanielGibson** [comment]
Never heard about that bug, do you have details?

**Comment by Dredd893** [comment]
https://www.google.com/search?q=reactor+bug+doom+3&oq=reactor+bug+doom+3&aqs=chrome..69i57.1850j0j1&sourceid=chrome&ie=UTF-8

A synthesis of the bug: If you press the button on the main elevator before you have turned on the reactor, it will permanently register as having low power, even when the reactor is turned on. You can't exit the level and will possibly have to restart the entire game if you have not been making multiple saves.
