### ISSUE TITLE
dhewm3 1.5.2rc1 segfaults when loading Resurrection of Evil

### ISSUE THREAD

**Issue by amak79** [dhewm/dhewm3#458]
I have dhewm3 1.5.2rc1 installed via Flatpak. When I attempt to load Resurrection of Evil via the main menu (Mods->d3xp->Load Mod) I get a segfault. This doesn't occur with 1.5.1. However, I can run Resurrection of Evil directly with `flatpak run org.dhewm3.Dhewm3 +set fs_game d3xp`.

[dhewm3-1.5.2rc1.log](https://github.com/dhewm/dhewm3/files/8752116/dhewm3-1.5.2rc1.log)

**Comment by DanielGibson** [comment]
I just pushed a fix for this, can you test if it works for you?

**Comment by amak79** [comment]
I'll need to ping the Flatpak maintainer to push a new test build. I'll report back once I test it.

**Comment by amak79** [comment]
I can confirm that the fix works. Thank you very much.

I was also going to mention the Lost Mission loading issue but you have already explained why it doesn't work over in the Flatpak mod support issue.
