### ISSUE TITLE
Game steals back mouse cursor after a few seconds

### ISSUE THREAD

**Issue by Xbox-360-1063** [dhewm/dhewm3#459]
I have two monitors. When I tab out I can only use the monitor the game isn't on, but it steals my cursor back to the screen the game is on after a couple of seconds.

**Comment by DanielGibson** [comment]
And which version are you using (try 1.5.2 RC1)

**Comment by Xbox-360-1063** [comment]
It seems that using 1.5.2 RC1 fixes the cursor issue as well as letting me use both monitors when I tab out

**Comment by DanielGibson** [comment]
Great, glad I already fixed the bug =)
