### ISSUE TITLE
Crashes when exiting mars city

### ISSUE THREAD

**Issue by Xbox-360-1063** [dhewm/dhewm3#460]
Sorry for another issue, but now it seems (while running 1.5.2 RC1 on windows in fullscreen) that the game crashes when loading the level administration. I have attached the dhewm3log.txt as well as a link to a crash dump. please let me know if I'm needed to provide more info
https://totally-real-and-online-site.com/download/738e1759f5d57270/#9pV5S5e9i19BSDiY19DYSQ
[dhewm3log.txt](https://github.com/dhewm/dhewm3/files/8775425/dhewm3log.txt)

**Comment by DanielGibson** [comment]
Weird, the log only mentions game/mars_city2, not admin?
Does the crash go away if you remove pak009.pk4? Do you have a download link for that pak?

**Comment by Xbox-360-1063** [comment]
The crash doesn't go away if I remove the file and here is a link to it
https://gamebanana.com/sounds/download/352
(it comes as pack004.pk4 or something but says to rename it to a number that isn't taken

**Comment by DanielGibson** [comment]
This seems to be a SDL2-bug, introduced in SDL 2.0.22.
Can you verify that the following SDL2.dll works better (and that your Alt-Tab issue you reported before is still fixed with it): [sdl2_0_20.zip](https://github.com/dhewm/dhewm3/files/8776049/sdl2_0_20.zip)

Thanks!

**Comment by Xbox-360-1063** [comment]
The SDL2 dll you sent me seems to have resolved the issue and alt tabbing still works well, thank you

**Comment by DanielGibson** [comment]
great, I'll just ship 1.5.2 for windows with SDL 2.0.20 then
