### ISSUE TITLE
Typing in text boxes and console doesn't work in KDE Wayland, but works with Xwayland

### ISSUE THREAD

**Issue by pizzadude** [dhewm/dhewm3#464]
Typing in text boxes (such as naming a save) doesn't work in KDE wayland. If I instead use Xwayland, it works. Tested with the Dhewm3 flatpak. However, gameplay input works fine in native wayland, just not typing in text boxes (and console).

This is on Fedora 36 KDE.

**Comment by DanielGibson** [comment]
Strange, sounds like SDL_TEXTINPUT events don't work, for whatever reason.

**Comment by Eonfge** [comment]
@DanielGibson Should I revert the Wayland support for the Flatpak? This afternoon I'll have the time to reproduce it but I can already prepare a pull-request so that Flathub users will be switched back to XWayland (X11 layer on Wayland)

**Comment by Eonfge** [comment]
Can confirm the issue on Fedora 36. I did get an interesting message in the console

```
in_grabKeyboard: Will *not* grab the keyboard if mouse is grabbed, so global keyboard-shortcuts (like Alt-Tab) will still work
```

Not sure if that's from SDL or from Dhewm 3

**Comment by DanielGibson** [comment]
That message is harmless, it just means that you can set the `in_grabKeyboard` cvar to `1` to make sure dhewm3 gets *all* keyboard input, and the Win-Key or Alt-Tab doesn't throw you out of the game.

Can you type in the console, or is that also broken?

Did you also test a "normal" dhewm3 build (without flatpak)?
Might be worth trying a custom built libsdl2, maybe fedora added a broken patch or something?

**Comment by Eonfge** [comment]
> Can you type in the console, or is that also broken?

The console also doesn't respond.

> Did you also test a "normal" dhewm3 build (without flatpak)?

No, I tested this on Fedora 36 with the Flatpak. I'll change my previous comment to avoid confusion

> Might be worth trying a custom built libsdl2, maybe fedora added a broken patch or something?

Flathub has SDL 2.0.16;
https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/blob/release/21.08/elements/components/sdl2.bst

**Comment by DanielGibson** [comment]
The current version is 2.0.22, and there were lots of Wayland fixes in the last few versions.
You should try to update it

**Comment by Eonfge** [comment]
Can confirm. I just made a local build of the flathub package using sdl 2.0.22 and it works. I'll get started on a patch and I'll likely get it fixed in an hour or two.

**Comment by Eonfge** [comment]
Fixed it downstream. Flatpak should now come with 2.0.22. 

Nice example of how Fl;atpak combines both the greatest of traditional package management and stand-alone binaries.
