### ISSUE TITLE
Linux - Keyboard auto detection always anounce English even when the keyboard isn't, ingame the keyboard works fine diferent of what gets anounced

### ISSUE THREAD

**Issue by BielBdeLuna** [dhewm/dhewm3#467]
keyboard is announced as Detected keyboard layout as "english", I have in_kbd = "auto" and I have a Spanish keyboard that it works properly, because in the console both the ñ and ç keys do work as intended for the Spanish keyboard.
So it's odd that it gets to be detected as English.

**Comment by DanielGibson** [comment]
The language detection really only is about what char is on the "console key" (between Esc, Tab and 1, `SDL_SCANCODE_GRAVE`).
However, it's still surprising that it's detected as English - what char do you get if you press that key (without shift)? I think it should be `º`, but it seems like `SDL_GetKeyFromScancode( SDL_SCANCODE_GRAVE )` returns <code>`</code> instead (which dhewm3 will detect as English)?

**Comment by BielBdeLuna** [comment]
in the linux console I get: `º`, in Dhewm3 it opens and closes the console without any problem.

**Comment by BielBdeLuna** [comment]
Building the last libSDL2 from their git solved this issue
