### ISSUE TITLE
sound stutters after a few minutes

### ISSUE THREAD

**Issue by mdvhimself** [dhewm/dhewm3#474]
happens in base vanilla doom3, but happens in classic doom and some custom map ive just uploaded. ive tried disabling eax, but doesnt help. quicksaving and loading back the save right after solves the problem. not sure whats happening.

https://youtu.be/2dLR2id8iEY

**Comment by mdvhimself** [comment]
all 3 cases. starts around 24 mins, easy to hear when im shooting the plasmagun. becomes insane by the time i get to the small bossfight versus 2 mancubus around 27 mins. 
map can be downloaded here, should be totally vanilla compatible https://www.moddb.com/games/doom-iii/addons/evacuation-protocol-doom-3

ive tried without the texturepack, same thing happens. ive even tried resetting the config by deleting the configs in the user documents folder. the only thing ive achived is that i can no longer type zero cause im on iso layout...

if i get home im gonna try running the thing on one core, it helped with sikkmod the other week.

**Comment by mdvhimself** [comment]
nevermind...my soundcard was overheating. works perfectly now.

**Comment by DanielGibson** [comment]
Wow, I think this is the first time I've heard of a soundcard overheating :)
