### ISSUE TITLE
MacOS build: You can’t open the application “dhewm3.app” because it may be damaged or incomplete.

### ISSUE THREAD

**Issue by username1290** [dhewm/dhewm3#475]
Hi, tried to build it using CMake 3.23.2, but the built app is not working.
Running macOS Monterey

Terminal output:

`CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- `/Library/Developer/CommandLineTools/usr/bin/cc -dumpmachine` says: "x86_64-apple-darwin21.6.0"
--   => CPU architecture extracted from that: "x86_64"
-- Setting -DD3_ARCH="x86_64" -DD3_SIZEOFPTR=8 -DD3_OSTYPE="macosx" 
-- libcurl found and enabled
CMake Warning at CMakeLists.txt:250 (message):
  libbacktrace wasn't found.  It's not required but recommended, because it
  provides useful backtraces if dhewm3 crashes

-- Building RelWithDebInfo for macosx-x86_64
-- Configuring done
CMake Warning (dev):
  Policy CMP0068 is not set: RPATH settings on macOS do not affect
  install_name.  Run "cmake --help-policy CMP0068" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.

  For compatibility with older versions of CMake, the install_name fields for
  the following targets are still affected by RPATH settings:

   base
   d3xp

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /Users/username/Downloads/dhewm3-1.5.2`

**Comment by DanielGibson** [comment]
Citing the Readme:

> Newer versions of Homebrew install openal-soft to another directory, so use this instead:
>
> `cmake -DOPENAL_LIBRARY="/opt/homebrew/opt/openal-soft/lib/libopenal.dylib" -DOPENAL_INCLUDE_DIR="/opt/homebrew/opt/openal-soft/include" /path/to/repo/neo`

**Comment by username1290** [comment]
Thanks, getting there! 
No longer getting the openal error message.

Now it built an dhewm3.app with an icon, 
but exits as soon as I click it.

When I click it, it stays for about 1-2 seconds in the Dock, but then closes without any message.

**Comment by DanielGibson** [comment]
It probably can't find the game data

**Comment by username1290** [comment]
Is there a pre compiled app available for download? To see if I'm doing something different.

As a test, downloaded the Windows binaries, and it worked using Crossover
the one that worked is the one called `dhewm3_notools.exe`

**Comment by DanielGibson** [comment]
https://macsourceports.com/game/doom3, as mentioned on https://dhewm3.org/#getting-dhewm3-executables

you should work on your reading comprehension.

**Comment by username1290** [comment]
Many thanks

**Comment by DanielGibson** [comment]
good luck, have fun with the game!
