### ISSUE TITLE
Windows compilation error

### ISSUE THREAD

**Issue by TarcioV** [dhewm/dhewm3#480]
OS: Windows 10 x64
Using Visual Studio 2017 Target x64
cmake command contains DHEWM3LIBS pointing to 'dhewm3-libs/x86_64-w64-mingw32'

getting this error:
Error	LNK1104	cannot open file 'libz.dll.a.lib'	dhewm3	C:\Users\username\dhewm3-build\LINK	1

**Comment by DanielGibson** [comment]
it should be using `zlib1.lib`, I think. No idea why it doesn't, pretty sure I had both x64 and (32bit) Win32 working with VS2017 (and dhewm3-libs)

**Comment by TarcioV** [comment]
Never mind, I successful build and run using Visual Studio 2017, I had have make a mistake the first time.
