### ISSUE TITLE
Tram in Communications Transfer misbehaves

### ISSUE THREAD

**Issue by Rattle189** [dhewm/dhewm3#481]
**Video for demonstration:** https://youtu.be/9MU97-MH3_8

The tram on the electric rails found in the Communications Transfer level misbehaves where the directional controls are backwards and the front/back buttons do not work. The "Move to Station 2 - Control" button also doesn't work properly and the level cannot be progressed properly as you need to use the tram's manual control to get to the security station found along the rails.

This bug is also present in the OpenCoop mod and wasn't fixed in the unofficial 2.2 patch.

Platform: Steam
dhewm3 version: 1.52.2.1305
Map: Communications Transfer (10th level)
OS: Arch Linux x86_64
Kernel: 5.18.15-zen1-1-zen
CPU: AMD Ryzen 5 2400G
GPU: NVIDIA GeForce GTX 1070 on 515.57 drivers

**Comment by Rattle189** [comment]
This issue is only present in co-op mods like OpenCoop and Librecoop, I haven't tested it on other mods like Last Man Standing but I will also test it out soon.

**Comment by DanielGibson** [comment]
Then you should report it to the OpenCoop or LibreCoop developers - if it doesn't happen with the base game (or d3xp aka Resurrection of Evil) it's most probably not a bug in dhewm3 itself

**Comment by Rattle189** [comment]
Understood, will move the thread there. My apologies for getting confused on where to report this issue.
