### ISSUE TITLE
Linux Dhewm3 stuck on Initializing OpenGL subsystem

### ISSUE THREAD

**Issue by Jerickman** [dhewm/dhewm3#491]
Dhewm3 never goes past 'Initializing OpenGL subsystem'
Current Kisak Mesa drivers installed.
GPU: AMD ATI Radeon R9 290X/390X
OS: Linux Mint 20.3 x86_64
Kernel: 5.15.65-xanmod1

**Comment by DanielGibson** [comment]
Which version of dhewm3?
Please try 1.5.2 or latest git.
If the problem persists, please post ~/.local/share/dhewm3/dhewm3log.txt

**Comment by Jerickman** [comment]
It is 1.5.2 and no logs are generating.

**Comment by DanielGibson** [comment]
Then please run dhewm3 in a Terminal and post the output that's written there

**Comment by Jerickman** [comment]
Feel free to disregard this thread. I was looking through the terminal output and saw version 1.5.1. I had attempted overwriting the installation with the current version before (which is why I was confident on that fact) but it seems it didn't go as well as I believed. I tried again with a clean install and there were no issues. We can chalk this up to user error.
