### ISSUE TITLE
Broken lighting when running as Doom3.exe

### ISSUE THREAD

**Issue by voodoo84** [dhewm/dhewm3#492]
Not a bug per se, but it should probably be added into "known issues".

System specs:
Windows 10 64-bit, fully updated
16 GB of RAM
Radeon RX 570 with the latest stable drivers (22.5.1)
Steam version of the game

When running the game directly via dhewm3.exe, all looks normal and similar to id version.

But if I rename dhewm3.exe to Doom3.exe (because I want Steam to track my playtime) and run it via Steam, apparently the AMD graphics driver thinks it's the original id build of Doom 3 and some weird driver "optimizations" kick in, resulting in completely broken lighting and shadows (as if almost all light sources got turned off) and various other graphical glitches here and there. Turning Steam overlay on or off has no effect.

By renaming it back to dhewm3.exe (or anything else non-Doom3.exe), the problem dissapears.

**Comment by RoqueDeicide** [comment]
I'd encountered the same problem before, but was too lazy to report it. Here is what I'd figured out:
 1. Turning Steam overlay off does fix broken shadow volumes, at least on my system (R7 250X).
 2. The rest of the glitches, like windows turning into mirrors, can be fixed by turning off in-shader gamma by setting r_gammaInShader to 0.

**Comment by voodoo84** [comment]
Thanks for the suggestions, I decided to test it some more based on your input.

Firstly, to rule out Steam overlay, I tested with Steam app completely turned off. The problem with lighting and glitches remained (if running Dhewm3 as **Doom3.exe**), so I'd say it's not related to Steam overlay.

Secondly, if I disable shader-based gamma, **both problems disappear**!

Just to be clear what I'm talking about (for others who may be reading this), here are some screenshots:

**Shader-based gamma** (glitched windows and broken lighting):

![dhewm3_to_doom3_shader_gamma_1](https://user-images.githubusercontent.com/14997945/189700796-0e848c87-cd29-4605-ba33-0b41ff349605.jpg)

![dhewm3_to_doom3_shader_gamma_2](https://user-images.githubusercontent.com/14997945/189700816-44908638-6761-447a-b041-57405233e129.jpg)

**Hardware-based gamma** (r_gammaInShader = 0, no glitches and proper lighting):

![dhewm3_to_doom3_hardware_gamma_1](https://user-images.githubusercontent.com/14997945/189700843-2aef5614-3a26-464a-be8d-489c9a436a48.jpg)

![dhewm3_to_doom3_hardware_gamma_2](https://user-images.githubusercontent.com/14997945/189700860-9c3a9bce-daa5-433b-a8fb-9b3c31dcfbc3.jpg)

So while I'm at it, I also tested everything on a laptop with Windows 10, Intel 8th gen and 16 GB of RAM, but with dual graphics: Intel UHD 620 and Nvidia MX 130. I can force Windows to run specific .EXE files via one or another GPU (Nvidia tray icon indicates if Nvidia GPU is active or not), so here are the results:

dhewm3.exe, shader-based gamma, Intel: No problems
dhewm3.exe, hardware gamma, Nvidia: No problems
dhewm3.exe renamed to Doom3.exe, shader-based gamma, Intel: No problem
dhewm3.exe renamed to Doom3.exe, hardware gama, Nvidia: No problem

So it looks like it's AMD driver quirk, but luckily it's resolvable just by disabling shader-based gamma (if you really care about Steam tracking playtime via original EXE name).

**Comment by DanielGibson** [comment]
Don't run it as Doom3.exe, that will cause AMDs broken Windows drivers to apply "optimizations" that only work with Vanilla Doom3 (and only when not running custom shaders, some mods are also broken with Vanilla Doom3 when not renaming the executable).

**Comment by RoqueDeicide** [comment]
> Firstly, to rule out Steam overlay, I tested with Steam app completely turned off. The problem with lighting and glitches remained (if running Dhewm3 as **Doom3.exe**), so I'd say it's not related to Steam overlay.

Here is what I meant about broken shadow volumes with Steam Overlay:

This is with Steam Overlay on:
![shot00002](https://user-images.githubusercontent.com/8141488/189716406-99d23d6b-8a71-47db-a92d-b1ac90f49fbe.jpg)

And now with it off:
![shot00003](https://user-images.githubusercontent.com/8141488/189716583-c1b402b5-f7a3-495b-a336-976ba98fbac6.jpg)

This is why Steam Overlay should preferably be off. This might be AMD only issue as well.
