### ISSUE TITLE
Multiplayer server can't be joined by other players

### ISSUE THREAD

**Issue by babdeman** [dhewm/dhewm3#493]
When I host a server(dedicated or listen) other players aren't able to join it.
It won't appear on the server browser(internet as well as LAN) and trying to connect directly via the command line won't work either.
This problem does not occur in vanilla Doom 3.

System Specs:
Windows 10 Pro 64-bit build 19044.1889
64 GB RAM
Intel Core i7-6700K 4.00GHz
Steam Version of Doom 3

**Comment by hemebond** [comment]
dhewm3 has a different network protocol to vanilla Doom 3 and Doom 3 BFG edition. This is not a bug with dhewm3.

**Comment by DanielGibson** [comment]
correct.
