### ISSUE TITLE
flashlight doesn't work for save game

### ISSUE THREAD

**Issue by thezerobit** [dhewm/dhewm3#495]
I upgrade from 1.5.1 to 1.5.2 and the flashlight stopped working (well, it flickers a bit, maybe works 1 out of 60 frames or so) for my save game (which is attached). If I start a new game, the flashlight works fine. I am just running vanilla DOOM 3, no mods. I'm running Windows 10.
[savegames.zip](https://github.com/dhewm/dhewm3/files/9770048/savegames.zip)

**Comment by DanielGibson** [comment]
Sounds kinda like #159, is it the same bug maybe?
See especially https://github.com/dhewm/dhewm3/issues/159#issuecomment-289231371 for CVars that might be involved, did you change any of them?

**Comment by thezerobit** [comment]
I don't recall changing any CVars for any reason. The attached video of the bug does *look* the same, so it may be the same bug. However, that conclusion "I'm going to blame my changing of shadow cvars on this and say it corrupted my save file." seems more speculative than conclusive.

The bug appeared when I upgraded my dhewm3 version and loaded a save file that did not have that problem on earlier versions. When I continue to play that game, save progress and reload those saves, it persists. When I start a new game, the bug does not occur.

**Comment by DanielGibson** [comment]
I'll look at your savegame when I have some time.

Does it help to switch the flashlight off and on again, or switch to another weapon and back the the flashlight or anything like it?

**Comment by thezerobit** [comment]
No, I tried switching weapons a bunch, saving and reloading. Only starting a new game seems to fix it.

**Comment by DanielGibson** [comment]
Are you using any additional pak files besides pak000.pk4 - pak008.pk4 ?
Can you attach `Documents/My Games/dhewm3/dhewm3log.txt` (copied after loading the savegame) to a post here?

When I try to load you savegame, the game crashes

**Comment by thezerobit** [comment]
[dhewm3log.txt](https://github.com/dhewm/dhewm3/files/9845331/dhewm3log.txt)

I'm loading no extra pak files, just standard vanilla DOOM 3.

**Comment by DanielGibson** [comment]
And that log is from the same savegame you've posted above?
I'm wondering because I don't get those
```
WARNING: Couldn't load sound 'sound/ed/doors/_elevator_silver_twopaned/inner1.wav' using default
WARNING: Couldn't load sound 'guisounds.wav' using default
```
lines (and instead I get sound-related crashes)

**Comment by thezerobit** [comment]
Yes, it is the same savegame. I will try to put together a fresh download of dhewm3, with a default configuration and files copied directly from the DOOM 3 install to get to a "pure" state and see if I'm getting the same errors.

**Comment by thezerobit** [comment]
Alright, I got a fresh install of dhewm3, copied the pak files from the DOOM 3 (1.3.1) install, removed the old My Games\dhewm3 folder, copied over that saved game and ran it.
[dhewm3log.txt](https://github.com/dhewm/dhewm3/files/9845764/dhewm3log.txt)

**Comment by DanielGibson** [comment]
Ok, I found out why it crashes for me but not for you: I was using remote desktop (xfreerdp) to access my Windows machine from Linux, but didn't enable sound forwarding, so dhewm3 didn't have a soundcard, which apparently can crash when loading savegames..
For the record, my workaround is using the `/sound:sys:pulse` argument of xfreerdp.

So now I can try to investigate the flashlight problem =)

**Comment by DanielGibson** [comment]
I fixed it, here's a build for Windows that includes the fix:
[dhewm3-1.5.3pre-win32-fixedflashlight.zip](https://github.com/dhewm/dhewm3/files/9946427/dhewm3-1.5.3pre-win32-fixedflashlight.zip)

**Comment by DanielGibson** [comment]
I think the bug only happened when saving while the flashlight is on, but not every time (or at least not visibly so).
Especially when the flashlight *did* work after loading a savegame, it could have the side-effect of removing some random light in the world..

A workaround (for the flashlight-part of the problem) was to switch to the flashlight and then with the mousewheel to another weapon and back (for some reason using the flashlight key to put it away and back again didn't work).

But now it should all be fixed and work as expected.

**Comment by thezerobit** [comment]
Thanks!

**Comment by vorob1** [comment]
Just wanted to create thread about this issue, thankfully i googled before doing it and solution is already here. Funny, but i experienced same bug on original engine while was testing game on old laptop with geforce fx 5600go.

**Comment by DanielGibson** [comment]
yep, that bug must always have existed (until I fixed it)

the weird thing is that id *did* fix it for RoE, just not for the base game

**Comment by shoober420** [comment]
This is almost 100% the cause for me as well, as I did save the game with the flashlight on.
