### ISSUE TITLE
GUI editor is breaking something

### ISSUE THREAD

**Issue by erhankaradag** [dhewm/dhewm3#497]
When I open any of the gui files in the gui folder with the GUI editor, even if I don't save it, something breaks and a cursor starts to appear on the screen in gameplay.

**Comment by DanielGibson** [comment]
I don't get what you mean, when I close the GUI editor the whole games exits?
And when I start it again then, the cursor behaves as expected

**Comment by erhankaradag** [comment]
I think I was wrong. I tried again then seems ok. Sorry

**Comment by DanielGibson** [comment]
Ok no worries
