### ISSUE TITLE
Dhewm 3 utilizes onboard gpu instead of dedicated gpu

### ISSUE THREAD

**Issue by HugeTaffer** [dhewm/dhewm3#499]
I'm having really bad performance issues because of that, the game maxes out my onboard gpu capacity. Any settings I can change so I can force the game to run on my dedicated gpu?

onboard gpu: Intel HD Graphics 5600
dedicated gpu: GTX 960M

**Comment by DanielGibson** [comment]
what operating system are you using?
on windows there should be a way to configure what GPU to use somewhere in the driver settings

see https://www.addictivetips.com/windows-tips/force-app-to-use-dedicated-gpu-windows/

**Comment by nbohr1more** [comment]
The Dark Mod added code support for detecting hybrid GPU configurations:
https://bugs.thedarkmod.com/view.php?id=4953

**Comment by DanielGibson** [comment]
Yeah, I could probably add that.. OTOH, maybe the integrated GPUs often are fast enough for Doom3 and saving energy is more desirable (esp. on Laptops, where Optimus-like configurations are most common)?

**Comment by HugeTaffer** [comment]
Sorry guys, false alarm. Turns out the task manager does show that the game is running on the dedicated gpu. Turns out I was using 16x anti-aliasing and it tanked the framerate. I'm now using 4x anti-aliasing and it's silky smooth.

**Comment by DanielGibson** [comment]
you taffer :-p

**Comment by DanielGibson** [comment]
good point
