### ISSUE TITLE
Unsupported compiler macOS "AppleClang"

### ISSUE THREAD

**Issue by knev** [dhewm/dhewm3#510]
message(CMAKE_COMPILER_IS_GNUCC="${CMAKE_COMPILER_IS_GNUCC}")
    message(CMAKE_C_COMPILER_ID="${CMAKE_C_COMPILER_ID}")
    message(CMAKE_CXX_COMPILER_ID="${CMAKE_CXX_COMPILER_ID}")

returns "`AppleClang`"

    CMAKE_COMPILER_IS_GNUCC=""
    CMAKE_C_COMPILER_ID="AppleClang"
    CMAKE_CXX_COMPILER_ID="AppleClang"

Resulting in 

    CMake Error at CMakeLists.txt:404 (message):
    Unsupported compiler
    
`CMakeLists.txt:264`

**Comment by DanielGibson** [comment]
Is this new?
Because I think that the compiler detection code in your CMakeLists.txt hasn't changed in 11 years..

**Comment by knev** [comment]
Not sure. I don't remember having to mess with my compiler ID previously when build. 
It just worked.

**Comment by knev** [comment]
I might have had gcc installed via homebrew before as well as Xcode installed. Not sure. 
I will have to do some testing.

**Comment by lowlevelsoul** [comment]
Reporting annother occurrence of this happening with latest from master. I'm getting this from cmake :-

CMake Error at CMakeLists.txt:399 (message):
  Unsupported compiler
  
  Trying to build on a 2023 M2 MacBook Pro 14"

**Comment by lowlevelsoul** [comment]
Update 3. Testing on an old Mac mini with Mac OS 10.12 and it works as expected. The odd thing is that CMake does spit out that it's found 'AppleClang'.  Not being very experienced with cmake, I haven't investigated too deeply. 

Could it be that you guys simple not been configuring the project and only generating it, hence missing out on all of the fun?

**Comment by DanielGibson** [comment]
I just pushed a fix, can you test if it works for you?
