### ISSUE TITLE
Crashes all the time.

### ISSUE THREAD

**Issue by TeridaxIcarax** [dhewm/dhewm3#511]
First it crashed when i tried to exit Mars City now it crashes at the beggining cutscene. Tried everything i could nothing helped.

**Comment by DanielGibson** [comment]
What operating system are you using?
What GPU and driver?
Which version of dhewm3?

**Comment by TeridaxIcarax** [comment]
1-windows 11 64-bits.

2-nvidia geforce GTX 1650 4gb.

3-i don't know if it was the latest version.

**Comment by TeridaxIcarax** [comment]
update: i will reinstall dhewm3, as well as the enhanced edition and the essential hd pack and try again.

**Comment by DanielGibson** [comment]
try without the essential HD pack first

**Comment by TeridaxIcarax** [comment]
ok, i will also install a translation mod for my language.

**Comment by DanielGibson** [comment]
please try without any mods at first so we can know if it crashes because of the mod

**Comment by TeridaxIcarax** [comment]
well i tried with the enhanced edition and the translation mod and the game did not crash. i guess i will try the essential hd pack now to see if it crashes.

**Comment by TeridaxIcarax** [comment]
i downloaded the essential hd pack but the lighting is broken now.

**Comment by TeridaxIcarax** [comment]
nevermind the game crashed again lol.

**Comment by TeridaxIcarax** [comment]
Yup, it's the hd mod, it's causing the game to crash.

**Comment by DanielGibson** [comment]
can you post a link to that mod?

**Comment by TeridaxIcarax** [comment]
https://www.moddb.com/mods/d3hdp-doom-3-essential-hd-pack

**Comment by TeridaxIcarax** [comment]
i'm getting this error:

dhewm3 malloc failure to 30367125

**Comment by DanielGibson** [comment]
Can you try if this build works better:
[dhewm3-1.5.3pre-fixHDmodels-try2.zip](https://github.com/dhewm/dhewm3/files/10827957/dhewm3-1.5.3pre-fixHDmodels-try2.zip)

**Comment by TeridaxIcarax** [comment]
i dunno man, isn't dhewm3 malloc failure to 30367125 a memory allocation error?

**Comment by DanielGibson** [comment]
please try that build, it fixed a memory allocation failure with HD models, maybe you're having the same issue

**Comment by TeridaxIcarax** [comment]
ok i will try it.

**Comment by TeridaxIcarax** [comment]
it worked! but i wasn't with the max graphical settings when i tested it, i will try it now again with the max settings.

**Comment by TeridaxIcarax** [comment]
the game is crashing on the startup loading screen on ultra settings.

**Comment by TeridaxIcarax** [comment]
tl.dr: the game is now working and no longer crashes when exiting mars city, but it also doesn't run on ultra settings(might be my PC this time) so i won't pplay the game on the highest settings for now on.

Thank you i think my problem is now fixed.

**Comment by DanielGibson** [comment]
great, glad it works!
do you have any information on the crash on ultra settings?
it might indeed just be your hardware (esp. when using a HD pack), but might be worth looking at

**Comment by TeridaxIcarax** [comment]
It just cuts back to the desktop with no blue screen.

**Comment by DanielGibson** [comment]
ok, no idea  then
