### ISSUE TITLE
How to compile dhewm3-mods_1.5.2

### ISSUE THREAD

**Issue by lea2501** [dhewm/dhewm3#513]
Hi! i need the file d3le.so for OpenBSD operating system, to use the "The Lost Mission" mod here: https://www.moddb.com/mods/the-lost-mission/downloads/d3-lost-mission

That d3le.so file exists inside this file dhewm3-mods_1.5.2_Linux_amd64.tar.gz but when i compile this repository for dhewm3 i don't get this d3le.so file.

So the question is how can i compile dhewm3-mods_1.5.2?

**Comment by DanielGibson** [comment]
See the d3le branch of https://github.com/dhewm/dhewm3-sdk

**Comment by lea2501** [comment]
> See the d3le branch of https://github.com/dhewm/dhewm3-sdk

thanks! i successfully compiled that branch and got the 'd3le.so' file compiled on OpenBSD with these commands:

```
$ git clone -b d3le https://github.com/dhewm/dhewm3-sdk.git
$ mkdir -p build
$ cd build
$ cmake ../
$ gmake -j4
$ doas cp -v /d3le.so /usr/local/lib/dhewm3/
```
