### ISSUE TITLE
Can't launch on Linux, some TGA error

### ISSUE THREAD

**Issue by vorob1** [dhewm/dhewm3#514]
Laptop from 2009 with GF260M, works perfectly under Windows 7, but both Ubuntu 18 and Mint 20.3 gives me these errors:

`vorob@vorob-G60VX:~/Downloads/dhewm3$ ./dhewm3
dhewm3 1.5.0.1304 linux-x86_64 Dec 15 2018 03:06:01 using SDL v2.0.8
WARNING: terminal type 'xterm-256color' is unknown. terminal support may not work correctly
terminal support enabled ( use +set in_tty 0 to disable )
pid: 5699
3952 MB System Memory
found interface lo - loopback
found interface wlp3s0 - 192.168.1.69/255.255.255.0
doom using MMX & SSE & SSE2 for SIMD processing
enabling Flush-To-Zero mode
enabling Denormals-Are-Zero mode
WARNING: base path '/usr/local/share/dhewm3' does not exist
WARNING: using path of executable: /home/vorob/Downloads/dhewm3
----- Initializing File System -----
Loaded pk4 /home/vorob/Downloads/dhewm3/base/pak000.pk4 with checksum 0x28d208f1
Loaded pk4 /home/vorob/Downloads/dhewm3/base/pak001.pk4 with checksum 0x40244be0
Loaded pk4 /home/vorob/Downloads/dhewm3/base/pak002.pk4 with checksum 0xc51ecdcd
Loaded pk4 /home/vorob/Downloads/dhewm3/base/pak003.pk4 with checksum 0xcd79d028
Loaded pk4 /home/vorob/Downloads/dhewm3/base/pak004.pk4 with checksum 0x765e4f8b
Loaded pk4 /home/vorob/Downloads/dhewm3/base/pak005.pk4 with checksum 0x8ffc3621
Loaded pk4 /home/vorob/Downloads/dhewm3/base/pak006.pk4 with checksum 0x95b65ab
Loaded pk4 /home/vorob/Downloads/dhewm3/base/pak007.pk4 with checksum 0x666bdb3c
Loaded pk4 /home/vorob/Downloads/dhewm3/base/pak008.pk4 with checksum 0x23ae5993
Current search path:
/home/vorob/.config/dhewm3/base
/home/vorob/.local/share/dhewm3/base
/home/vorob/Downloads/dhewm3/base
/home/vorob/Downloads/dhewm3/base/pak008.pk4 (3 files)
/home/vorob/Downloads/dhewm3/base/pak007.pk4 (38 files)
/home/vorob/Downloads/dhewm3/base/pak006.pk4 (48 files)
/home/vorob/Downloads/dhewm3/base/pak005.pk4 (63 files)
/home/vorob/Downloads/dhewm3/base/pak004.pk4 (5137 files)
/home/vorob/Downloads/dhewm3/base/pak003.pk4 (4676 files)
/home/vorob/Downloads/dhewm3/base/pak002.pk4 (6120 files)
/home/vorob/Downloads/dhewm3/base/pak001.pk4 (8972 files)
/home/vorob/Downloads/dhewm3/base/pak000.pk4 (2698 files)
Addon pk4s:
----- Initializing Decls -----
5206 strings read from strings/english.lang
TODO: Sys_SetClipboardData
********************
ERROR: LoadTGA( textures/black.tga ): Only type 2 (RGB), 3 (gray), and 10 (RGB) TGA images supported

********************
idRenderSystem::Shutdown()
Shutting down OpenGL subsystem
Sys_Error: LoadTGA( textures/black.tga ): Only type 2 (RGB), 3 (gray), and 10 (RGB) TGA images supported

shutdown terminal support
`

**Comment by DanielGibson** [comment]
> dhewm3 1.5.0.1304 linux-x86_64 Dec 15 2018

Have you tried [dhewm3 1.5.2](https://github.com/dhewm/dhewm3/releases/tag/1.5.2)?

**Comment by vorob1** [comment]
Yep, and then I tried older build. Same stuff. Maybe I need some dependencies? Or wrong rights on files need to fixed?

**Comment by vorob1** [comment]
I'm sorry! Win version also stopped launching. Looks like files became corrupted. I'll replace them and be back.

**Comment by DanielGibson** [comment]
so, did replacing the files fix your problem?
