### ISSUE TITLE
[Question] What does this binary do?

### ISSUE THREAD

**Issue by SilentMRG** [dhewm/dhewm3#520]
Hello, I apologize for the somewhat stupid question, but, what does the binary
"dhewm3-mods_1.5.2_win32.zip"? Is it focused on loading mods?

I downloaded the binary
"dhewm3_1.5.2_win32.zip".

Thanks in advance!

**Comment by DanielGibson** [comment]
It's a [Zip Archive](https://en.wikipedia.org/wiki/ZIP_(file_format)) that contains the dhewm3 binaries (the executable dhewm3.exe, the DLLs for the base game and the addon, and also the dedicated server executable dhewm3ded.exe).

dhewm3.exe is a replacement for Doom3.exe

**Comment by SilentMRG** [comment]
Yes, that I know. What I want to know is what is the difference between the binaries "dhewm3-mods_1.5.2_win32.zip" and "dhewm3_1.5.2_win32.zip"? Are they the same file or do the "mods" version do something different?

Thanks!

**Comment by DanielGibson** [comment]
dhewm3-mods_1.5.2_win32.zip contains game DLLs for the mods listed on https://dhewm3.org/mods.html

**Comment by SilentMRG** [comment]
Thanks for the info bro!
