### ISSUE TITLE
Thinkpad's touchpad mouse not working during (most) keyboard inputs

### ISSUE THREAD

**Issue by T-X** [dhewm/dhewm3#524]
I have a Lenovo Thinkpad T14s AMD Gen3 here, which features two mouse devices: The red knob trackpoint and a touchpad. The former works without issues, with the latter I'm facing some issues.

While using movement inputs, like WASD or crouching the touchpad mouse does not react. When not moving via WASD etc. the touchpad works fine though, it's just the parallel inputs do not seem to work.

The trackpoint does not have this issue either, it can be used while using WASD etc.

Interestingly, when using WASD while holding the shift key for sprinting then during sprinting the touchpad works, too.

I'm on Debian Sid and using dhewm3 as provided by Debian (1.5.2+dfsg-1). And tried the Doom3 demo with it.

```
$  xinput list
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ ELAN0678:00 04F3:3195 Mouse             	id=10	[slave  pointer  (2)]
⎜   ↳ ELAN0678:00 04F3:3195 Touchpad          	id=11	[slave  pointer  (2)]
⎜   ↳ TPPS/2 Elan TrackPoint                  	id=13	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ Power Button                            	id=6	[slave  keyboard (3)]
    ↳ Video Bus                               	id=7	[slave  keyboard (3)]
    ↳ Power Button                            	id=8	[slave  keyboard (3)]
    ↳ Sleep Button                            	id=9	[slave  keyboard (3)]
    ↳ AT Translated Set 2 keyboard            	id=12	[slave  keyboard (3)]
    ↳ ThinkPad Extra Buttons                  	id=14	[slave  keyboard (3)]
    ↳ PLT BB PRO 2 (AVRCP)                    	id=15	[slave  keyboard (3)]
$ uname -a
Linux linus-lptp 6.3.0-1-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.3.7-1 (2023-06-12) x86_64 GNU/Linux
```

**Comment by turol** [comment]
Do you have "disable touchpad while typing" enabled in your desktop settings? If so, working as intended...

**Comment by T-X** [comment]
@turol oh, you're right, never noticed that before! It's indeed also behaving like this on any other game or on the desktop :smile:.

And I can also change that behaviour with xinput:

```
$ xinput list-props "ELAN0678:00 04F3:3195 Touchpad" | grep "libinput Disable While Typing Enabled" 
	libinput Disable While Typing Enabled (326):	1
	libinput Disable While Typing Enabled Default (327):	1
$ xinput set-prop "ELAN0678:00 04F3:3195 Touchpad" "libinput Disable While Typing Enabled" 0
$ xinput list-props "ELAN0678:00 04F3:3195 Touchpad" | grep "libinput Disable While Typing Enabled"
	libinput Disable While Typing Enabled (326):	0
	libinput Disable While Typing Enabled Default (327):	1
```

Thanks for the help and sorry for bothering! Closing this as a non-issue.
