### ISSUE TITLE
Error loading map Phobos 2 Resurrection of Evil

### ISSUE THREAD

**Issue by Caleb-Revixit** [dhewm/dhewm3#529]
I'm using dhewm3 1.5.1.1305. I'm playing doom 3 resurrection of evil. When loading the next level the following error occurs: 
ERROR: idIK_Walk::Init: invalid foot joint 'ik_foot1'
How can I fix this?
Attached files.[https://drive.google.com/file/d/12vjhC27-lG27QJ7lDpFymJeZSmskimLw/view?usp=sharing](url)
[https://drive.google.com/file/d/1rRneuAeZY6561oFmpC-IBcjawnD2U7LI/view?usp=sharing](url)

**Comment by DanielGibson** [comment]
Can you try [dhewm3 1.5.2](https://github.com/dhewm/dhewm3/releases/tag/1.5.2) ?
If it still doesn't work, try if removing those extra pk4 files helps:
```
C:\GameCenter\dhewm3\base\r_AI_textures_base1.pk4a
C:\GameCenter\dhewm3\base\r_AI_textures_base2.pk4
C:\GameCenter\dhewm3\base\shotgun.pk4
C:\GameCenter\dhewm3\base\Ungibbable.pk4
C:\GameCenter\dhewm3\base\zzzBRASSnBLOOD.pk4

C:\GameCenter\dhewm3\d3xp\r_AI_textures_d3xp.pk4
C:\GameCenter\dhewm3\d3xp\shotgun.pk4
C:\GameCenter\dhewm3\d3xp\Ungibbable.pk4
C:\GameCenter\dhewm3\d3xp\zzzBRASSnBLOOD.pk4
```

**Comment by Caleb-Revixit** [comment]
Yes. The problem was with one of the mods. Sorry for disturbing. In version dhewm3 1.5.2 I have a problem with sound: missing sounds of firing from machine guns; sound positioning with emphasis on the right channel.

**Comment by DanielGibson** [comment]
Weird, this is the first time I've heard of that kind of sound issues with 1.5.2 - I think there haven't even been many sound related changes since 1.5.1

One thing you could try is replacing the OpenAL32.dll in 1.5.2 with the one from 1.5.1, in case your sound issues are somehow caused by openal-soft changes (1.5.2 ships a newer version of that DLL)

**Comment by Caleb-Revixit** [comment]
> Странно, я впервые слышу о таких проблемах со звуком в версии 1.5.2 — думаю, с версии 1.5.1 даже не было много изменений, связанных со звуком.
> 
> Вы можете попробовать заменить OpenAL32.dll в версии 1.5.2 на файл из версии 1.5.1, если ваши проблемы со звуком каким-то образом вызваны изменениями openal-soft (1.5.2 включает более новую версию этой DLL).

Fine. I'll try. Thanks for answers.
