### ISSUE TITLE
RoE: Phobos Labs Sector 1 - Clipping through Skytram floor

### ISSUE THREAD

**Issue by abandon-the-flesh** [dhewm/dhewm3#535]
[Please watch video here](https://clips.twitch.tv/GoodTiredHerringWutFace-ageKa8hHQx4Io7TS)

Trying to end Phobos Labs Sector 1 level (RESURRECTION OF EVIL), am unable to board the Skytram as I clip through the floor. Reloading does nothing. I don't have a save on the unmodded version of the game. I could maybe try moving the save to remove textures? Unsure what directory that is typically stored in. I can investigate moving the save later.

For now, I'd like to know if I'm doing something wrong here or is there a reason I'm clipping through the floor?

Thanks.

**Comment by DanielGibson** [comment]
I don't think that there's a good reason for this to happen (haven't tried to reproduce it yet).

What version of dhewm3 are you using, and what operating system?

**Comment by abandon-the-flesh** [comment]
Hello I am on the latest Windows 10 with an old nvidia1060 6gb. I downloaded the mod from here 

https://www.moddb.com/mods/d3hdp-doom-3-essential-hd-pack/downloads/d3hdp-doom-3-essential-hd-pack-v20

I think I'm still on 2.0 but I see there was an update? I can try to update later today and see if it fixes anything.

**Comment by DanielGibson** [comment]
That mod doesn't include dhewm3 (and is not developed by me, so I don't know if it maybe breaks something that would work with the vanilla game).

If you're indeed using dhewm3.exe, you probably downloaded it here.
If you open the console (Shift+Esc), the version is printed on the lower right of the console.
If it's not 1.5.2, try 1.5.2 from https://github.com/dhewm/dhewm3/releases/tag/1.5.2

**Comment by DanielGibson** [comment]
If that doesn't work, try the latest beta-build: https://github.com/dhewm/dhewm3/files/10827957/dhewm3-1.5.3pre-fixHDmodels-try2.zip

**Comment by abandon-the-flesh** [comment]
My mistake! I am launching through your exe. New to the game and a friend told me to download all this stuff. I'll update you when I get home today.

**Comment by abandon-the-flesh** [comment]
Confirmed I am running 1.5.2.1305 from 6/13/22. 
Attempted to finish level with 1.5.3 as suggested. Still clipping through the floor.
Updated D3HDP - DooM 3 Essential HD Pack v2.0 from Oct 22nd, 2023 (as linked in prior post). 
I can stand on the floor! Thank you for assisting me in troubleshooting. My apologies for the confusion. 
Hopefully anyone else using the HD Pack and launching through dhewm sees this closed issue and will know to update the HD pack.

Grateful for your work.

**Comment by DanielGibson** [comment]
Great, glad it works now!
