### ISSUE TITLE
[Feature Request] support of Quake 4 / Prey (2006) 

### ISSUE THREAD

**Issue by r-a-sattarov** [dhewm/dhewm3#537]
Hi everybody. It is interesting to know how difficult\possible it can be to add support for Quake 4 or Prey (2006) games to RBDOOM-3-BFG?
There were projects ([Quake4Doom](https://github.com/jmarshall23/Quake4Doom), [PreyDoom](https://github.com/jmarshall23/PreyDoom)) that support these games in their engines. Moreover, there is a [project](https://github.com/glKarin/com.n0n3m4.diii4a) that ported these games to the Android platform.

**Comment by DanielGibson** [comment]
Furthermore, this isn't RBD3BFG
