### ISSUE TITLE
Support for 21:9 (and other) ultrawide aspect ratios?

### ISSUE THREAD

**Issue by smeep0** [dhewm/dhewm3#538]
I just installed Dhewm3 on both my older PC (which use 3x1080p screens), and my newer ultrawide setup.
While it works great for the former, I am having trouble trying to correctly set my resolution to 3440x1440 for Dhewm3. I have already altered the base Doomconfig.cfg file to include r_customWidth to 3440, r_customHeight to 1440, r_mode to -1, and r_aspectRatio to 1, but the game still refuses to acknowledge these ultrawide resolution parameters. HUD elements still look stretched, and FMVs aren't scaled properly.

**Comment by DanielGibson** [comment]
You should leave `r_aspectRatio` at `-1`, `1` means 16:9, which isn't ultrawide (`-1` means "do the right thing for the current resolution, assuming that the pixels are square")

If that doesn't help, what happens if you set `r_customWidth`, `r_customHeight` and `r_mode` **in the console** (open it with Shift+Esc and enter `r_customWidth 30` etc)?

**Comment by DanielGibson** [comment]
Furthermore, many HUD elements (health, ammo count, etc) *will* be stretched, that's not really avoidable, especially with the original assets.
The crosshair should be round though, and full screen menus (like the PDA or the main menu) should be in 4:3 with black bars on left/right, so they don't look distorted

**Comment by smeep0** [comment]
Okay, so I think I was able to partially resolve most of the issues, but some elements like the full screen menus and PDA as you've mentioned _still_ appear stretched.

I found the dhewm.cfg file and decided to input the specific ultrawide parameters (`r_customWidth` at `3440` and `r_customHeight` at `1440`, `r_mode` to `-1`) and left `r_aspectRatio` to `-1` like you've mentioned. The crosshair does appear as a circle now, but everything else, such as the aforementioned main menu and PDA, are still stretched with no black bars of any sort present. I tried to look at the config file again and found `r_scaleMenusto43` which I set to `1` to see if it would help, but the game would simply boot with the same issues as before (sans the now round crosshair), and checking the cfg file again would show `r_scaleMenusto43` had reverted back to `0`.

**Comment by smeep0** [comment]
Just found out what was causing my game to not display the correct aspect ratio. Apparently dhewm3 also includes an autoconfig.cfg file. Modifying that file with the above variables has allowed me to get the pillarboxing for the correct aspect ratio along with finally being able to disable vsync from the start.
