### ISSUE TITLE
Missing link libraries because of ${CURL_LIBRARY} not set in CMakeLists.txt

### ISSUE THREAD

**Issue by jopadan** [dhewm/dhewm3#541]
```CMake
find_package(CURL QUIET)
if(CURL_FOUND)
        set(ID_ENABLE_CURL ON)
        include_directories(${CURL_INCLUDE_DIR})
        message(STATUS "libcurl found and enabled")
else()
        message(WARNING "libcurl not found, server downloads won't be available (apart from that dhewm3 will work)")
        set(ID_ENABLE_CURL OFF)
        set(CURL_LIBRARY "")
endif()
```

Manually adding the missing dependencies:
```Cmake
set(CURL_LIBRARY CURL::libcurl -lgssapi_krb5 -lnghttp2 -lgnutls -lrustls -lbrotlidec -lzstd -lidn2 -lnettle -lrtmp -lcares)
```

compiles.

Platform is:
- gentoo linux-6.6.7
- cmake-3.27.9
-  net-misc/curl-8.5.0::gentoo  USE="adns alt-svc brotli ftp gnutls gopher hsts http2 idn imap kerberos openssl pop3 progress-meter rtmp rustls samba smtp ssh ssl static-libs telnet tftp verify-sig websockets zstd -ldap -mbedtls -nghttp3 (-sslv3) -test" ABI_X86="32 (64) (-x32)" CURL_SSL="openssl -gnutls -mbedtls -rustls"

**Comment by jopadan** [comment]
Updating [FindCURL.cmake](https://gitlab.kitware.com/cmake/cmake/-/blob/master/Modules/FindCURL.cmake?ref_type=heads) and reinstalling fixed it.

**Comment by DanielGibson** [comment]
You shouldn't have to link all those libs manually - *unless* you statically link curl, which doesn't seem like a supergood idea to me.
If you link libcurl dynamically, libcurl.so.4 (or whatever it's called on your system) links against the required libs and dhewm3 only needs to link against libcurl itself.
