### ISSUE TITLE
Support arm aarch64 ? 

### ISSUE THREAD

**Issue by InfernalWolf666** [dhewm/dhewm3#545]
Orange pi 5 plus support ?
Cpu - arm - rk3588

**Comment by DanielGibson** [comment]
aarch64 is supported

**Comment by InfernalWolf666** [comment]
I didn’t see this download on the site. for example, on the site with GZDoom there is a download for arm 64. please give me the link

**Comment by DanielGibson** [comment]
you'll have to build it yourself, or install the version your linux distribution's package manager provides (e.g. `sudo apt install dhewm3-doom3`)

**Comment by InfernalWolf666** [comment]
Thanks

**Comment by InfernalWolf666** [comment]
> вам придется собрать его самостоятельно или установить версию, которую предоставляет менеджер пакетов вашего дистрибутива Linux (например `sudo apt install dhewm3-doom3`)

This is work on orange pi 5 plus on ubunta 22.04 Joshua Riek relis 1.32

Thanhs Sir
