### ISSUE TITLE
A Question about key bindings

### ISSUE THREAD

**Issue by wof8317** [dhewm/dhewm3#547]
I've noticed that this project is working on controller support, which I think is fantastic. But this is where I have one key question about this that has to do with keybindings: Can dhewm3 support binding more than one function to a keyboard key or a controller button (once support for it matures enough to merge into the master branch)? I ask this because I started testing it by creating a controller binding based off the default controller configuration for the OG Xbox port of Doom 3. One trouble that I had was binding the "back button" (the one to the immediate left of the Guide button on an Xbox controller), to both Quicksave and Player ready.

**Comment by DanielGibson** [comment]
No, that's not possible.
