### ISSUE TITLE
Problems trying to compile from source code

### ISSUE THREAD

**Issue by ViperAcidZX** [dhewm/dhewm3#550]
I was trying to compile an early build of 1.5.3 and when I compiled my own executable I get this error:

![image](https://github.com/dhewm/dhewm3/assets/19318128/1b6e76df-5eb8-47c3-aec1-0e042a905b62)

I don't know what's going on, I never had any issues with compiling the dhewm3 exe and the SDK for the base games/mods I wanted to use with it months ago but lately now I keep running into errors like this.

**Comment by turol** [comment]
You have a mismatching bitness DLL somewhere. This is one of the most useless error messages in Windows that's quite something.

**Comment by ViperAcidZX** [comment]
I was trying to compile a 64-bit version of the source port and the SDK files and it worked before but I'm not sure what's happening to cause this now.

**Comment by turol** [comment]
You're missing zlib. Install it and tell CMake where to find it.

**Comment by ViperAcidZX** [comment]
I managed to fix the issue going by using vcpkg instead of the dhewm3-libs library to compile the port's executable instead, though part of the issues I was dealing with was the vcpkg compile instructions for CMake being outdated and misleading. It says to do this...

> cmake -B [build directory] -S . -DCMAKE_TOOLCHAIN_FILE=[path to vcpkg]/scripts/buildsystems/vcpkg.cmake

but for dhewm3's instructions I had to do this instead:

> cmake -S "/path/to/dhewm3-repository/neo" -B [build directory] -DCMAKE_TOOLCHAIN_FILE=[path to vcpkg]/scripts/buildsystems/vcpkg.cmake

I think maybe the instructions to compile could be cleaned up and updated for vcpkg libraries to avoid these issues.

**Comment by DanielGibson** [comment]
probably the vcpkg instructions assume that you're in the directory with the CMakeLists.txt file, i.e. /path/to/dhewm3-repo/neo, then `-S .` would work.

Your problem with dhewm3libs was that you didn't tell cmake where to find them. https://github.com/dhewm/dhewm3/#using-the-provided-windows-binaries says: 
> Issue the appropriate command from the build folder, for example (for VS2019 and 32bit):
>
> cmake -G "Visual Studio 16 2019" -A Win32 -DDHEWM3LIBS=/path/to/dhewm3-libs/i686-w64-mingw32 /path/to/repository/neo

As far as I can tell from the error.txt you posted, you were missing the `-DDHEWM3LIBS=bla` part - which is the reason why zlib couldn't be found.

**Comment by ViperAcidZX** [comment]
> cmake -G "Visual Studio 16 2019" -A Win32 -DDHEWM3LIBS=/path/to/dhewm3-libs/i686-w64-mingw32 /path/to/repository/neo

That fixed it issue and sorry for the inconvenience, it was a long while since I compiled this from source code and the different instructions was messing me up.

**Comment by DanielGibson** [comment]
ok, great it works now
