### ISSUE TITLE
Vulkan support

### ISSUE THREAD

**Issue by Gr33nEyes** [dhewm/dhewm3#555]
What about native Vulkan support?

**Comment by r-a-sattarov** [comment]
> What about native Vulkan support?

Try to look at this project - https://github.com/DustinHLand/vkDOOM3

**Comment by Gr33nEyes** [comment]
> Try to look at this project - https://github.com/DustinHLand/vkDOOM3

It is for BFG Edition.

**Comment by DanielGibson** [comment]
see https://github.com/dhewm/dhewm3/issues/506#issuecomment-1848483461
