### ISSUE TITLE
map_erebus1 not found when start new game for expansion

### ISSUE THREAD

**Issue by Valour549** [dhewm/dhewm3#556]
The base game Doom 3 runs fine, but when I try to start a new game of the expansion, it gives me error of **map_erebus1 not found**.

I am launching through a shortcut _"D:\GOG Games\DOOM 3\dhewm3.exe" +disconnect +set fs_game_base d3xp_ and I believe I have everything installed correctly, as per screenshot of my d3xp folder below.

Please advise.

![image](https://github.com/dhewm/dhewm3/assets/88639237/33e591d9-f5e4-48ad-a0bf-322283f74c58)

**Comment by DanielGibson** [comment]
To play Resurrection of Evil, you need to set `+set fs_game d3xp` - `+set fs_game_base d3xp` is used for mods **based on** d3xp

**Comment by Valour549** [comment]
Ahh my bad, issue fixed.

**Comment by DanielGibson** [comment]
great, glad it works now!

**Comment by Valour549** [comment]
Because armor is so useless in veteran mode, I've gone ahead and added **seta g_armorProtection "0.6"** to DoomConfig.cfg and autoexec.cfg. But every time I transfer into a new level, these settings don't work anymore until I exit the game and open it again. Would you know how to fix this issue?
