### ISSUE TITLE
Certain maps wont load

### ISSUE THREAD

**Issue by Firaveus24** [dhewm/dhewm3#557]
Error: Multiple entitys named" Stabilization hub ?   This happens when I try to load certain maps and not sure why?

**Comment by DanielGibson** [comment]
Sorry, my crystal ball currently doesn't work properly, probably doesn't like the rain.
So unfortunately you'll have to provide more information yourself:
* What maps?
* What dhewm3 version are you using?
* What operating system?
* Please reproduce the problem and afterwards copy `My Documents/My Games/dhewm3/dhewm3log.txt` (or `$HOME/.local/share/dhewm3/dhewm3log.txt` on Linux/BSD/... or `$HOME/Library/Application Support/dhewm3/dhewm3log.txt` on macOS) and attach it to a post here

**Comment by Firaveus24** [comment]
Ahh nevermind I figured it out. I just went into user data and deleted the dhewm3 folder and reinstalled mod and it fixed the multiple entitys issue,Win 10  dhewm3 1.5.3
