### ISSUE TITLE
Flashlight stops working

### ISSUE THREAD

**Issue by Q3BFG10K** [dhewm/dhewm3#562]
This is an issue from OG Doom 3 which Dhewm3 also has. 

In the Communications (comm1) and Monorail Skybridge (recycling1) levels, the flashlight will randomly stop working and no light is rendered. This seems more likely to trigger if you quicksave and/or quickload a lot. 

Switching to a melee weapon such as fists or chainsaw restores the flashlight until the next time it happens.

**Comment by DanielGibson** [comment]
please try the latest release candidate, I fixed a bug like this after the last release.
https://github.com/dhewm/dhewm3/releases/tag/1.5.3_RC2

**Comment by Q3BFG10K** [comment]
Thanks, I'll try it out next time I play the game. I'll close this one and re-open if I find any issues.

**Comment by Q3BFG10K** [comment]
I played through the whole game on 1.5.4 and had no more flashlight issues, thank you.

**Comment by DanielGibson** [comment]
Cool, thanks for testing and for the feedback! :)
