### ISSUE TITLE
[Warning] Area 51 (2005)

### ISSUE THREAD

**Issue by SilentMRG** [dhewm/dhewm3#563]
Hello everybody!

I just want to let you know that the source code is available here: https://github.com/ProjectDreamland/area51

And it's important to remember that the game in question is Freeware, and free of copyright since 2008, so if any programmer is interested in starting a source port project now is a good time, and there will be no barriers to it.

Cheers!

**Comment by hemebond** [comment]
@DanielGibson I think this is spam. I can't find any connection to Doom 3.

**Comment by SilentMRG** [comment]
There really is no connection to Doom 3. No, it's not spam, the source code exists and the repository is authentic. I just shared it here so that maybe you, good programmers, can create a source port in the future.
