### ISSUE TITLE
[gamepad] inconsistent use of the gamepad buttons

### ISSUE THREAD

**Issue by BielBdeLuna** [dhewm/dhewm3#565]
in the main menu A button ( or X in Sony terms ) is used as "shoot" so as the left trigger, even when shoot is not bound yet to any of the gamepad's buttons. (i think the gamepad buttons are hard-coded for the main menu and the PDA, isn't it?) but when it comes to the PDA, if X isn't bound to "shoot" you can't use it there to "click" on buttons, you can use the left trigger (if it is bound to "shoot", or other-ways, whatever button you've bound in order to "shoot")

now wouldn't it be far more optimal to add a separated "UI click" command from the "shoot" command and bound it to the A/X button and have those "UI clicks" only happen when interacting with full screen UIs, and in normal random, 3D game have the "UI click" commands be meaningless, and so interact with the in-game 3D UI panels with the normal "shoot" command like with the  normal keyboard and mouse.

also, and this is comparing Dhewm3 with Doom3 BFG,  there you can press B/O as a sort of "UI back" command, that is non existing in the normal doom3, and also for the ease of use, there is some sort of usage of the shoulder buttons to move from some categories, maybe those interactions could be added too?

**Comment by DanielGibson** [comment]
see other issue, they're related
