### ISSUE TITLE
Gamepad mouse emulation focus issue

### ISSUE THREAD

**Issue by DanielGibson** [dhewm/dhewm3#566]
> I can get this problem somewhat consistently ~~in base Doom 3 early into Delta Labs 1 and~~ *(this is already fixed)* always consistently in The Lost Mission campaign port in the elevator before the Trite ambush in Underground Site 1.

> I tried Lost Mission with the RC2 release of v1.5.3 at the same spot I was having the problems I reported earlier and it still happens sadly. Even compiled 64-bit builds I compiled via source code reproduces the issue. I haven't tried base Doom 3 or Resurrection of Evil yet though.

_Originally posted by @ViperAcidZX in https://github.com/dhewm/dhewm3/issues/536#issuecomment-2008561279_

**Comment by DanielGibson** [comment]
Ok, I can reproduce the issue in D3LE as well, there it's a different problem - apparently the panel (to call the lift) becomes inactive or something when pressing it, and that doesn't go through a codepath where I detect that no UI is focused anymore..

Gamepad support really is a gift that keeps on giving -_-

**Comment by DanielGibson** [comment]
This build should fix that issue: [dhewm3-1.5.3_RC2+gamepadfix_win32.zip](https://github.com/dhewm/dhewm3/files/14670607/dhewm3-1.5.3_RC2%2Bgamepadfix_win32.zip)
(the mod DLL does *not* need to be updated, the fix is entirely in engine code)

@ViperAcidZX Thanks for testing this so thoroughly and please let me know if there are more gamepad issues (or other bugs) :)

**Comment by BielBdeLuna** [comment]
I added this pull request which might help with the binding of any key/button from any legal device

**Comment by DanielGibson** [comment]
fixed
