### ISSUE TITLE
Error while compiling for PowerPC in OSX

### ISSUE THREAD

**Issue by vkosikhin** [dhewm/dhewm3#568]
While trying to compile Dhewm3 on a PowerPC Mac in OSX Leopard I get the following errors.

Power-Mac-G5:build test$ make -j4
[  1%] Building CXX object CMakeFiles/idlib.dir/idlib/bv/Bounds.cpp.o
[  1%] Building CXX object CMakeFiles/idlib.dir/idlib/bv/Box.cpp.o
[  1%] Building CXX object CMakeFiles/idlib.dir/idlib/bv/Frustum.cpp.o
[  1%] Building CXX object CMakeFiles/idlib.dir/idlib/bv/Sphere.cpp.o
cc1plus: error: invalid option 'arch=native'
cc1plus: error: unrecognized command line option "-ffp-contract=off"

The first one I was able circumvent by specifying -DONATIVE=OFF, but I'd like to use those optimizations if they have any impact on performance.

As for the unrecognized command, I made sure to replace the XCode compiler driver links with those from GCC 7.5 available via Homebrew (and updated 'make' for good measure), but that still didn't help.

UPD. Not sure if it's relevant to the issue, but the only copies of cc1plus found on the disk are version 4.2.1, which seems to  be the original XCode one.

**Comment by DanielGibson** [comment]
Does this change in neo/CMakeLists.txt help?

```diff
diff --git a/neo/CMakeLists.txt b/neo/CMakeLists.txt
index 6797a73f..81bcbe1d 100644
--- a/neo/CMakeLists.txt
+++ b/neo/CMakeLists.txt
@@ -307,7 +307,10 @@ if(D3_COMPILER_IS_GCC_OR_CLANG)
        add_compile_options(-fno-strict-aliasing)
        # dear idiot compilers, don't fuck up math code with useless FMA "optimizations"
        # (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=100839)
-       add_compile_options(-ffp-contract=off)
+       CHECK_CXX_COMPILER_FLAG("-ffp-contract=off" cxx_has_fp-contract)
+       if(cxx_has_fp-contract)
+               add_compile_options(-ffp-contract=off)
+       endif()
        
        if(ASAN)
                # if this doesn't work, ASan might not be available on your platform, don't set ASAN then..
```

**Comment by vkosikhin** [comment]
Thank you, that helped. But now it throws a different error midway through the compilation (console output attached).

[error.txt](https://github.com/dhewm/dhewm3/files/14748442/error.txt)

**Comment by DanielGibson** [comment]
does this help:
```diff
diff --git a/neo/renderer/Image_files.cpp b/neo/renderer/Image_files.cpp
index 8ea1dbaa..289f3b07 100644
--- a/neo/renderer/Image_files.cpp
+++ b/neo/renderer/Image_files.cpp
@@ -28,6 +28,10 @@ If you have questions concerning this license or the applicable additional terms
 
 // DG: replace libjpeg with stb_image.h because it causes fewer headaches
 // include this first, otherwise build breaks because of  use_idStr_* #defines in Str.h
+#if defined(__APPLE__) && !defined(__clang__) && defined(__GNUC__) && __GNUC__ < 5
+  // Extra-Hack for ancient GCC 4.2-based Apple compilers that don't support __thread
+  #define STBI_NO_THREAD_LOCALS
+#endif
 #define STB_IMAGE_IMPLEMENTATION
 #define STBI_NO_HDR
 #define STBI_NO_LINEAR
```

**Comment by vkosikhin** [comment]
Yes, that worked. I also had to link a newer version of zlib to make minizip happy.

`cmake -DZLIB_LIBRARY=/usr/local/opt/zlib/lib/libz.dylib -DZLIB_INCLUDE_DIR=/usr/local/opt/zlib/include -DOPENAL_LIBRARY=/usr/local/opt/openal-soft/lib/libopenal.dylib -DOPENAL_INCLUDE_DIR=/usr/local/opt/openal-soft/include /Users/test/dhewm3/neo`

Now there's one more error.

`/Users/test/dhewm3/neo/sound/snd_local.h:765: error: 'LPALCRESETDEVICESOFT' does not name a type
/Users/test/dhewm3/neo/sound/snd_local.h:765: error: 'LPALCRESETDEVICESOFT' does not name a type
make[2]: *** [CMakeFiles/dhewm3.dir/build.make:2999: CMakeFiles/dhewm3.dir/sound/snd_efxfile.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/Users/test/dhewm3/neo/sound/snd_local.h:225: warning: 'class idAudioBuffer' has virtual functions but non-virtual destructor
/Users/test/dhewm3/neo/sound/snd_local.h:765: error: 'LPALCRESETDEVICESOFT' does not name a type
/Users/test/dhewm3/neo/sound/snd_local.h:225: warning: 'class idAudioBuffer' has virtual functions but non-virtual destructor
make[2]: *** [CMakeFiles/dhewm3.dir/build.make:2951: CMakeFiles/dhewm3.dir/sound/snd_cache.cpp.o] Error 1
/Users/test/dhewm3/neo/sound/snd_local.h:765: error: 'LPALCRESETDEVICESOFT' does not name a type
make[2]: *** [CMakeFiles/dhewm3.dir/build.make:3023: CMakeFiles/dhewm3.dir/sound/snd_emitter.cpp.o] Error 1
make[2]: *** [CMakeFiles/dhewm3.dir/build.make:2975: CMakeFiles/dhewm3.dir/sound/snd_decoder.cpp.o] Error 1
make[2]: Leaving directory '/Users/test/dhewm3/build'
make[1]: *** [CMakeFiles/Makefile2:179: CMakeFiles/dhewm3.dir/all] Error 2
make[1]: Leaving directory '/Users/test/dhewm3/build'
make: *** [Makefile:84: all] Error 2`

openal-soft 1.16.0 is the latest I managed to build on this system. openal-info output is attached.

[openal.txt](https://github.com/dhewm/dhewm3/files/14757705/openal.txt)

**Comment by DanielGibson** [comment]
does this help:

```diff
diff --git a/neo/sound/snd_local.h b/neo/sound/snd_local.h
index 6c5790eb..c2f5baf8 100644
--- a/neo/sound/snd_local.h
+++ b/neo/sound/snd_local.h
@@ -40,6 +40,12 @@ If you have questions concerning this license or the applicable additional terms
 #include <AL/alc.h>
 #include <AL/alext.h>
 
+// DG: make this code build with older OpenAL headers that don't know about ALC_SOFT_HRTF
+//     which provides LPALCRESETDEVICESOFT for idSoundSystemLocal::alcResetDeviceSOFT()
+#ifndef ALC_SOFT_HRTF
+  typedef ALCboolean (ALC_APIENTRY*LPALCRESETDEVICESOFT)(ALCdevice *device, const ALCint *attribs);
+#endif
+
 #include "framework/UsercmdGen.h"
 #include "sound/efxlib.h"
 #include "sound/sound.h"
```

**Comment by vkosikhin** [comment]
Yes, thank you. But there's a new one.

```
/Users/test/dhewm3/neo/sys/osx/SDLMain.m: In function 'CustomApplicationMain':
/Users/test/dhewm3/neo/sys/osx/SDLMain.m:229: error: cannot find protocol declaration for 'NSApplicationDelegate'
make[2]: *** [CMakeFiles/dhewm3.dir/build.make:3815: CMakeFiles/dhewm3.dir/sys/osx/SDLMain.m.o] Error 1
```

**Comment by DanielGibson** [comment]
does this help
```diff
diff --git a/neo/sys/osx/SDLMain.m b/neo/sys/osx/SDLMain.m
index 5599789e..89ce20c0 100644
--- a/neo/sys/osx/SDLMain.m
+++ b/neo/sys/osx/SDLMain.m
@@ -15,6 +15,8 @@
 #include <sys/param.h> /* for MAXPATHLEN */
 #include <unistd.h>
 
+#include <Availability.h>
+
 /* For some reason, Apple removed setAppleMenu from the headers in 10.4,
  but the method still is there and works. To avoid warnings, we declare
  it ourselves here. */
@@ -226,7 +228,13 @@ static void CustomApplicationMain (int argc, char **argv)
 
     /* Create SDLMain and make it the app delegate */
     sdlMain = [[SDLMain alloc] init];
+
+#if __MAC_OS_X_VERSION_MIN_REQUIRED < 1060 /* before 10.6 */
+    [NSApp setDelegate:sdlMain];
+#else /* 10.6 introduced NSApplicationDelegate, according to
+         https://developer.apple.com/documentation/appkit/nsapplicationdelegate?language=objc */
     [NSApp setDelegate:(id<NSApplicationDelegate>)sdlMain];
+#endif
 
     /* Start the main event loop */
     [NSApp run];
```

**Comment by vkosikhin** [comment]
Now it finally works! Thank you so much for taking your time to fix such an obscure issue. For those who'd also like to fool around with ancient software, you'll have to build SDL2 with joystick support (which Tigerbrew formula doesn't do by default), otherwise the game won't launch.

In the end, the performance is barely half of the official PPC release with the same settings release regardless of EAX effects. Could that be due to the old toolchain? I'm willing to try building on a modern system to see if that makes any difference.

**Comment by DanielGibson** [comment]
Glad to hear it finally works!
Did you do any changes to the source except for the ones I gave you? (I want to commit all the required changes so it builds out of the box)

If the performance sucks, try telling CMake to create a Release build

**Comment by vkosikhin** [comment]
No, I didn't change anything else in the source. The performance is on par with the retail Doom 3 now that I've disabled VSync, even with EAX effects on. The Release build seems marginally better. If you don't mind, it would help to list the requirement to build SDL2 with joystick support in readme, as well as the minimum version of zlib. The default OSX one leads to the following error. v1.3.1 from Tigerbrew works fine when linked directly.

```
/Users/test/dhewm3/neo/framework/minizip/ioapi.c: In function 'fseek64_file_func':
/Users/test/dhewm3/neo/framework/minizip/ioapi.c:190: error: 'z_off64_t' undeclared (first use in this function)
/Users/test/dhewm3/neo/framework/minizip/ioapi.c:190: error: (Each undeclared identifier is reported only once
/Users/test/dhewm3/neo/framework/minizip/ioapi.c:190: error: for each function it appears in.)
/Users/test/dhewm3/neo/framework/minizip/ioapi.c:190: error: syntax error before 'offset'
make[2]: *** [CMakeFiles/dhewm3.dir/build.make:1943: CMakeFiles/dhewm3.dir/framework/minizip/ioapi.c.o] Error 1
```

**Comment by DanielGibson** [comment]
I'm doing some changes so dhewm3 works without SDL gamepad support.
I'll add a note to the README that zlib must be at least 1.2.4.3 (that introduced z_off64_t)

**Comment by DanielGibson** [comment]
does it work with the system zlib if you just modify line 190 of neo/framework/minizip/ioapi.c
from `if(FSEEKO_FUNC((FILE *)stream, (z_off64_t)offset, fseek_origin) != 0)`
to `if(FSEEKO_FUNC((FILE *)stream, offset, fseek_origin) != 0)` (i.e. remove `(z_off64_t)`)?

**Comment by vkosikhin** [comment]
Yes, that works too. I've also reverted GCC and all associated tools back to their vanilla version 4.x, still finished building with no issue.

**Comment by DanielGibson** [comment]
all the changes should be in git now, can you test the current master code, just to be sure I didn't forget something? :)

**Comment by vkosikhin** [comment]
Builds and runs out of the box now. SDL2 without joystick support didn't cause any issues either.

**Comment by vkosikhin** [comment]
Now I've tried integrating libbacktrace from here: [https://github.com/ianlancetaylor/libbacktrace](url). It failed with the following error.

```
Power-Mac-G5:build vkosikhin$ make -j4
[ 14%] Built target idlib
[ 33%] Built target base
[ 54%] Built target d3xp
[ 55%] Linking CXX executable dhewm3.app/Contents/MacOS/dhewm3
Undefined symbols:
  "___builtin_bswap32", referenced from:
      _macho_add in libbacktrace.a(macho.o)
      _macho_add_fat in libbacktrace.a(macho.o)
      _macho_add_fat in libbacktrace.a(macho.o)
      _macho_add_fat in libbacktrace.a(macho.o)
  "___builtin_bswap64", referenced from:
      _macho_add_fat in libbacktrace.a(macho.o)
ld: symbol(s) not found
collect2: ld returned 1 exit status
make[2]: *** [dhewm3.app/Contents/MacOS/dhewm3] Error 1
make[1]: *** [CMakeFiles/dhewm3.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by DanielGibson** [comment]
though for libbacktrace, you *could* try to add the following to the beginning of [macho.c](https://github.com/ianlancetaylor/libbacktrace/blob/master/macho.c), after the `#include` lines:

```c
static inline uint16_t swap16(uint16_t x)
{
	uint16_t ret = ((x & 0xFF) << 8) | (x >> 8);
	return ret;
}

static inline uint32_t __builtin_bswap32(uint32_t x)
{
	uint32_t ret = ((uint32_t)swap16(x & 0xFFFF) << 16);
	ret |= swap16(x >> 16);
	return ret;
}

static inline uint64_t __builtin_bswap64(uint64_t x)
{
	uint64_t ret = ((uint64_t)__builtin_bswap32(x & 0xFFFFFFFFu) << 32);
	ret |= __builtin_bswap32(x >> 32);
	return ret;
}

```

but if libbacktrace has more issues than missing bswap I'm really out of ideas :)

**Comment by vkosikhin** [comment]
Thank you, I'll try out this fix. No big deal if it doesn't work.
