### ISSUE TITLE
shadow is broken 

### ISSUE THREAD

**Issue by skysix2** [dhewm/dhewm3#572]
on my 2 PC
1: laptop Dell Vostro 15 5510 ,
 CPU 11th Gen Intel Core i5-11300H ,
 GPU integrated Intel TigerLake-LP GT2 [Iris Xe Graphics] ,
 RAM 16GB ,
 DRIVER mesa 23.3.6
 fedora 39
2: small desktop
 CPU Ryzen 2400G ,
 GPU integrated vega 11 ,
 RAM 8GB ,
 DRIVER mesa 23.1.0
 manjaro (arch-linux)

dhewm3 1.5.3 download from here,  shadow is broken in both systems, creating dark polygons that flicker:
![d3-1 5 3-shot00002](https://github.com/dhewm/dhewm3/assets/105243640/44ac5f7c-4690-48d3-9d3f-d25dc8bb9d26)
![d3-1 5 3-shot00003](https://github.com/dhewm/dhewm3/assets/105243640/aa6d7214-e2fd-42f0-87ae-dd84145e4479)
![d3-1 5 3-shot00004](https://github.com/dhewm/dhewm3/assets/105243640/ece51df9-b4c0-4cd5-8992-a29a05d774c9)

dhewm3 1.5.2 download from here,  shadow is fine on ryzen, and have a few issue on intel as seen in these screenshots:
![d3-1 5 2-shot00002](https://github.com/dhewm/dhewm3/assets/105243640/428f242f-659b-4214-90a1-e55f655592cd)
![d3-1 5 2-shot00003](https://github.com/dhewm/dhewm3/assets/105243640/144b99fa-aee7-400b-8a4a-7843b8b3d9c0)
![d3-1 5 2-shot00005](https://github.com/dhewm/dhewm3/assets/105243640/16a5e2ee-ac80-436f-8f62-cbc1e0c507a4)
![d3-1 5 2-shot00006](https://github.com/dhewm/dhewm3/assets/105243640/6ae5b05d-c798-40d8-a6f4-cf5af3486651)

or could it be a temporary driver problem ? or configuration ?

**Comment by DanielGibson** [comment]
I can reproduce the issue, both with mesa and nvidias driver.
The weird thing is that it only happens with the release binaries from the download page, not when I compile dhewm3 myself on my regular systems.
The release binaries are built in an old chroot so they're more compatible with older distros, but I don't think I changed anything in the chroot between 1.5.2 and 1.5.3

**Comment by DanielGibson** [comment]
Does this build work better: [dhewm3-1.5.3try2_Linux_amd64.tar.gz](https://github.com/dhewm/dhewm3/files/15033532/dhewm3-1.5.3try2_Linux_amd64.tar.gz) ?

(I'll also have to rebuild the mods for Linux, so far only the base game and Resurrection of Evil should be fixed)

**Comment by skysix2** [comment]
ok I'll try as soon as I can and I'll let you know
I also tried to compile from sources but I get a binary of about 20MB, whereas yours is only about 4MB,
Can you tell me exactly which cmake switches you use?

**Comment by DanielGibson** [comment]
For the release binaries I use `cmake -DDEDICATED=ON -DLINUX_RELEASE_BINS=ON -DCMAKE_BUILD_TYPE=Release`

`CMAKE_BUILD_TYPE` defaults to "RelWithDebInfo", i.e. an optimized release build with debug symbols, while build type "Release" will not contain debug symbols. That explains why your binary is bigger.

**Comment by DanielGibson** [comment]
also updated to mods: [dhewm3-mods-1.5.3try2_Linux_amd64.tar.gz](https://github.com/dhewm/dhewm3/files/15038949/dhewm3-mods-1.5.3try2_Linux_amd64.tar.gz)

**Comment by skysix2** [comment]
here we are, tested on the Intel laptop
ok now it behaves like version 1.5.2, no more flickering dark polygons, the lights are always rendered as precise circles, but given that on Ryzen the rendering of version 1.5.2 is correct, I think it's just a hardware problem, not much powerful

For the Ryzen test I have to make you wait a little longer
thanks
