### ISSUE TITLE
A widescreen hud fix

### ISSUE THREAD

**Issue by gabs234s** [dhewm/dhewm3#579]
Dhewm 3 does not have a proper widescreen hud because the hud is streched. I hope the dhewm3 source port has a proper fix for the widescreen hud by 1.5.4

**Comment by ViperAcidZX** [comment]
It does not sadly (I wish though) and the HUD is still stretched when playing on resolutions wider than 4:3. The only port that does have a widescreen  fix for the HUD is CstDoom3 as far as I'm aware.

**Comment by DanielGibson** [comment]
see https://github.com/dhewm/dhewm3/issues/324
