### ISSUE TITLE
Perfected Dhewm 3

### ISSUE THREAD

**Issue by Trey336** [dhewm/dhewm3#580]
Uh.....this topic was talked about years ago. But I've talked to the creator of the perfected doom 3 mod (VGAMES by the way) on discord. He gave me  the OK to make a compatible library file for windows and Linux. The thing is, I don't know if that's OK to do, as I have little knowledge on creating such files. As determined as I was, I decided to ask him some questions about doing so. It was revealed that I had to combine his code with the code of dhewm 3's sources. As I said I have little knowledge of what I'm supposed to do (another way to say that I'm not as smart as I thought I was). So the only questions I have is, 1. Is it possible to do it? 2.Do we need more permission for anything else? 3. Who's willing on helping him out?

**Comment by DanielGibson** [comment]
You only need permission from whoever wrote the C++ code for the mod (or holds its rights).
You'll want to merge the changes into dhewm3-sdk instead of dhewm3 itself, see https://github.com/dhewm/dhewm3-sdk

see also https://github.com/dhewm/dhewm3-sdk?tab=readme-ov-file#how-to-port-a-mod-to-dhewm3

**Comment by DanielGibson** [comment]
I just updated the "How to port a Mod" section, it's much more detailed now.

**Comment by Trey336** [comment]
Well I will give it a try, thanks for making it more detailed.

**Comment by Trey336** [comment]
> I just updated the "How to port a Mod" section, it's much more detailed now.

Hi! I'm back again. I've made some progress but when building I get precompiled.h error, the thing is I removed it but I've gotten 1 warning and 20 errors....
Ex. fatal error: too many errors emitted, stopping now [-ferror-limit=]
make[2]: *** [CMakeFiles/base.dir/build.make:76: CMakeFiles/base.dir/game/AF.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
1 warning and 20 errors generated.                   make[2]: *** [CMakeFiles/base.dir/build.make:104: CMakeFiles/base.dir/game/Actor.cpp.o] Error 1
1 warning and 20 errors generated.                   make[2]: *** [CMakeFiles/base.dir/build.make:90: CMakeFiles/base.dir/game/AFEntity.cpp.o] Error 1
1 warning and 20 errors generated.                   make[2]: *** [CMakeFiles/base.dir/build.make:118: CMakeFiles/base.dir/game/Camera.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:111: CMakeFiles/base.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

Do you know what am I doing wrong or is this not enough info?

**Comment by DanielGibson** [comment]
this doesn't contain much useful info, but I assume that you need to include other headers.
scroll the compiler error messages all the way up and try to fix the first one.
then compile again, and repeat until all errors are gone

**Comment by Trey336** [comment]
Sorry that it wasn't very useful but.....it's this error, the first one that pops up is:


/data/data/com.termux/files/home/doom3dev/dhewm3-sdk/game/Actor.cpp/data/data/com.termux/files/home/doom3dev/dhewm3-sdk/game/AF.cpp::1423::66::  error: error: use of undeclared identifier 'idAnimState'use of undeclared identifier 'idAF'

**Comment by Trey336** [comment]
Sorry if it wasnt useful........My computer is dead I, copied my files to my phone so I can do this on the bus too. But I have this app called termux and used it I and sometimes the error is different when I use the make command in the build directory. This error keeps popping up on my a14

/data/data/com.termux/files/home/doom3dev/dhewm3-sdk/game/Actor.cpp/data/data/com.termux/files/home/doom3dev/dhewm3-sdk/game/AF.cpp::1423::66::  error: error: use of undeclared identifier 'idAnimState'use of undeclared identifier 'idAF'

It's the first one.

**Comment by DanielGibson** [comment]
Did you get this to work?

**Comment by DanielGibson** [comment]
I managed to port the mod and make it compile, didn't test it yet.

Before I can release that: Did the author or Perfected Doom3 (VGames, and whoever else worked on it or whose code he copied) agree to license his code changes under GPL?
The released source uses the Doom3 SDK license, which is incompatible.

It seems to mostly be Sikkmod code (which has recently been ported to dhewm3 SDK), but also has custom changes a "doomtrinity-dual weapon" mod(?) is also mentioned.

**Comment by Trey336** [comment]
Hold on let me contact him

**Comment by Trey336** [comment]
He said:
![Polish_20240717_160508417](https://github.com/user-attachments/assets/585bfc2e-93c8-4b64-9a12-8df1effa396d)

**Comment by Trey336** [comment]
Also did you compile on all platforms such as linux?

**Comment by Trey336** [comment]
He also agrees of the change of license under GPL

**Comment by DanielGibson** [comment]
Thanks for getting permission!

Here's the ported source: https://github.com/dhewm/dhewm3-sdk/tree/perfected

So far I've only compiled it on Linux, but I see no reason why it shouldn't build on other platforms - let me know if any problems arise.

**Comment by Trey336** [comment]
Thanks, Daniel!!
