### ISSUE TITLE
Missing DLL Launch Errors Even After Clean Windows Reinstall

### ISSUE THREAD

**Issue by HardDiskDog** [dhewm/dhewm3#590]
UPDATE: Installing the x86 Visual C++ 2017 redistributable got rid of the error, but the game still silently crashes on startup without even a window opening. No other redistributables (https://www.majorgeeks.com/files/details/visual_c_runtime_installer.html) make a difference.

---

All of a sudden, trying to launch the Dhewm3 1.5.3 executable started giving me the same "The code execution cannot proceed because [file] was not found. Reinstalling the program may fix this problem" errors in a row every time for the following files, preventing startup:
-VCRUNTIME140.dll (pops up one-to-three times, with occurrence rate varying by instance)
-mfc140.dll (pops up once-to-twice)

I am currently unable to continue my playthrough, and even a 100% clean reinstall of Windows 11 under a different Microsoft account (which was mainly to fix Windows repeatedly swallowing my Pictures folder) with nothing but my secondary hard drive left over (I put Dhewm3 on my primary/OS install NVME) did not put a dent in this issue.

I have pak00-08.pk4 copied into Dhewm3's base folder, have tried copying over the Dhewm3 executable and parent folder .dll's over to my offline GOG version vanilla Doom 3 folder instead, and tried Dhewm3 version 1.5.2; all with the same exact result. Vanilla Doom 3 still launches fine.

**Comment by DanielGibson** [comment]
I guess this can also be closed, as the underlying issue should be the same as in #592: corrupted game data
