### ISSUE TITLE
1.5.4rc1: low performance

### ISSUE THREAD

**Issue by Manoa1911** [dhewm/dhewm3#594]
I get extremely low fps with sikkmod 1.2
original Doom 3: 24 fps
dhewm 1.5.4rc1: 9 fps
resolution 4K
with and without vsync/adaptive
transferred my autoexec.cfg from doom3 base but the performance did not change
RTX 3090 Ti
driver 537.58
Windows 10
I tried to disable/enable soft particules but had no effect on performance

**Comment by DanielGibson** [comment]
are there also performance differences in regular doom3 (without sikkmod)?

**Comment by Manoa1911** [comment]
no change with doom3.exe
no change with sikkmod off
I will see when I can do a new driver update, thank :)
