### ISSUE TITLE
Does not work with lost mission (see description)

### ISSUE THREAD

**Issue by jgs1989** [dhewm/dhewm3#601]
I am using the batch file that comes with the lost mission that launches it using dhewm3.  Launching dhewm3 and then loading the lost mission mod from main menu produces the same error.
![Lost Mission error](https://github.com/user-attachments/assets/6af20c1b-f4e9-466d-a55f-6c9313fb4dbb)

**Comment by jgs1989** [comment]
Disregard, I am an idiot....did not realize you needed separate DLL's for the lost mission.  Sorry about that.

**Comment by DanielGibson** [comment]
glad it works now =)

**Comment by jgs1989** [comment]
Thanks!  Just want to say I really enjoy dhewm3 and all that it does to enhance Doom 3 without altering the feel/gameplay.  I appreciate all the work you have put into it!
