### ISSUE TITLE
Severe performance regression due to soft particles in 1.5.4

### ISSUE THREAD

**Issue by ghost** [dhewm/dhewm3#604]
1.5.4 has significantly higher GPU usage than 1.5.3 whenever particles are on screen, going from ~35% to over 80% on my system (Ryzen 5 5600G, Vega 8 iGPU on Windows). This is caused by soft particles, which are now enabled by default.

I'm not sure if the poor performance on my system is a symptom of my hardware or a bug/optimization issue.
Regardless, soft particles should probably be disabled by default so that unaware users aren't faced with significant performance degradation after updating (especially on Intel iGPUs where performance is already limited).

No soft particles, 36% usage:
![image](https://github.com/user-attachments/assets/d93eb061-24fe-4e48-bc88-021cd52d4c66)
No soft particles, capture depth buffer to texture, 40% usage:
![image](https://github.com/user-attachments/assets/7555b0a6-cbca-4ee5-86dc-1383afc046c9)
Soft particles, 80% usage:
![image](https://github.com/user-attachments/assets/eb4fa997-6059-4078-a6d2-b17f55cdd36a)
Performance is the same in both windowed and fullscreen, windowed was used here to take a screenshot

**Comment by xmansch** [comment]
i have the same problem

**Comment by xmansch** [comment]
,

> 1.5.4 has significantly higher GPU usage than 1.5.3 whenever particles are on screen, going from ~35% to over 80% on my system (Ryzen 5 5600G, Vega 8 iGPU on Windows). This is caused by soft particles, which are now enabled by default.
> 
> I'm not sure if the poor performance on my system is a symptom of my hardware or a bug/optimization issue. Regardless, soft particles should probably be disabled by default so that unaware users aren't faced with significant performance degradation after updating (especially on Intel iGPUs where performance is already limited).
> 
> No soft particles, 36% usage: ![image](https://private-user-images.githubusercontent.com/52540509/356401982-d93eb061-24fe-4e48-bc88-021cd52d4c66.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0NTk0ODYsIm5iZiI6MTcyMzQ1OTE4NiwicGF0aCI6Ii81MjU0MDUwOS8zNTY0MDE5ODItZDkzZWIwNjEtMjRmZS00ZTQ4LWJjODgtMDIxY2Q1MmQ0YzY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEyVDEwMzk0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxNjlmZWVlYWNjM2M5MDNhMzIyYTgyMzM4OTUyMzA0YmE1NDM2MDYxMjZkZWRiZGE4N2JlMDM2MDVkOTcwMTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.inu05DGTU3P04LVosE7l5aIjrAEeMx9tRLlfNwPche4) No soft particles, capture depth buffer to texture, 40% usage: ![image](https://private-user-images.githubusercontent.com/52540509/356402100-7555b0a6-cbca-4ee5-86dc-1383afc046c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0NTk0ODYsIm5iZiI6MTcyMzQ1OTE4NiwicGF0aCI6Ii81MjU0MDUwOS8zNTY0MDIxMDAtNzU1NWIwYTYtY2JjYS00ZWU1LTg2ZGMtMTM4M2FmYzA0NmM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEyVDEwMzk0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5YTA5YmFkOWVjYjMzNDY2MTUwZGM4ODkwYzJhMWVhNGVlNTU0NTFhODljY2Q2NGU3ZTZmZWQ2MGMxNmMyNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OlKNGTcGDNTu0qkw0_24eLeG7Rskq7zz0EKHS6S59r8) Soft particles, 80% usage: ![image](https://private-user-images.githubusercontent.com/52540509/356402050-eb4fa997-6059-4078-a6d2-b17f55cdd36a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0NTk0ODYsIm5iZiI6MTcyMzQ1OTE4NiwicGF0aCI6Ii81MjU0MDUwOS8zNTY0MDIwNTAtZWI0ZmE5OTctNjA1OS00MDc4LWE2ZDItYjE3ZjU1Y2RkMzZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEyVDEwMzk0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzMzAyYjgzMWRmOWU4NmE5ZGE4NTZhYjE3MmQ4N2JjMjVjZjNmZDFjZDM2MDc5Mjc4YzlmZjNmYzU5OWFlNzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eT53EndfAfMmzC8UgyNtM1_HoVrszqJ0o1BqrtT8bYQ) Performance is the same in both windowed and fullscreen, windowed was used here to take a screenshot

what about perfomance, when you disable soft particales ?

**Comment by DanielGibson** [comment]
I'm not sure I want to disable this by default - do you think it would be sufficient if it were disabled when setting a Performance Preset below Ultra?
That would mean that it's still enabled by default, but if someone sets the performance preset to "high" or "medium" or "low" (because performance is bad on their system), soft particles get disabled.
