### ISSUE TITLE
Save files in the installation folder possible?

### ISSUE THREAD

**Issue by vlad54rus** [dhewm/dhewm3#609]
I'd like to keep the game portable on my USB drive but couldn't figure out how to set it with with dhewm3.

**Comment by DanielGibson** [comment]
It should be possible to set the `fs_savepath` and `fs_configpath` CVars to the installation folder, like `dhewm3.exe +set fs_savepath "D:\Doom3\" +set fs_configpath "D:\Doom3\"` or similar, assuming that the installation folder is "D:\Doom3\".

For a portable installation that's a bit harder, but should be possible with a batch script, like create a dhewm3.bat (next to dhewm3.exe) with the following *(untested!)*
```bat
;; the following sets the scriptpath variable to the directory dhewm3.bat is in
SET scriptpath=%~dp0
;; switch to that directory, so dhewm3.exe can be found in the next command
cd %scriptpath%
dhewm3.exe +set fs_savepath %scriptpath% +set fs_configpath %scriptpath%
```

**Comment by garoto** [comment]
I have this doskey macro setup:

`dhew=J:\Games\dhewm3\dhewm3.exe +set fs_basepath J:/Games/dhewm3 +set fs_configpath J:/Games/dhewm3 +set fs_savepath J:/Games/dhewm3 +disconnect $*`

@j4reporting: try setting up `fs_basepath` for the extra files that are not written to the game dir.

**Comment by vlad54rus** [comment]
@DanielGibson Works great, thank you. But you should fix dhewm3log.txt and stderr.txt still appearing in the Documents folder.

**Comment by DanielGibson** [comment]
That's not exactly easy, because those log files are created *before* the CVar system is initialized and thus before I can use the `fs_*` CVars to choose the configured path, so errors can be logged as soon as possible.

**Comment by vlad54rus** [comment]
Well, i guess my only option is to just delete them after Dhewm3 process exits.
