### ISSUE TITLE
Librecoop 1.5 FPS drop in dhewm3 1.5.4

### ISSUE THREAD

**Issue by gut5** [dhewm/dhewm3#614]
**Describe the bug**

Librecoop 1.5 alpha runs very poorly (low FPS compared to normal Doom 3 ) https://www.moddb.com/mods/librecoop-dhewm3-coop/downloads/librecoop-alpha-15-windows-32bits

**Your System**
- What **operating system** are you using, what CPU and GPU, which GPU driver version?

Windows 10, Ryzen 2300, Radeon Vega 6, Adrenalin 24.3.1

- What **version of dhewm3** are you using? (Also: Official download? Package from Linux distro? MacSourcePorts? Did you compile yourself?)

dhewm3 1.5.4 (github release)

**To Reproduce**
Describe how to reproduce the bug
- if it happens while playing: What mod (base game, RoE, or some 3rd-party mod), which level, what do you do there to trigger the bug
    - After opening the console (`Shift`+`Esc`) you can enter `map` to print the current map name and `where` to print the coordinates in the level
- if it happens in the menu or similar: describe the steps to trigger the bug

Just try running Librecoop in single-player (FPS drop still happens in single-player)

**Expected and actual behavior**
A clear and concise description of what you expected to happen and what happens instead

I expect the game to run at 60fps, it runs at a stable 60fps otherwise
![Screenshot (169)](https://github.com/user-attachments/assets/4d599e9e-90fb-41be-8ddc-f2e0e1b81b15)

**Additional information**
If applicable, add screenshots or a video to help explain your problem.
Please attach [dhewm3log.txt](https://github.com/dhewm/dhewm3/wiki/FAQ#where-do-i-find-the-config-files-and-savegames-and-dhewm3logtxt)
A **savegame** also often helps to more quickly reproduce a bug

**Comment by DanielGibson** [comment]
Thanks for trying it out!

Does it work better with 1.5.3 or any other older 1.5.x release?

(I'm wondering if it's a regression, as the issue hasn't been reported before)

**Comment by DanielGibson** [comment]
Thanks for testing!

I'm sure that other people have played LibreCoop before..
I'll try it myself to see if I can reproduce it on one of my machines (I briefly tested librecoop on my main PC before the last release and didn't notice bad performance)

To be clear: Is the performance always bad or just in some scenes?
Like, if you just start a new game, is the framerate already low in the very first scene (in the hangar near the spaceship)?

>  but is the expectation that regular Doom 3 would run at the same speed as someone running the Librecoop mod

I'd generally expect the performance to be similar.
However, I'm not familiar with LibreCoop's code so I don't know what changes compared to regular Doom3 it has that could affect performance.
@Stradex do you have an idea?

**Comment by DanielGibson** [comment]
I can neither reproduce this on my main PC (Linux, Ryzen 5950X, Geforce 3060Ti) nor on my secondary PC (Win10, Ryzen 2700X, Radeon RX 580).
I get stable 60fps on both systems (at least in the scene I tested, the beginning of game/mars_city2 as shown on your screenshot), and running the `benchmark` command (with VSync disabled) gives similar results for the base game and librecoop

**Comment by gut5** [comment]
It's about 50% lower (the dropship scene starts at around 30-40fps, normal FPS for my machine is a stable 60) than I'd expect from the very start and then varies by area as I play. It's always noticeably and consistently lower than it would be outside Librecoop.

**Comment by gut5** [comment]
> I can neither reproduce this on my main PC (Linux, Ryzen 5950X, Geforce 3060Ti) nor on my secondary PC (Win10, Ryzen 2700X, Radeon RX 580). I get stable 60fps on both systems (at least in the scene I tested, the beginning of game/mars_city2 as shown on your screenshot), and running the `benchmark` command (with VSync disabled) gives similar results for the base game and librecoop

I'm going to try refreshing my graphics driver, idk what else it could be. Thanks for checking.

**Comment by DanielGibson** [comment]
Random idea: Does the behavior change if you disable VSync?

And can you see somewhere how much your CPU cores and your GPU are utilized while playing?

**Comment by gut5** [comment]
Disabling vsync actually fixed it. 
Core usage and GPU don't reach anywhere close to even 50% which is what I'd expect.

**Comment by DanielGibson** [comment]
> Disabling vsync actually fixed it.
Interesting.
My theories regarding VSync were/are:
1. If you just get a little bit below 60fps, vsync will make it drop to 30 (because it missed the frame and will sync to the next), same with getting below 30 and 15.
2. At such low framerates, the CPU and/or GPU are probably bored and clock down, which might make everything even slower

> Core usage and GPU don't reach anywhere close to even 50% which is what I'd expect.

Well, if the performance sucks you'd think that at least one of them has very high usage - unless my theory from above is correct and they clock down because they're bored, or something similar.

Besides disabling VSync it *might* also help to enable some kind of performance mode that always keeps the CPU and/or GPU at its highest performance.

**Comment by gut5** [comment]
You're right, vsync was disabled for the main game for some reason.

Anyhow, thanks for helping out. I'll close this as resolved.
