### ISSUE TITLE
High mouse DPI values causes the game to stop responding to mouse input

### ISSUE THREAD

**Issue by b1tmask** [dhewm/dhewm3#616]
If you set your mouse to 400 or 800 DPI, the game responds to fast swipes just fine. However, if you set your mouse to 1600 DPI or higher and swipe quickly, the entire game will stop responding to mouse input. This problem does not happen when using the standard Steam Doom 3 or Doom 3 BFG edition.

**OS:** Windows 11
**Game Version:** dhewm3-1.5.4_win32 with Steam pak files
**Mice:** Tried several and the issue happens on all of them

I believe someone already created an issue for this but it was closed out due to lack of information. 
**Closed issue for the same problem:** Strange mouse behaviour #421

**Comment by vlad54rus** [comment]
Can confirm, although i only start noticing it on 2000+ DPI with a very quick swipes.

**Comment by DanielGibson** [comment]
I think you're running into this check: 
https://github.com/dhewm/dhewm3/blob/d94bb42d5048148f5358a3d7cf0f5bd6eb817f4a/neo/framework/UsercmdGen.cpp#L679-L682

I should probably remove it, or modify it to use higher values, or something like that.

**Comment by DanielGibson** [comment]
This should be resolved.
Testbuilds for Windows can be downloaded at https://github.com/dhewm/dhewm3/actions/runs/12145931500 - please test :)

**Comment by Srandista** [comment]
Non-related question, but since you brought testbuilds to the light: why you're not releasing 64-bit binaries for major releases, even tho you're building them form every commit?

**Comment by DanielGibson** [comment]
I'm doing 64bit Windows testbuilds to make sure it still builds on 64bit Windows.

The official releases for Windows are 32bit for several reasons:
* Doom3 has hand-optimized assembly code for 32bit x86 on Windows, so 32bit Windows builds might run faster than 64bit builds
* I only want one kind of binaries for official Windows build, as long as that's feasible (and it is, those 32bit binaries run just fine on Win64)
  - That's less work for me - the release binaries are built and tested manually
  - This reduces possible confusion for mod DLLs (mixing 64bit dhewm3.exe and 32bit sikkmod.dll or whatever doesn't work)
  - Yes, nowadays 32bit Windows isn't that relevant anymore (not sure if even still officially supported?), but when dhewm3 started it very much was, so shipping only 64bit binaries would've been a bad idea
