### ISSUE TITLE
Broken Flashlight beam?

### ISSUE THREAD

**Issue by ishboi96** [dhewm/dhewm3#617]
**Describe the bug**
Handheld flashlight beam appears broken in dhewm3 1.5.3/1.5.4

**Your System**
Windows 11, nvidia RTX 3090, intel i9 9900k, 32gb ddr4, downloaded dhewm3 from its official source. 

**To Reproduce**
Pull out the flashlight at any time during gameplay. Whether its a fresh install of D3 or a modded one, this occurs.

**Expected and actual behavior**
The flashlight in regular doom 3 does not produce this strange broken beam effect.

**Additional information**

![Screenshot 2024-09-15 000541](https://github.com/user-attachments/assets/05757764-12e9-42ff-a5f8-9c28a9db45e9)

**Comment by ishboi96** [comment]
I actually figured it out. I forgot I was loading dhewm 3 with special k. when I load dhewm 3 without it, the problem goes away.

**Comment by DanielGibson** [comment]
No idea what special k is, but glad it works now

**Comment by ishboi96** [comment]
> No idea what special k is, but glad it works now

https://www.special-k.info/ i use it to inject HDR into games that dont have it.
