### ISSUE TITLE
Please remove the lie that says that it supports Perfected DOOM 3, Perfected DOOM 3 requires DOOM 3's executable. Since yours does not require nor uses the executable it will not work.

### ISSUE THREAD

**Issue by TheTreeofDoom** [dhewm/dhewm3#618]
written in Title

**Comment by garoto** [comment]
cringe

**Comment by DanielGibson** [comment]
Please stop lying about dhewm3s capabilities.

It *does* support Perfected Doom3, see https://dhewm3.org/mods.html#perfected-doom-3
and the source for the mod DLL at https://github.com/dhewm/dhewm3-sdk/tree/perfected
