### ISSUE TITLE
Bugs when attempting to load Perfected DOOM 3

### ISSUE THREAD

**Issue by TheTreeofDoom** [dhewm/dhewm3#619]
Warning: using path of executable: C:dhewm3
On Line 517: material 'textures/particles/bloodcloud' previously defined at materials/weapon_doomtrinity.mtr:1
Couldn't load mod-specific Perfected.dll thus defaults to ease game's library.
When that occurs it leaves a notice that file script/doom_events.script line 13: Unknown event 'isLowered'

I'm not sure how or if this version (7.0) is supported, as you have said it is. I have un/reinstalled and verified DOOM 3's files. I've tried different folders (alone in the C drive and in my Steam folder). But, no matter what I have tried it ends up being futile. Yes, I followed everything that was typed up to the T by dropping the required base files into the required folders with Dhewm3 in a separated folder outside of the Steam installation and also tried it inside my Steam game installation folder. The source port shows that the mod is installed correctly but when I go to launch it via the mods section of the main menu it leaves behind the errors I mentioned at the top of this post. This problem does not arise on the base game but arises only on the source port. If there was a more step-by-step process into how I could fix such a problem maybe my issue could be resolved. My only other guess is that this mod is broken but that wouldn't explain as to why it works on the base game but not the source port.

My Hardware:
AMD Ryzen 5 8645HS 4.3GHz
Nvidia RTX 4050 6gb VRAM
64gb RAM
Windows 11 Pro

**Comment by DanielGibson** [comment]
Perfected Doom3 7.0.2 is supported.
Do you have perfected.dll from the dhewm3-mods archive next to dhewm3.exe?

**Comment by TheTreeofDoom** [comment]
ah... you know I feel really stupid now lol. I didn't notice that file underneath the assets lmao. Thanks!
