### ISSUE TITLE
Can't run game with Imgui enabed during the compilation

### ISSUE THREAD

**Issue by Srandista** [dhewm/dhewm3#632]
When I compile any version past the 1.5.3, I'll get an error pointing to Imgui during the start of the game. 1.5.3 works out of the box, 1.5.4 and current Git source does work, if I disable Imgui during the cmake phase. Interestingly, 1.5.4 precompiled binaries from GitHub release tab works as well.

I'm compiling the code on my Xubuntu 24.04, on Ryzen 5 3600 and Radeon RX 6800. GCC is version 13.2.0

I'm getting the same error on my Raspberry Pi, where also with disabled Imgui game starts just fine. OS there is Debian Bookworm based Raspberry Pi OS with GCC 12.2.0.

I'm attaching logs from both systems with compilation and running phase,

[dhewm3_Xubuntu.txt](https://github.com/user-attachments/files/17964869/dhewm3_Xubuntu.txt)
[dhewm3_RPi.txt](https://github.com/user-attachments/files/17964870/dhewm3_RPi.txt)

**Comment by DanielGibson** [comment]
Interesting.
Does this change fix it?
```diff
diff --git a/neo/sys/sys_imgui.cpp b/neo/sys/sys_imgui.cpp
index 82448b96..ec488ef6 100644
--- a/neo/sys/sys_imgui.cpp
+++ b/neo/sys/sys_imgui.cpp
@@ -225,6 +225,9 @@ static float GetDefaultScale()
        // TODO: different reference DPI on mac? also, doesn't work that well on my laptop..
        float ret = GetDefaultDPI() / 96.0f;
 #endif
+       if (ret <= 0.0f) {
+               return 1.0f;
+       }
        ret = round(ret*2.0)*0.5; // round to .0 or .5
        return ret;
 }
```

**Comment by Srandista** [comment]
Perfect, that worked! Thank you for quick fix!

**Comment by DanielGibson** [comment]
Thanks for testing! :)
