### ISSUE TITLE
Possibility to set config files in the executable directory or choose the location

### ISSUE THREAD

**Issue by Tartifless** [dhewm/dhewm3#636]
**Describe the feature you want**
Windows : possibility to set a different path for config files than in USER\Documents\My Games, have a fully portable installation

**What problem does it solve?**
Possibility to have dhewm3 on a dedicated external drive and bring it with me on holiday or to friends

**Comment by DanielGibson** [comment]
This is already possible, see https://github.com/dhewm/dhewm3/issues/609#issuecomment-2294887546

**Comment by Tartifless** [comment]
That works perfectly fine, thanks
