### ISSUE TITLE
Can't start Resurection of Evil

### ISSUE THREAD

**Issue by Gps2010** [dhewm/dhewm3#90]
After compiling and playing through Doom3, I wanted to play the expansion pack again.

Linux (openSUSE 12.3 64 bit )

I had some problems and then I copied all pks files, to the d3xp folder. ( all 13)

Then I started doom3, and it asked for my ROE cd key.
II typed it in, and all seemed fine.
Under mods I selected d3xp.
Then I click new game, and picked marine.

But during loading I get an error.

==== Processing events ====
SpawnPlayer: 0
loaded collision model models/weapons/shell1/mshell_lo.lwo
loaded collision model models/weapons/shell1/sshell_bigger.lwo
TODO: Sys_SetClipboardData
----- Game Map Shutdown -----

---

ERROR: Unknown weapon in decl 'weapon_bloodstone_passive'

---

]exit

I am totally lost on what is wrong.

If it matters I bought this game through steam, and I have played through doom3 and roe on windows 7,
now trying to play it again on openSUSE.

**Comment by mkrupczak3** [comment]
On Ubuntu (not compiling from source), I found that ROE wouldn't launch. I'd get the following error:

`ERROR: Function 'map_erebus1::main' not found in script for 'call' key on worldspawn`

To fix this, I had to install the following package to obtain the missing `d3xp.so` binary:

`sudo apt install dhewm3-d3xp`

After that, everything worked!

This was in addition to the `dhewm3` and `dhewm3-doom3` packages
