### ISSUE TITLE
Intel HD 4000 gfx problem

### ISSUE THREAD

**Issue by Tom01** [dhewm/dhewm3#91]
Graphics is garbage on Intel HD 4000 OS X 10.8.4

**Comment by DanielGibson** [comment]
any update on this or can it be closed?

**Comment by Tom01** [comment]
no update, it can be closed. ( I have a Radeon card now).

Thomas Bodlien
creative-software-design@t-online.de

**Comment by DanielGibson** [comment]
ok, Danke für die schnelle Antwort! :-)
