### ISSUE TITLE
Network client FX

### ISSUE THREAD

**Issue by Wintch** [dhewm/dhewm3#95]
Hi,
I am trying to get network game look identical to singleplayer with no luck.
Blood from players and FX particles are only shown on server side.
Can it be related to ASYNC_WRITE_PVS? I tried both values, still without success.
Raven had solved this issue somehow in Quake4, SDK could have the answer...

Thanks for the great job!

**Comment by Wintch** [comment]
Still happens with my setup. But i managed to get it working online on legacy doom3 ROE. Any ideas?

**Comment by DanielGibson** [comment]
so it only happens in dhewm3, but not with the original doom3 binaries?

**Comment by Wintch** [comment]
Until yesterday i was sure it is idtech4 related bug, or even something done on purpose to reduce network bandwidth. But i just entered random server last night and when i shot, those particles spawned on the wall when the bullet impact are there. Really need to test it again to confirm you
