### ISSUE TITLE
copyright stuff

### ISSUE THREAD

**Issue by darealshinji** [dhewm/dhewm3#99]
I just realized that neo/renderer/wglext.h is still mentioned in the readme, but the file is no longer among the sources.
And the license of neo/idlib/hashing/CRC32.cpp is not mentioned. Since it's copyrighted by Mark Adler I'm 99% sure it's Zlib license.

**Comment by DanielGibson** [comment]
thanks, I'm removing the mentioning of wglext.h

yeah, it most probably is under zlib license, but CRC32.cpp and CRC32.h don't mention any license either, so I'm not sure.. and I'm not sure if I should change anything in the copyright notices that were put there by id Software/Zenimax...
So I guess I'll just keep it like it is.
